:ON ERROR EXIT

USE [DeineDatenbank];
GO

/*
SQLCMD-Installer für den vollständigen Frameworkbestand.
Vor Ausführung den Platzhalter [DeineDatenbank] in allen SQL-Dateien ersetzen
und in SSMS/ADS den SQLCMD-Modus aktivieren.
Der Installer beendet die Verarbeitung beim ersten SQL-Fehler.
*/

:r ../00_Setup/000_Preflight_und_Schema.sql
:r ../01_Common/010_VW_ModuleStatusCatalog.sql
:r ../01_Common/020_VW_AnalyseClassCatalog.sql
:r ../01_Common/021_VW_AnalysisCatalog.sql
:r ../01_Common/022_VW_AnalysisSearchTerm.sql
:r ../01_Common/023_VW_AnalysisRelation.sql
:r ../01_Common/030_VW_AnalyseAccessPolicy.sql
:r ../01_Common/040_VW_AnalyseAccessCurrent.sql
:r ../01_Common/050_USP_CheckAnalyseAccess.sql
:r ../01_Common/060_VW_FrameworkFeatureCatalog.sql
:r ../01_Common/074_WaitTypeCatalog.sql
:r ../01_Common/074a_WaitTypeCatalog_Seed_01.sql
:r ../01_Common/074b_WaitTypeCatalog_Seed_02.sql
:r ../01_Common/074c_WaitTypeCatalog_Seed_03.sql
:r ../01_Common/074d_WaitTypeCatalog_Seed_04.sql
:r ../01_Common/074e_WaitTypeCatalog_Analysis.sql
:r ../01_Common/074f_WaitTypeCatalog_Source_Seed.sql
:r ../01_Common/075_TVF_WaitTypeInfo.sql
:r ../01_Common/075a_TVF_WaitTypeSources.sql
:r ../01_Common/076_TVF_QueryStoreWaitCategoryInfo.sql
:r ../01_Common/077_FrameworkVersion.sql
:r ../01_Common/078_TVF_ParsePipeList.sql
:r ../01_Common/079_TVF_ParsePattern.sql
:r ../01_Common/080_TVF_ParseSqlNameList.sql
:r ../01_Common/081_TVF_ParseFullObjectNameList.sql
:r ../01_Common/082_TVF_DatabaseCandidates.sql
:r ../01_Common/083a_USP_InternalCheckAnalysisPath.sql
:r ../01_Common/083_USP_PrepareDatabaseCandidates.sql
:r ../01_Common/084_USP_PrepareNameFilters.sql
:r ../01_Common/085_TVF_ParseBigintList.sql
:r ../01_Common/086_TVF_ParseStringList.sql
:r ../01_Common/086a_TVF_ParseBlockingResource.sql
:r ../01_Common/087_TVF_StatementText.sql
:r ../01_Common/087a_ToolBackgroundQueryPattern.sql
:r ../01_Common/087b_ToolBackgroundQueryPattern_Seed.sql
:r ../01_Common/087c_TVF_ToolBackgroundQueryInfo.sql
:r ../01_Common/087d_TVF_ProjectUnicodeText.sql
:r ../01_Common/087e_TVF_ClassifyErrorLogEvent.sql
:r ../01_Common/098_USP_InternalProjectUnicodeTextColumn.sql
:r ../01_Common/088_TVF_InterpretPerformanceCounter.sql
:r ../01_Common/089_TVF_InterpretContentionCounter.sql
:r ../01_Common/090_TVF_InterpretAvailabilityDatabaseState.sql
:r ../01_Common/091_TVF_InterpretAvailabilitySeedingState.sql
:r ../01_Common/092_TVF_InterpretAgentAlertRoute.sql
:r ../01_Common/093_TVF_InterpretAgentJobState.sql
:r ../01_Common/094_TVF_InterpretDatabaseMailStatus.sql
:r ../01_Common/095_USP_InternalWriteResultTable.sql
:r ../01_Common/096_USP_InternalPrepareResultTables.sql
:r ../01_Common/097_USP_InternalPrepareSingleResultTable.sql
:r ../01_Common/098_USP_InternalEmitConsoleResult.sql
:r ../01_Common/099_USP_InternalEmitTruncationWarning.sql
:r ../01_Common/099a_USP_InternalParseXmlText.sql
:r ../01_Common/070_USP_CheckFrameworkCapabilities.sql
:r ../01_Common/100_USP_AnalysisNavigator.sql
:r ../02_CurrentState/005_InternalCaptureCurrentStateSnapshot.sql
:r ../02_CurrentState/010_USP_CurrentSessions.sql
:r ../02_CurrentState/020_USP_CurrentRequests.sql
:r ../02_CurrentState/030_USP_CurrentBlocking.sql
:r ../02_CurrentState/040_USP_CurrentWaits.sql
:r ../02_CurrentState/050_USP_CurrentTransactions.sql
:r ../02_CurrentState/060_USP_CurrentMemoryGrants.sql
:r ../02_CurrentState/070_USP_CurrentTempDB.sql
:r ../02_CurrentState/080_USP_CurrentIO.sql
:r ../02_CurrentState/090_USP_CurrentLog.sql
:r ../02_CurrentState/100_USP_CurrentOverview.sql
:r ../03_ObjectIndex/010_USP_ObjectInventory.sql
:r ../03_ObjectIndex/020_USP_IndexUsage.sql
:r ../03_ObjectIndex/025_USP_IndexOperationalStats.sql
:r ../03_ObjectIndex/030_USP_MissingIndexes.sql
:r ../03_ObjectIndex/040_USP_Statistics.sql
:r ../03_ObjectIndex/045_USP_StatisticsDistributionAnalysis.sql
:r ../03_ObjectIndex/050_USP_Partitions.sql
:r ../03_ObjectIndex/060_USP_Columnstore.sql
:r ../03_ObjectIndex/070_USP_IndexPhysicalStats.sql
:r ../03_ObjectIndex/075_USP_VectorIndexAnalysis.sql
:r ../03_ObjectIndex/090_USP_SchemaDesignAnalysis.sql
:r ../03_ObjectIndex/080_USP_ObjectAnalysis.sql
:r ../04_PlanCache/010_USP_QueryStats.sql
:r ../04_PlanCache/020_USP_QueryHashAnalysis.sql
:r ../04_PlanCache/030_USP_PlanCacheHealth.sql
:r ../04_PlanCache/040_USP_PlanDetails.sql
:r ../04_PlanCache/041_PlanAnalysisProfile.sql
:r ../04_PlanCache/042_PlanAnalysisRuleThreshold.sql
:r ../04_PlanCache/043_PlanAnalysisProfileAssignment.sql
:r ../04_PlanCache/044_TVF_ParseStatisticsIoText.sql
:r ../04_PlanCache/045_TVF_ParseStatisticsTimeText.sql
:r ../04_PlanCache/046_TVF_ExecutionPlanObjectReferences.sql
:r ../04_PlanCache/047_TVF_ExecutionPlanStatisticsUsage.sql
:r ../04_PlanCache/048_TVF_ExecutionPlanColumnReferences.sql
:r ../04_PlanCache/049_InternalCollectExecutionPlanMetadata.sql
:r ../04_PlanCache/051_InternalAnalyzeExecutionPlan.sql
:r ../04_PlanCache/052_USP_CreateExecutionEvidenceJson.sql
:r ../04_PlanCache/053_USP_ExecutionPlanAnalysis.sql
:r ../04_PlanCache/050_USP_ShowplanAnalysis.sql
:r ../04_PlanCache/060_USP_PlanCacheAnalysis.sql
:r ../05_QueryStore/010_USP_QueryStoreStatus.sql
:r ../05_QueryStore/020_USP_QueryStoreRuntimeStats.sql
:r ../05_QueryStore/030_USP_QueryStoreWaitStats.sql
:r ../05_QueryStore/040_USP_QueryStorePlanChanges.sql
:r ../05_QueryStore/050_USP_QueryStoreRegressions.sql
:r ../05_QueryStore/060_USP_QueryStoreForcedPlans.sql
:r ../05_QueryStore/070_USP_QueryStoreHints.sql
:r ../05_QueryStore/090_USP_IntelligentQueryProcessingAnalysis.sql
:r ../05_QueryStore/080_USP_QueryStoreAnalysis.sql
:r ../06_ExtendedEvents/010_USP_ExtendedEventsSessions.sql
:r ../06_ExtendedEvents/020_USP_ExtendedEventsReadEvents.sql
:r ../06_ExtendedEvents/030_USP_ExtendedEventsDeadlocks.sql
:r ../06_ExtendedEvents/040_USP_ExtendedEventsBlockedProcesses.sql
:r ../06_ExtendedEvents/050_USP_ExtendedEventsTargetRuntime.sql
:r ../06_ExtendedEvents/060_USP_ExtendedEventsAnalysis.sql
:r ../07_Infrastructure/010_USP_AgentStatus.sql
:r ../07_Infrastructure/020_USP_AgentJobs.sql
:r ../07_Infrastructure/030_USP_ResourceGovernorAnalysis.sql
:r ../07_Infrastructure/040_USP_AvailabilityGroups.sql
:r ../07_Infrastructure/050_USP_BackupRecovery.sql
:r ../07_Infrastructure/060_USP_LogShippingStatus.sql
:r ../07_Infrastructure/070_USP_ReplicationStatus.sql
:r ../07_Infrastructure/080_USP_DataCaptureStatus.sql
:r ../07_Infrastructure/100_USP_BackupChainAnalysis.sql
:r ../07_Infrastructure/110_USP_AvailabilityDeepAnalysis.sql
:r ../07_Infrastructure/120_USP_AgentMonitoringAnalysis.sql
:r ../07_Infrastructure/130_USP_MaintenanceOperations.sql
:r ../07_Infrastructure/140_USP_ErrorLogAnalysis.sql
:r ../07_Infrastructure/090_USP_InfrastructureAnalysis.sql
:r ../08_ServerHealth/010_USP_ServerCpuTopology.sql
:r ../08_ServerHealth/020_USP_ServerNuma.sql
:r ../08_ServerHealth/030_USP_ServerMemory.sql
:r ../08_ServerHealth/040_USP_TempDBConfiguration.sql
:r ../08_ServerHealth/050_USP_ServerConfiguration.sql
:r ../08_ServerHealth/060_USP_TraceFlags.sql
:r ../08_ServerHealth/070_USP_StartupParameters.sql
:r ../08_ServerHealth/080_USP_OSInformation.sql
:r ../08_ServerHealth/090_USP_ServerSecurityConfiguration.sql
:r ../08_ServerHealth/110_USP_DatabaseIntegrityAnalysis.sql
:r ../08_ServerHealth/120_USP_DatabaseCapacityAnalysis.sql
:r ../08_ServerHealth/130_USP_PerformanceCounters.sql
:r ../08_ServerHealth/140_USP_CriticalEngineEvents.sql
:r ../08_ServerHealth/150_USP_InternalContentionAnalysis.sql
:r ../08_ServerHealth/160_USP_BufferPoolAnalysis.sql
:r ../08_ServerHealth/170_USP_DiagnosticFindings.sql
:r ../08_ServerHealth/180_USP_WorkerPressureAnalysis.sql
:r ../08_ServerHealth/190_USP_DatabaseConfigurationAnalysis.sql
:r ../08_ServerHealth/100_USP_ServerHealthAnalysis.sql
:r ../09_VersionAdaptive/005_Deprecated_Object_Cleanup.sql
:r ../09_VersionAdaptive/010_USP_ServerFeatureCapabilities.sql
:r ../09_VersionAdaptive/011_SqlServerBuildCatalog.sql
:r ../09_VersionAdaptive/012_SqlServerLifecycleCatalog.sql
:r ../09_VersionAdaptive/015_USP_ServerVersionInformation.sql
:r ../09_VersionAdaptive/020_USP_SpecialFeatureInventory.sql
:r ../09_VersionAdaptive/030_USP_InMemoryOltpAnalysis.sql
:r ../09_VersionAdaptive/040_USP_TemporalAnalysis.sql
:r ../09_VersionAdaptive/050_USP_ServiceBrokerAnalysis.sql
:r ../09_VersionAdaptive/060_USP_FullTextAnalysis.sql
:r ../09_VersionAdaptive/070_USP_DataCaptureDeepAnalysis.sql
:r ../09_VersionAdaptive/080_USP_EncryptionAnalysis.sql
:r ../09_VersionAdaptive/090_USP_ExternalRuntimeAnalysis.sql
:r ../09_VersionAdaptive/100_USP_ClrAnalysis.sql
:r ../09_VersionAdaptive/500_USP_FrameworkUsageFromQueryStore.sql
