USE [DeineDatenbank];
GO

/*
===============================================================================
Objekt       : monitor.VW_AnalysisCatalog
Version      : 1.3.0
Stand        : 2026-07-25
Typ          : View
Zweck        : Katalogisiert jede öffentliche Framework-Procedure nach
               Anwenderrolle, Themenbereich, Scope, Evidenzart, Kostenprofil,
               Voraussetzung, Paketgrenze und sicherem Einstieg.
Semantik     : Genau eine Zeile je öffentlicher Procedure aus dem
               Objektinventar. Eine Procedure besitzt genau eine primäre
               Navigationsrolle; Mehrfachzuordnungen erfolgen über Suchbegriffe
               und Relationen, nicht über zusätzliche Katalogzeilen.
Kosten       : CostRangeCode beschreibt die dokumentierte Spannweite.
               RepresentativeAnalysisClass verweist, sofern vorhanden, auf
               monitor.VW_AnalyseClassCatalog und ersetzt nicht die
               pfadabhängigen Gates der Ziel-Procedure.
Eigenlast    : Konstante Frameworkmetadaten; keine DMVs, Benutzerkataloge oder
               produktiven Datenzugriffe.
===============================================================================
*/
CREATE OR ALTER VIEW [monitor].[VW_AnalysisCatalog]
AS
    SELECT
          CONVERT(sysname, [v].[ProcedureName]) AS [ProcedureName]
        , CONVERT(nvarchar(160), [v].[DisplayName]) AS [DisplayName]
        , CONVERT(varchar(40), [v].[PrimaryAreaCode]) AS [PrimaryAreaCode]
        , CONVERT(nvarchar(160), [v].[PrimaryAreaName]) AS [PrimaryAreaName]
        , CONVERT(varchar(24), [v].[NavigationRole]) AS [NavigationRole]
        , CONVERT(varchar(40), [v].[ScopeCode]) AS [ScopeCode]
        , CONVERT(varchar(40), [v].[EvidenceType]) AS [EvidenceType]
        , CONVERT(varchar(32), [v].[CostRangeCode]) AS [CostRangeCode]
        , CONVERT(varchar(64), [v].[RepresentativeAnalysisClass]) AS [RepresentativeAnalysisClass]
        , CONVERT(bit, [v].[RequiresKnownTarget]) AS [RequiresKnownTarget]
        , CONVERT(bit, [v].[RequiresHighImpactForSafeStart]) AS [RequiresHighImpactForSafeStart]
        , CONVERT(bit, [v].[HighImpactPathAvailable]) AS [HighImpactPathAvailable]
        , CONVERT(varchar(32), [v].[PackageCode]) AS [PackageCode]
        , CONVERT(smallint, [v].[DefaultRank]) AS [DefaultRank]
        , CONVERT(nvarchar(1000), [v].[Purpose]) AS [Purpose]
        , CONVERT(nvarchar(1000), [v].[PrerequisiteSummary]) AS [PrerequisiteSummary]
        , CONVERT(nvarchar(2000), [v].[SafeCall]) AS [SafeCall]
        , CONVERT(nvarchar(400), [v].[DocumentationPath]) AS [DocumentationPath]
        , CONVERT(nvarchar(400), [v].[RunbookPath]) AS [RunbookPath]
    FROM
    (
        VALUES
          (N'USP_AnalysisNavigator',N'Analyseweg finden','NAVIGATION',N'Einstieg und Orientierung','ENTRY','FRAMEWORK','FRAMEWORK_METADATA','LOW',NULL,0,0,0,'CORE',NULL,N'Findet passende Framework-Procedures nach Symptom, Ziel, Scope oder Fachbegriff, ohne eine Diagnose auszuführen.',N'Keine fachliche Voraussetzung; der Katalog liest ausschließlich statische Frameworkmetadaten.',N'EXEC [monitor].[USP_AnalysisNavigator];',N'Documentation/Analysis_Guides/Procedures/USP_AnalysisNavigator.md',NULL)
        , (N'USP_CheckAnalyseAccess',N'Analysefreigaben prüfen','FRAMEWORK',N'Framework und Zugriff','SETUP','FRAMEWORK','FRAMEWORK_METADATA','LOW',NULL,0,0,0,'CORE',NULL,N'Zeigt die interne Gruppen- und Analyseklassenfreigabe des aktuellen Sicherheitskontexts.',N'Nur für Ressourcenfreigaben; die Ausgabe ersetzt keine SQL-Server-Berechtigungsprüfung.',N'EXEC [monitor].[USP_CheckAnalyseAccess] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CheckAnalyseAccess.md',NULL)
        , (N'USP_CheckFrameworkCapabilities',N'Framework-Capabilities prüfen','FRAMEWORK',N'Framework und Zugriff','SETUP','FRAMEWORK','FRAMEWORK_METADATA','LOW_MEDIUM',NULL,0,0,0,'CORE',NULL,N'Prüft Version, Policy, Berechtigung, Abfragbarkeit und Featurestatus für Diagnosepfade.',N'Sichtbarkeit und Rechte bestimmen die Vollständigkeit; die Procedure vergibt keine Rechte.',N'EXEC [monitor].[USP_CheckFrameworkCapabilities] @NurNichtVerfuegbar = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CheckFrameworkCapabilities.md',NULL)
        , (N'USP_PrepareDatabaseCandidates',N'Datenbankauswahl vorbereiten','FRAMEWORK',N'Framework und Zugriff','SUPPORT','FRAMEWORK','FRAMEWORK_METADATA','LOW',NULL,1,0,0,'CORE',NULL,N'Befüllt eine vom Aufrufer bereitgestellte temporäre Kandidatenliste nach dem zentralen Datenbankvertrag.',N'Interner Aufrufvertrag für Framework-Procedures; kein eigenständiger Diagnoseeinstieg.',N'EXEC [monitor].[USP_AnalysisNavigator] @Suchbegriff = N''USP_PrepareDatabaseCandidates'';',N'Documentation/Analysis_Guides/Procedures/USP_PrepareDatabaseCandidates.md',NULL)
        , (N'USP_PrepareNameFilters',N'Namensfilter vorbereiten','FRAMEWORK',N'Framework und Zugriff','SUPPORT','FRAMEWORK','FRAMEWORK_METADATA','LOW',NULL,1,0,0,'CORE',NULL,N'Validiert und zerlegt case-sensitive, bracket-aware Namensfilter für aufrufende Procedures.',N'Interner Aufrufvertrag; der Aufrufer muss die vorgesehenen lokalen Zieltabellen bereitstellen.',N'EXEC [monitor].[USP_AnalysisNavigator] @Suchbegriff = N''USP_PrepareNameFilters'';',N'Documentation/Analysis_Guides/Procedures/USP_PrepareNameFilters.md',NULL)

        , (N'USP_CurrentSessions',N'Aktuelle Sessions','LIVE',N'Akute Störung und laufende Requests','FOLLOW_UP','SESSION_REQUEST','LIVE_SNAPSHOT','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',NULL,N'Inventarisiert Sessions, Verbindungskontext, kumulative Aktivität und offene Transaktionen.',N'Flüchtiger Snapshot; Session- und Clientangaben können sich unmittelbar ändern.',N'EXEC [monitor].[USP_CurrentSessions] @MitSqlText = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentSessions.md',NULL)
        , (N'USP_CurrentRequests',N'Aktive Requests und Ressourcen','LIVE',N'Akute Störung und laufende Requests','ENTRY','SESSION_REQUEST','LIVE_SNAPSHOT','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',3,N'Ordnet laufende Requests nach Laufzeit, CPU, I/O, Wait, Blocking, Memory Grant und Ausführungskontext ein.',N'Nur aktuell laufende Requests; für vergangene Regressionen Query Store oder Extended Events verwenden.',N'EXEC [monitor].[USP_CurrentRequests] @MaxZeilen = 50, @MitSqlText = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentRequests.md',N'Documentation/Analysis_Guides/Runbooks/02_High_CPU.md')
        , (N'USP_CurrentBlocking',N'Aktuelle Blocking-Ketten','LIVE',N'Akute Störung und laufende Requests','ENTRY','SESSION_REQUEST','LIVE_SNAPSHOT','LOW_HIGH_OPT_IN','STANDARD_CURRENT',0,0,1,'CORE',2,N'Rekonstruiert aktuelle Blockingkanten, Root Blocker und bei Bedarf technische Lockressourcen.',N'Blocking muss während des Snapshots noch bestehen; Lockdetails sind ein expliziter High-Impact-Pfad.',N'EXEC [monitor].[USP_CurrentBlocking] @MinWaitMs = 1000, @BlockingObjektTiefe = ''STANDARD'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentBlocking.md',N'Documentation/Analysis_Guides/Runbooks/01_User_Hangs_Blocking.md')
        , (N'USP_CurrentWaits',N'Aktuelle und gesampelte Waits','LIVE',N'Akute Störung und laufende Requests','FOLLOW_UP','SERVER','SAMPLE_DELTA','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',NULL,N'Zeigt aktuelle Tasks, kumulative Waits und optional ein kurzes Wait-Delta.',N'Waits sind Symptome; Scope, Dauer, Workload und Gegenprobe bestimmen die Interpretation.',N'EXEC [monitor].[USP_CurrentWaits] @SampleSeconds = 5, @MitSqlText = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentWaits.md',NULL)
        , (N'USP_CurrentTransactions',N'Offene und alte Transaktionen','LIVE',N'Akute Störung und laufende Requests','FOLLOW_UP','SESSION_REQUEST','LIVE_SNAPSHOT','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',NULL,N'Zeigt offene Transaktionen, Alter, Sessionzustand, Logverbrauch und optionalen SQL-Kontext.',N'Eine lange Transaktion kann geplant sein; Blocking, Logwachstum und Anwendungskontext gegenprüfen.',N'EXEC [monitor].[USP_CurrentTransactions] @MinAlterSekunden = 60, @MitSqlText = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentTransactions.md',NULL)
        , (N'USP_CurrentMemoryGrants',N'Wartende und aktive Memory Grants','LIVE',N'Akute Störung und laufende Requests','ENTRY','SESSION_REQUEST','LIVE_SNAPSHOT','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',14,N'Zeigt angeforderte, gewährte und genutzte Query Execution Memory Grants.',N'Ein großer Grant ist ohne Warteschlange, Nutzung, Plan und Konkurrenz kein Fehlerbeweis.',N'EXEC [monitor].[USP_CurrentMemoryGrants] @NurWartende = 1, @MitSqlText = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentMemoryGrants.md',N'Documentation/Analysis_Guides/Runbooks/06_Memory_Grant_Queue.md')
        , (N'USP_CurrentTempDB',N'Aktueller TempDB-Verbrauch','LIVE',N'Akute Störung und laufende Requests','ENTRY','DATABASE','MIXED','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',7,N'Zeigt aktuelle TempDB-Belegung nach Session und Datei sowie ab SQL Server 2025 Limits, Nutzung, Peak und Verletzungszähler je Workload Group.',N'Session- und Workload-Group-Zähler sind nicht direkt identisch; Version Store und TempDB-Log liegen außerhalb der Governance.',N'EXEC [monitor].[USP_CurrentTempDB] @MitDateien = 1, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentTempDB.md',N'Documentation/Analysis_Guides/Runbooks/04_TempDB_Growth.md')
        , (N'USP_CurrentIO',N'Aktuelle Datei-I/O-Latenz','LIVE',N'Akute Störung und laufende Requests','ENTRY','MULTI_DATABASE','SAMPLE_DELTA','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',9,N'Bewertet Datei-I/O kumulativ oder als kurzes Delta-Sample und kann Pending I/O ergänzen.',N'Kumulative Durchschnitte und aktuelles Sample getrennt lesen; Storage-Kausalität extern bestätigen.',N'EXEC [monitor].[USP_CurrentIO] @SampleSeconds = 5, @PendingIoEinbeziehen = 1, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentIO.md',N'Documentation/Analysis_Guides/Runbooks/07_IO_Latency.md')
        , (N'USP_CurrentLog',N'Aktuelle Transaktionslog-Auslastung','LIVE',N'Akute Störung und laufende Requests','ENTRY','MULTI_DATABASE','LIVE_SNAPSHOT','LOW_HIGH_OPT_IN','STANDARD_CURRENT',0,0,1,'CORE',8,N'Zeigt Logauslastung, Wiederverwendungswartegrund, VLF- und optional PVS-Kontext.',N'Hohe Auslastung erst mit Wiederverwendungsgrund, Transaktionen, Backup- und HA-Kontext bewerten.',N'EXEC [monitor].[USP_CurrentLog] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentLog.md',N'Documentation/Analysis_Guides/Runbooks/05_Transaction_Log_Full.md')
        , (N'USP_CurrentOverview',N'Orchestrierter Live-Überblick','LIVE',N'Akute Störung und laufende Requests','ENTRY','SERVER','MIXED','LOW_MEDIUM','STANDARD_CURRENT',0,0,0,'CORE',1,N'Orchestriert mehrere leichte Live-Analysen für eine erste Triage des aktuellen Zustands.',N'Nicht atomare Momentaufnahmen; Childstatus vor Einzelwerten lesen und anschließend gezielt vertiefen.',N'EXEC [monitor].[USP_CurrentOverview] @MitSqlText = 0, @SampleSeconds = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CurrentOverview.md',N'Documentation/Analysis_Guides/Runbooks/01_User_Hangs_Blocking.md')

        , (N'USP_ObjectInventory',N'Objekt- und Indexinventar','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','CATALOG_CONFIGURATION','LOW_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',NULL,N'Liefert Objekt- und Indexinventar mit Größe, Zeilen, Partitionierung, Kompression, Definition und capability-adaptiven JSON-Index-/Pfadmetadaten.',N'Datenbank- oder Objektscope angeben; breite Kataloganalyse kann High-Impact werden. JSON-Index-Metadaten sind kein Healthbefund.',N'EXEC [monitor].[USP_ObjectInventory] @DatabaseNames = N''[ExampleDatabase]'', @SchemaNames = N''[ExampleSchema]'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ObjectInventory.md',NULL)
        , (N'USP_IndexUsage',N'Indexnutzung seit Reset','OBJECT',N'Objekte, Indizes und Statistiken','ENTRY','OBJECT','CUMULATIVE_DMV','LOW_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',NULL,N'Zeigt kumulative Read-/Write-Nutzung klassischer und optional In-Memory-Indizes.',N'Restart-, Datenbank- und Strukturresetgrenzen beachten; keine Nutzung ist kein automatischer Löschauftrag.',N'EXEC [monitor].[USP_IndexUsage] @DatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_IndexUsage.md',N'Documentation/Analysis_Guides/Runbooks/08_Unused_Index.md')
        , (N'USP_IndexOperationalStats',N'Indexoperationen, Locks und Latches','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','CUMULATIVE_DMV','LOW_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',NULL,N'Zeigt partitionsgenaue DML-, Allocation-, Lock-, Latch- und Zugriffsaktivität.',N'Gezielten Objektfilter verwenden; kumulative Zähler benötigen Reset- und Workloadkontext.',N'EXEC [monitor].[USP_IndexOperationalStats] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @NurMitAktivitaet = 1, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_IndexOperationalStats.md',NULL)
        , (N'USP_MissingIndexes',N'Fehlende-Index-Evidenz','OBJECT',N'Objekte, Indizes und Statistiken','FOLLOW_UP','OBJECT','CUMULATIVE_DMV','LOW_MEDIUM','MISSING_INDEX_CURRENT',1,0,0,'CORE',NULL,N'Priorisiert flüchtige Missing-Index-Evidenz und erzeugt unverbindliche Entwürfe.',N'Nur Optimizer-Evidenz seit Reset; Überlappung, Schreibkosten und reale Querypläne gegenprüfen.',N'EXEC [monitor].[USP_MissingIndexes] @DatabaseNames = N''[ExampleDatabase]'', @MinUserReads = 10, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_MissingIndexes.md',NULL)
        , (N'USP_Statistics',N'Statistikzustand, Änderungen und Replikatherkunft','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','CATALOG_CONFIGURATION','LOW_HIGH_OPT_IN','STATISTICS_TARGETED',1,0,1,'CORE',NULL,N'Inventarisiert Statistikdefinition, Sample, Änderungen, inkrementelle Details und auf SQL Server 2025 die Replica-Herkunft.',N'Objekt- oder Statistiksicht eingrenzen; Alter und Replica-Herkunft allein belegen weder ein Problem noch die Verwendung durch einen Plan.',N'EXEC [monitor].[USP_Statistics] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_Statistics.md',NULL)
        , (N'USP_StatisticsDistributionAnalysis',N'Statistikhistogramm und Verteilung','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','CATALOG_CONFIGURATION','HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Analysiert ausgewählte Histogramme auf Skew, dominante Schritte, Tail und Partitionsabweichungen.',N'Bekannten Objekt- oder Statistikscope verwenden; Histogrammwerte können sensible Schlüsselwerte enthalten.',N'EXEC [monitor].[USP_StatisticsDistributionAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleObject]'', @AnalyseModus = ''GEZIELT'', @MaxVerteilungsStatistiken = 25, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_StatisticsDistributionAnalysis.md',NULL)
        , (N'USP_Partitions',N'Partitionen, Grenzen und Kompression','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','CATALOG_CONFIGURATION','LOW_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',NULL,N'Zeigt partitionsgenaue Größe, Grenzen, Ablage und Kompression.',N'Breite Cross-Database-Katalogabfragen vermeiden; Partitionen sind ohne Workloadkontext kein Problembeweis.',N'EXEC [monitor].[USP_Partitions] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_Partitions.md',NULL)
        , (N'USP_Columnstore',N'Columnstore-Rowgroups und Speicher','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','CATALOG_CONFIGURATION','MEDIUM_HIGH_OPT_IN','COLUMNSTORE_CURRENT',1,0,1,'CORE',NULL,N'Analysiert Columnstore-Rowgroups und optional Segmente sowie Dictionaries.',N'Objektscope setzen; Segment-, Dictionary- und Physical-Stats-Pfade sind explizite Vertiefungen.',N'EXEC [monitor].[USP_Columnstore] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @MitPhysicalStats = 0, @MitSegmenten = 0, @MitDictionaries = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_Columnstore.md',NULL)
        , (N'USP_IndexPhysicalStats',N'Physische Indexstruktur','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','LIVE_SNAPSHOT','HIGH_OPT_IN','PHYSICAL_STATS_DEEP',1,1,1,'CORE',NULL,N'Misst physische Rowstore- und Heap-Strukturen wie Fragmentierung, Seitendichte, Ghosts und Forwarded Records.',N'Bekannten Objektfilter, LIMITED-Modus und ruhigen Betriebszeitpunkt verwenden.',N'EXEC [monitor].[USP_IndexPhysicalStats] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @AnalyseModus = ''GEZIELT'', @ScanMode = ''LIMITED'', @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_IndexPhysicalStats.md',NULL)
        , (N'USP_VectorIndexAnalysis',N'Vector-Index-Katalog und Wartung','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','OBJECT','MIXED','LOW_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',NULL,N'Korreliert sichtbare SQL-Server-2025-Vector-Indizes mit ihrem aktuellen Hintergrundwartungszustand.',N'SQL Server 2025 und ein bekannter Datenbank- oder Objektscope; ältere Versionen liefern einen expliziten Verfügbarkeitsstatus.',N'EXEC [monitor].[USP_VectorIndexAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @StalenessReviewPercent = 15, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_VectorIndexAnalysis.md',NULL)
        , (N'USP_ObjectAnalysis',N'Orchestrierte Objektanalyse','OBJECT',N'Objekte, Indizes und Statistiken','ENTRY','OBJECT','MIXED','LOW_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',6,N'Orchestriert Inventar einschließlich SQL-Server-2025-JSON-Indexmetadaten, Usage, Missing Indexes und optionale Tiefenmodule mit gemeinsamem Filtervertrag.',N'Für den sicheren Einstieg eine Datenbank und ein Objekt angeben; Tiefenmodule einzeln aktivieren.',N'EXEC [monitor].[USP_ObjectAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @FullObjectNames = N''[ExampleSchema].[ExampleTable]'', @MitObjectInventory = 1, @MitIndexUsage = 0, @MitMissingIndexes = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ObjectAnalysis.md',NULL)
        , (N'USP_SchemaDesignAnalysis',N'Schema- und Constraint-Review','OBJECT',N'Objekte, Indizes und Statistiken','TARGETED','MULTI_DATABASE','CATALOG_CONFIGURATION','MEDIUM_HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Erzeugt normalisierte Findings zu Constraints, Foreign Keys, Indizes und Identity-Risiken.',N'Datenbankscope und High-Impact-Bestätigung erforderlich; Findings sind Reviewaufträge, keine DDL-Anweisungen.',N'EXEC [monitor].[USP_SchemaDesignAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_SchemaDesignAnalysis.md',NULL)

        , (N'USP_QueryStats',N'Plan-Cache-Ressourcenverbrauch','PLAN',N'Langsame Query und Ausführungsplan','ENTRY','QUERY','CUMULATIVE_DMV','LOW_HIGH_OPT_IN','PLAN_CACHE_CURRENT',0,0,1,'CORE',NULL,N'Rangiert gecachte Statements nach CPU, Dauer, I/O, Ausführungen, Grants, Spills oder Zeilen.',N'Plan Cache ist flüchtig und kumulativ je Cacheeintrag; historische Aussagen mit Query Store bestätigen.',N'EXEC [monitor].[USP_QueryStats] @Sortierung = ''CPU_TOTAL'', @MaxZeilen = 50, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStats.md',N'Documentation/Analysis_Guides/Runbooks/02_High_CPU.md')
        , (N'USP_QueryHashAnalysis',N'Query-Hash- und Planvarianten','PLAN',N'Langsame Query und Ausführungsplan','FOLLOW_UP','QUERY','CUMULATIVE_DMV','LOW_HIGH_OPT_IN','PLAN_CACHE_DEEP',1,1,1,'CORE',NULL,N'Aggregiert Cachezeilen je Query Hash und zeigt Planvarianten, Handles und Ressourcen.',N'Query Hash oder enger Top-Scope empfohlen; breite Cacheanalyse benötigt High-Impact-Bestätigung.',N'EXEC [monitor].[USP_QueryHashAnalysis] @AnalyseModus = ''TOP'', @MaxZeilen = 100, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryHashAnalysis.md',NULL)
        , (N'USP_PlanCacheHealth',N'Plan-Cache-Gesundheit','PLAN',N'Langsame Query und Ausführungsplan','FOLLOW_UP','SERVER','LIVE_SNAPSHOT','LOW_HIGH_OPT_IN','PLAN_CACHE_CURRENT',0,0,1,'CORE',NULL,N'Bewertet Cachegröße, Cachekategorien und Single-Use-Anteil.',N'SUMMARY ist der sichere Einstieg; ein hoher Single-Use-Anteil benötigt Konfigurations- und Workloadkontext.',N'EXEC [monitor].[USP_PlanCacheHealth] @AnalyseModus = ''SUMMARY'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_PlanCacheHealth.md',NULL)
        , (N'USP_PlanDetails',N'Gezielte Plandetails','PLAN',N'Langsame Query und Ausführungsplan','TARGETED','PLAN_XML','LIVE_SNAPSHOT','MEDIUM_HIGH_OPT_IN','PLAN_CACHE_DEEP',1,1,1,'CORE',NULL,N'Löst gezielte Plankandidaten auf und liefert Attribute sowie Compile-, Last-Actual- oder Live-Plan.',N'Planhandle, Session oder Query-Identität vorgeben; Live- und Last-Actual-Plan sind nicht immer verfügbar.',N'EXEC [monitor].[USP_PlanDetails] @SessionIds = N''57'', @MitCompilePlan = 1, @MitLastActualPlan = 0, @MitLivePlan = 0, @MaxAnalyseobjekte = 5, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_PlanDetails.md',NULL)
        , (N'USP_ShowplanAnalysis',N'Gezielte Showplan-Analyse','PLAN',N'Langsame Query und Ausführungsplan','TARGETED','PLAN_XML','LIVE_SNAPSHOT','MEDIUM_HIGH_OPT_IN','SHOWPLAN_TARGETED',1,0,1,'CORE',NULL,N'Extrahiert Statements, Warnungen, Objekte, Statistiken, Operatoren, Kardinalität, Memory und Parameter aus Plan-XML.',N'Query Hash, Planhandle oder enger Kandidatenscope erforderlich; XML-Tiefe kann High-Impact werden.',N'EXEC [monitor].[USP_ShowplanAnalysis] @QueryHash = 0x0102030405060708, @AnalyseModus = ''GEZIELT'', @MaxAnalyseobjekte = 5, @MaxDurationSeconds = 10, @MaxZeilen = 1000, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ShowplanAnalysis.md',NULL)
        , (N'USP_PlanCacheAnalysis',N'Orchestrierte Plan-Cache-Analyse','PLAN',N'Langsame Query und Ausführungsplan','ENTRY','QUERY','MIXED','LOW_HIGH_OPT_IN','PLAN_CACHE_DEEP',0,1,1,'CORE',NULL,N'Orchestriert Query Stats, Query Hash, Cache Health und optional Showplan.',N'Der gezeigte vollständige Einstieg benötigt High-Impact-Bestätigung; für leichte Triage zuerst USP_QueryStats verwenden.',N'EXEC [monitor].[USP_PlanCacheAnalysis] @MitQueryStats = 1, @MaxZeilen = 100, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_PlanCacheAnalysis.md',NULL)
        , (N'USP_CreateExecutionEvidenceJson',N'Ausführungsevidenz normalisieren','PLAN',N'Langsame Query und Ausführungsplan','TARGETED','PLAN_XML','STATIC_INPUT','LOW_HIGH_OPT_IN','CATALOG_DEEP',1,0,1,'CORE_PLAN_STANDALONE',NULL,N'Normalisiert übergebene Plan-, STATISTICS-IO-, STATISTICS-TIME- und Statistik-/Histogrammevidenz in JSON.',N'Benötigt bereits erfasste synthetische oder autorisiert erhobene Evidenz; übermittelt oder speichert sie nicht extern.',N'EXEC [monitor].[USP_CreateExecutionEvidenceJson] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_CreateExecutionEvidenceJson.md',NULL)
        , (N'USP_ExecutionPlanAnalysis',N'Eigenständige Execution-Plan-Analyse','PLAN',N'Langsame Query und Ausführungsplan','ENTRY','PLAN_XML','STATIC_INPUT','MEDIUM_HIGH_OPT_IN','SHOWPLAN_XML_DEEP',1,0,1,'CORE_PLAN_STANDALONE',5,N'Analysiert genau ein übergebenes oder gezielt beschafftes Showplan-XML statement- und operatorbezogen.',N'Plan-XML oder eindeutig begrenzte Planquelle erforderlich; tatsächliche Laufzeitwerte existieren nur in Actual Plans.',N'EXEC [monitor].[USP_ExecutionPlanAnalysis] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_ExecutionPlanAnalysis.md',NULL)

        , (N'USP_QueryStoreStatus',N'Query-Store-Status','QUERY_STORE',N'Query Store und Regressionen','FOLLOW_UP','DATABASE','CATALOG_CONFIGURATION','LOW','QUERY_STORE_CURRENT',1,0,0,'CORE',NULL,N'Zeigt Zustand, Capture, Retention, Speicher, Cleanup und Wait-Capture je Datenbank.',N'Query Store muss in der gewählten Datenbank sichtbar sein; Status zuerst vor historischen Auswertungen prüfen.',N'EXEC [monitor].[USP_QueryStoreStatus] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreStatus.md',NULL)
        , (N'USP_QueryStoreRuntimeStats',N'Historische Query-Laufzeitwerte','QUERY_STORE',N'Query Store und Regressionen','TARGETED','QUERY','PERSISTED_HISTORY','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',NULL,N'Aggregiert historische Laufzeit- und Ressourcenwerte je Query und Plan über Query-Store-Intervalle.',N'Datenbank und Zeitfenster angeben; Capture, Retention und Aggregation begrenzen die Aussage.',N'EXEC [monitor].[USP_QueryStoreRuntimeStats] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreRuntimeStats.md',NULL)
        , (N'USP_QueryStoreWaitStats',N'Historische Query-Store-Waits','QUERY_STORE',N'Query Store und Regressionen','TARGETED','QUERY','PERSISTED_HISTORY','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',NULL,N'Aggregiert historische Query-Store-Waitkategorien je Query und Plan.',N'Wait-Capture muss verfügbar sein; Kategorieaggregate ersetzen keine Task- oder Request-Detailanalyse.',N'EXEC [monitor].[USP_QueryStoreWaitStats] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreWaitStats.md',NULL)
        , (N'USP_QueryStorePlanChanges',N'Query-Store-Planwechsel','QUERY_STORE',N'Query Store und Regressionen','TARGETED','QUERY','PERSISTED_HISTORY','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',NULL,N'Findet Queries mit mehreren Query-Store-Plänen und zeigt Compile- sowie Nutzungsmetadaten.',N'Datenbank und möglichst Queryscope festlegen; mehrere Pläne sind allein kein Regressionsbeweis.',N'EXEC [monitor].[USP_QueryStorePlanChanges] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @NurMehrerePlaene = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStorePlanChanges.md',NULL)
        , (N'USP_QueryStoreRegressions',N'Query-Regression zwischen Zeitfenstern','QUERY_STORE',N'Query Store und Regressionen','ENTRY','QUERY','PERSISTED_HISTORY','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',4,N'Vergleicht zwei Zeitfenster nach Dauer, CPU, Reads, Writes oder Ausführungen.',N'Query Store, belastbare Vergleichsfenster und genügend Ausführungen erforderlich.',N'EXEC [monitor].[USP_QueryStoreRegressions] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @MinAusfuehrungenJeFenster = 10, @MinRegressionProzent = 20, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreRegressions.md',N'Documentation/Analysis_Guides/Runbooks/03_Query_Regression.md')
        , (N'USP_QueryStoreForcedPlans',N'Forced Plans und Fehler','QUERY_STORE',N'Query Store und Regressionen','FOLLOW_UP','QUERY','PERSISTED_HISTORY','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',NULL,N'Inventarisiert erzwungene Pläne und Plan-Forcing-Fehler.',N'Nur lesend; Forcing-Zustand ist ohne Regressions-, Plan- und Betriebskontext nicht zu ändern.',N'EXEC [monitor].[USP_QueryStoreForcedPlans] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @NurMitFehler = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreForcedPlans.md',NULL)
        , (N'USP_QueryStoreHints',N'Query Store Hints','QUERY_STORE',N'Query Store und Regressionen','FOLLOW_UP','QUERY','CATALOG_CONFIGURATION','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',NULL,N'Inventarisiert Query Store Hints, Herkunft und Anwendungsfehler.',N'Nur lesend; Hint-Wirkung muss an konkreter Query-, Plan- und Runtime-Evidenz geprüft werden.',N'EXEC [monitor].[USP_QueryStoreHints] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreHints.md',NULL)
        , (N'USP_QueryStoreAnalysis',N'Orchestrierte Query-Store-Analyse','QUERY_STORE',N'Query Store und Regressionen','ENTRY','QUERY','MIXED','LOW_HIGH_OPT_IN','QUERY_STORE_CURRENT',1,0,1,'CORE',NULL,N'Orchestriert Status, Runtime, Waits, Planwechsel, Regressionen, Forced Plans, Hints und IQP.',N'Datenbank und Zeitfenster festlegen; aktivierte Childpfade bestimmen Kosten und Vollständigkeit.',N'EXEC [monitor].[USP_QueryStoreAnalysis] @QueryStoreDatabaseNames = N''[ExampleDatabase]'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_QueryStoreAnalysis.md',NULL)
        , (N'USP_IntelligentQueryProcessingAnalysis',N'Intelligent Query Processing','QUERY_STORE',N'Query Store und Regressionen','FOLLOW_UP','MULTI_DATABASE','MIXED','LOW_HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Zeigt Featureeignung, datenbankbezogene Konfiguration und aggregierte Feedbacksignale.',N'Datenbankscope und High-Impact-Bestätigung erforderlich; Eignung ist kein Beweis aktiver Nutzung.',N'EXEC [monitor].[USP_IntelligentQueryProcessingAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_IntelligentQueryProcessingAnalysis.md',NULL)

        , (N'USP_ExtendedEventsSessions',N'Extended-Events-Inventar','EXTENDED_EVENTS',N'Extended Events und Forensik','FOLLOW_UP','EVENT_SESSION','CATALOG_CONFIGURATION','LOW_MEDIUM','EXTENDED_EVENTS_CURRENT',0,0,0,'CORE',NULL,N'Inventarisiert XE-Sessions, Laufzeitstatus, Events, Actions, Targets und Felder.',N'Nur vorhandene und sichtbare Sessions werden erfasst; keine Targetdaten werden im sicheren Einstieg gelesen.',N'EXEC [monitor].[USP_ExtendedEventsSessions] @MitEvents = 1, @MitActions = 0, @MitTargets = 1, @MitFeldern = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ExtendedEventsSessions.md',NULL)
        , (N'USP_ExtendedEventsReadEvents',N'Extended-Events-Ereignisse lesen','EXTENDED_EVENTS',N'Extended Events und Forensik','TARGETED','EVENT_HISTORY','EVENT_HISTORY','HIGH_OPT_IN','EXTENDED_EVENTS_FORENSICS_DEEP',1,1,1,'CORE',NULL,N'Liest erhaltene Einzelereignisse aus Event Files oder bewusst aus einem Ring Buffer.',N'Konkrete Session, Datei oder Targetquelle und High-Impact-Bestätigung erforderlich; Retention begrenzt Historie.',N'EXEC [monitor].[USP_ExtendedEventsReadEvents] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_ExtendedEventsReadEvents.md',NULL)
        , (N'USP_ExtendedEventsDeadlocks',N'Historische Deadlocks','EXTENDED_EVENTS',N'Extended Events und Forensik','ENTRY','EVENT_HISTORY','EVENT_HISTORY','MEDIUM_HIGH_OPT_IN','EXTENDED_EVENTS_FORENSICS_DEEP',0,1,1,'CORE',15,N'Zerlegt erhaltene Deadlockgraphs in Summary, Victims, Processes und Resources.',N'Deadlockquelle muss den Zeitraum noch enthalten; fehlende Ereignisse beweisen keine Deadlockfreiheit.',N'EXEC [monitor].[USP_ExtendedEventsDeadlocks] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_ExtendedEventsDeadlocks.md',NULL)
        , (N'USP_ExtendedEventsBlockedProcesses',N'Historische Blocked-Process-Reports','EXTENDED_EVENTS',N'Extended Events und Forensik','ENTRY','EVENT_HISTORY','EVENT_HISTORY','MEDIUM_HIGH_OPT_IN','EXTENDED_EVENTS_FORENSICS_DEEP',0,1,1,'CORE',NULL,N'Liest historische Blocked-Process-Reports und zerlegt blockierte sowie blockierende Prozesse.',N'Blocked Process Threshold und passende XE-Capture müssen im Ereigniszeitraum aktiv gewesen sein.',N'EXEC [monitor].[USP_ExtendedEventsBlockedProcesses] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_ExtendedEventsBlockedProcesses.md',NULL)
        , (N'USP_ExtendedEventsTargetRuntime',N'XE-Targetruntime und Verlustsignale','EXTENDED_EVENTS',N'Extended Events und Forensik','FOLLOW_UP','EVENT_SESSION','LIVE_SNAPSHOT','LOW_HIGH_OPT_IN','EXTENDED_EVENTS_FORENSICS_DEEP',0,1,1,'CORE',NULL,N'Zeigt Runtimezustand und optional Daten laufender XE-Targets.',N'Targetdaten und Flush können Nebenwirkungen oder hohe Transferkosten verursachen und bleiben opt-in.',N'EXEC [monitor].[USP_ExtendedEventsTargetRuntime] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_ExtendedEventsTargetRuntime.md',NULL)
        , (N'USP_ExtendedEventsAnalysis',N'Orchestrierte XE-Analyse','EXTENDED_EVENTS',N'Extended Events und Forensik','ENTRY','EVENT_SESSION','MIXED','LOW_HIGH_OPT_IN','EXTENDED_EVENTS_CURRENT',0,0,1,'CORE',NULL,N'Orchestriert Inventar, Targetruntime, generische Events, Deadlocks und Blocked Processes.',N'Sicherer Einstieg aktiviert nur Sessioninventar; Ereignis- und Targetdatenpfade einzeln freigeben.',N'EXEC [monitor].[USP_ExtendedEventsAnalysis] @MitSessionInventar = 1, @MitTargetRuntime = 0, @MitEvents = 0, @MitDeadlocks = 0, @MitBlockedProcesses = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ExtendedEventsAnalysis.md',NULL)

        , (N'USP_AgentStatus',N'SQL-Server-Agent-Status','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','FOLLOW_UP','INFRASTRUCTURE','LIVE_SNAPSHOT','LOW','SQL_AGENT_CURRENT',0,0,0,'CORE',NULL,N'Zeigt Plattformunterstützung, Dienststatus und SQL-Agent-Basisinventar.',N'SQL Server Agent ist nicht auf jeder Plattform oder Dienstvariante verfügbar.',N'EXEC [monitor].[USP_AgentStatus] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_AgentStatus.md',NULL)
        , (N'USP_AgentJobs',N'Jobs, Laufzeit und Fehler','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','INFRASTRUCTURE','PERSISTED_HISTORY','LOW_MEDIUM','SQL_AGENT_CURRENT',0,0,0,'CORE',NULL,N'Zeigt Jobs, Schritte, Laufstatus, Historie, Dauer und Fehler.',N'msdb-Retention und Berechtigungen bestimmen die sichtbare Historie; Jobinhalte können sensibel sein.',N'EXEC [monitor].[USP_AgentJobs] @NurProblematisch = 1, @LongRunningMinutes = 60, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_AgentJobs.md',NULL)
        , (N'USP_ResourceGovernorAnalysis',N'Resource-Governor-Zustand','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','FOLLOW_UP','SERVER','MIXED','LOW_MEDIUM','RESOURCE_GOVERNOR_CURRENT',0,0,0,'CORE',NULL,N'Zeigt Pools, Workload Groups, Limits und Sessions sowie ab SQL Server 2025 die TempDB-Governance mit Wirksamkeit und Resetgrenze.',N'Konfiguriertes und wirksames Limit trennen; Verletzungen beweisen weder Ursache noch aktuelle Überlastung.',N'EXEC [monitor].[USP_ResourceGovernorAnalysis] @MitSessions = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ResourceGovernorAnalysis.md',NULL)
        , (N'USP_AvailabilityGroups',N'Availability-Groups-Status','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','INFRASTRUCTURE','LIVE_SNAPSHOT','LOW_MEDIUM','HA_DR_CURRENT',0,0,0,'CORE',NULL,N'Zeigt Availability-Group-, Replica-, Datenbank- und Routingzustand.',N'Verteilter, nicht atomarer Snapshot; Cluster-, Netzwerk- und Gegenstellenkontext kann fehlen.',N'EXEC [monitor].[USP_AvailabilityGroups] @MitRouting = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_AvailabilityGroups.md',N'Documentation/Analysis_Guides/Runbooks/10_Availability_Group_Lag.md')
        , (N'USP_BackupRecovery',N'Backupalter und Recovery','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','MULTI_DATABASE','PERSISTED_HISTORY','LOW_MEDIUM','HA_DR_CURRENT',0,0,0,'CORE',NULL,N'Bewertet Backupalter, Recovery Model, Logbackupbedarf und Restorehistorie.',N'msdb-Historie ist kein Beweis der Wiederherstellbarkeit; echten Restore-Test separat nachweisen.',N'EXEC [monitor].[USP_BackupRecovery] @DatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_BackupRecovery.md',N'Documentation/Analysis_Guides/Runbooks/09_Backup_Integrity_Risk.md')
        , (N'USP_LogShippingStatus',N'Log-Shipping-Pipeline','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','INFRASTRUCTURE','PERSISTED_HISTORY','LOW','HA_DR_CURRENT',0,0,0,'CORE',NULL,N'Zeigt Backup-, Copy- und Restorefortschritt von Log Shipping.',N'msdb- und Monitorserver-Sicht können partiell sein; Zeitversatz und Jobstatus gegenprüfen.',N'EXEC [monitor].[USP_LogShippingStatus] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_LogShippingStatus.md',NULL)
        , (N'USP_ReplicationStatus',N'Replikationsstatus und Backlog','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','INFRASTRUCTURE','PERSISTED_HISTORY','MEDIUM_HIGH_OPT_IN','HA_DR_CURRENT',0,0,1,'CORE',NULL,N'Zeigt Publikationen, Subscriptions, Agents, Latenz, Backlog und Fehler.',N'Distributiondetails sind opt-in; entfernte Topologie kann außerhalb der lokalen Evidenz liegen.',N'EXEC [monitor].[USP_ReplicationStatus] @MitDistributionDetails = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ReplicationStatus.md',NULL)
        , (N'USP_DataCaptureStatus',N'CDC- und Change-Tracking-Status','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','MULTI_DATABASE','CATALOG_CONFIGURATION','LOW_MEDIUM','HA_DR_CURRENT',0,0,0,'CORE',NULL,N'Zeigt CDC-, Change-Tracking- und weitere Data-Capture-Zustände.',N'Featurestatus und Jobs sind keine Consumer-Wasserstände; Verlusturteile benötigen zusätzliche Evidenz.',N'EXEC [monitor].[USP_DataCaptureStatus] @DatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_DataCaptureStatus.md',NULL)
        , (N'USP_InfrastructureAnalysis',N'Orchestrierter Infrastrukturüberblick','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','INFRASTRUCTURE','MIXED','LOW_HIGH_OPT_IN','HA_DR_CURRENT',0,0,1,'CORE',11,N'Orchestriert Agent, Resource Governor, HA, Backup, Log Shipping, Replikation und Data Capture.',N'Aktivierte Childmodule bestimmen Scope und Kosten; Modulstatus vor fachlichen Zeilen lesen.',N'EXEC [monitor].[USP_InfrastructureAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_InfrastructureAnalysis.md',NULL)
        , (N'USP_BackupChainAnalysis',N'Backupkette und Restoreevidenz','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','FOLLOW_UP','DATABASE','PERSISTED_HISTORY','LOW_MEDIUM','HA_DR_CURRENT',1,0,0,'CORE',NULL,N'Prüft Full-, Differential- und Logbeziehungen, LSN-Folgen und optionale Restoreevidenz.',N'Datenbankscope und geeignetes Historienfenster erforderlich; Metadaten ersetzen keinen Restore.',N'EXEC [monitor].[USP_BackupChainAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @HistoryDays = 35, @MitRestoreEvidence = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_BackupChainAnalysis.md',N'Documentation/Analysis_Guides/Runbooks/09_Backup_Integrity_Risk.md')
        , (N'USP_AvailabilityDeepAnalysis',N'Availability-Lag und Queues','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','INFRASTRUCTURE','LIVE_SNAPSHOT','LOW_MEDIUM','HA_DR_CURRENT',0,0,0,'CORE',NULL,N'Vertieft Availability Groups mit Send- und Redo-Queues, Lag, Cluster- und Replica-Evidenz.',N'Verteilter Snapshot; Ursachen in Logerzeugung, Netzwerk, Storage und Replica getrennt prüfen.',N'EXEC [monitor].[USP_AvailabilityDeepAnalysis] @MitClusterNetzwerken = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_AvailabilityDeepAnalysis.md',N'Documentation/Analysis_Guides/Runbooks/10_Availability_Group_Lag.md')
        , (N'USP_AgentMonitoringAnalysis',N'Agent-, Alert- und Mailpfad','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','FOLLOW_UP','INFRASTRUCTURE','PERSISTED_HISTORY','LOW_MEDIUM','SQL_AGENT_CURRENT',0,0,0,'CORE',NULL,N'Verknüpft Jobprobleme mit Alerts, Operatoren und Database Mail.',N'msdb-Retention und Berechtigungen bestimmen die Vollständigkeit; keine Benachrichtigung wird versendet.',N'EXEC [monitor].[USP_AgentMonitoringAnalysis] @HistoryHours = 24, @MitJobStatus = 1, @MitDatabaseMail = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_AgentMonitoringAnalysis.md',NULL)
        , (N'USP_MaintenanceOperations',N'Laufende Wartungsoperationen','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','MULTI_DATABASE','MIXED','LOW_MEDIUM','HA_DR_CURRENT',0,0,0,'CORE',NULL,N'Korrelierte read-only Sicht auf resumierbare Indexoperationen, Wartungsrequests, ADR/PVS und explizit gewählte Jobs.',N'Ohne Jobfilter werden Jobkataloge nicht gelesen; die Procedure führt keine Resume-, Abort- oder Kill-Aktion aus.',N'EXEC [monitor].[USP_MaintenanceOperations] @DatabaseNames = N''[ExampleDatabase]'', @NurProblematisch = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_MaintenanceOperations.md',NULL)
        , (N'USP_ErrorLogAnalysis',N'SQL-Server-Errorlog analysieren','OPERATIONS',N'Backup, Agent, HA/DR und Betrieb','ENTRY','SERVER','EVENT_HISTORY','LOW_MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Verdichtet begrenzte SQL-Server- und optional SQL-Agent-Errorlogtreffer zu Kategorien.',N'Rotationsabhängige lokale Historie; Meldungsvolltext bleibt aus Datenschutz- und Transfergründen opt-in.',N'EXEC [monitor].[USP_ErrorLogAnalysis] @MaxArchivNummer = 0, @MeldungstextEinbeziehen = 0, @MaxQuellzeilen = 10000, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ErrorLogAnalysis.md',NULL)

        , (N'USP_ServerCpuTopology',N'CPU- und Scheduler-Topologie','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','LIVE_SNAPSHOT','LOW','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Zeigt CPU-, Socket-, Core-, Scheduler- und NUMA-Topologie.',N'Topologie ist Kontext; aktuellen CPU-Druck mit Requests, Runnable Queues und externen Countern prüfen.',N'EXEC [monitor].[USP_ServerCpuTopology] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerCpuTopology.md',NULL)
        , (N'USP_ServerNuma',N'NUMA- und Memory-Nodes','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','LIVE_SNAPSHOT','LOW','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Zeigt NUMA-Nodes, Schedulerverteilung und Memory-Node-Kontext.',N'Ungleichheit ist ohne Workload-, Affinitäts- und Hardwarekontext kein Fehlerbeweis.',N'EXEC [monitor].[USP_ServerNuma] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerNuma.md',NULL)
        , (N'USP_ServerMemory',N'Server- und SQL-Memory','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','SERVER','LIVE_SNAPSHOT','LOW_MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Verknüpft OS-, SQL-Prozess-, Target-/Total-Memory- und Clerk-Evidenz.',N'Snapshot und kumulative Werte gemeinsam lesen; niedriger freier Speicher ist allein kein Pressure-Beweis.',N'EXEC [monitor].[USP_ServerMemory] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerMemory.md',NULL)
        , (N'USP_TempDBConfiguration',N'TempDB-Konfiguration','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','CATALOG_CONFIGURATION','LOW','SERVER_CONFIGURATION_CURRENT',0,0,0,'CORE',NULL,N'Bewertet TempDB-Dateien, Größen, Wachstum, Gleichheit und Konfigurationsrisiken.',N'Konfiguration mit aktuellem Verbrauch, Autogrowth-Ereignissen und Storageeigenschaften korrelieren.',N'EXEC [monitor].[USP_TempDBConfiguration] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_TempDBConfiguration.md',N'Documentation/Analysis_Guides/Runbooks/04_TempDB_Growth.md')
        , (N'USP_ServerConfiguration',N'Serverkonfiguration','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','SERVER','CATALOG_CONFIGURATION','LOW','SERVER_CONFIGURATION_CURRENT',0,0,0,'CORE',NULL,N'Zeigt konfigurierte und aktive Serveroptionen mit Bewertungskontext.',N'Repositoryhinweise sind Prüfaufträge; Workload, Edition und Betriebsstandard bestimmen Sollwerte.',N'EXEC [monitor].[USP_ServerConfiguration] @NurKernparameter = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerConfiguration.md',NULL)
        , (N'USP_TraceFlags',N'Aktive Trace Flags','SERVER',N'CPU, Memory, Worker und Server Health','TARGETED','SERVER','CATALOG_CONFIGURATION','LOW','SERVER_CONFIGURATION_CURRENT',0,0,0,'CORE',NULL,N'Inventarisiert aktive globale und sessionbezogene Trace Flags.',N'Aktivität allein bewertet weder Notwendigkeit noch Wirkung; Version und Scope prüfen.',N'EXEC [monitor].[USP_TraceFlags] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_TraceFlags.md',NULL)
        , (N'USP_StartupParameters',N'SQL-Server-Startparameter','SERVER',N'CPU, Memory, Worker und Server Health','TARGETED','SERVER','CATALOG_CONFIGURATION','LOW','SERVER_CONFIGURATION_CURRENT',0,0,0,'CORE',NULL,N'Zeigt SQL-Server-Startparameter, Pfade und dauerhaft aktivierte Flags.',N'Pfade können betriebliche Details enthalten; Repositorybeispiele bleiben synthetisch.',N'EXEC [monitor].[USP_StartupParameters] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_StartupParameters.md',NULL)
        , (N'USP_OSInformation',N'Betriebssystem und Uptime','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','LIVE_SNAPSHOT','LOW','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Zeigt Betriebssystem, Virtualisierung, Speicher, Zeit, Uptime und Plattformgrenzen.',N'Plattformcontext ergänzt, ersetzt aber keine Host-, Hypervisor- oder Cloudmetriken.',N'EXEC [monitor].[USP_OSInformation] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_OSInformation.md',NULL)
        , (N'USP_ServerSecurityConfiguration',N'Sicherheitskonfiguration prüfen','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','SERVER','CATALOG_CONFIGURATION','LOW','SECURITY_CONFIGURATION_CURRENT',0,0,0,'CORE',NULL,N'Erzeugt Sicherheits-Reviewbefunde zu relevanten Serveroptionen.',N'Nur Konfigurationssicht; Berechtigungen, Identitäten und externe Sicherheitskontrollen separat prüfen.',N'EXEC [monitor].[USP_ServerSecurityConfiguration] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerSecurityConfiguration.md',NULL)
        , (N'USP_ServerHealthAnalysis',N'Orchestrierter Server-Health-Überblick','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','SERVER','MIXED','LOW_HIGH_OPT_IN','SERVER_HEALTH_CURRENT',0,0,1,'CORE',10,N'Orchestriert Topologie, Memory, TempDB, Konfiguration, OS und optionale Spezialmodule.',N'Nicht atomare Child-Snapshots; aktivierte Tiefenmodule bestimmen Kosten und Aussagegrenzen.',N'EXEC [monitor].[USP_ServerHealthAnalysis] @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerHealthAnalysis.md',NULL)
        , (N'USP_DatabaseIntegrityAnalysis',N'Datenbankintegritäts-Evidenz','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','MULTI_DATABASE','PERSISTED_HISTORY','LOW_MEDIUM','HA_DR_CURRENT',0,0,0,'CORE',13,N'Korrelierte Integritätsevidenz aus Datenbankstatus, CHECKDB-Historie, suspect pages, Backups und HADR.',N'Führt kein DBCC aus; fehlende negative Evidenz ist kein Integritätsbeweis.',N'EXEC [monitor].[USP_DatabaseIntegrityAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @MitPageDetails = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_DatabaseIntegrityAnalysis.md',N'Documentation/Analysis_Guides/Runbooks/09_Backup_Integrity_Risk.md')
        , (N'USP_DatabaseCapacityAnalysis',N'Datenbank- und Volumekapazität','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','MULTI_DATABASE','LIVE_SNAPSHOT','LOW_MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',16,N'Bewertet Dateien, Volumes, freien Platz, Autogrowth, MaxSize und Wachstumsspielraum.',N'Punktueller Kapazitätssnapshot ohne Wachstumsprognose; Verlauf aus Monitoring oder Snapshotpaket ergänzen.',N'EXEC [monitor].[USP_DatabaseCapacityAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_DatabaseCapacityAnalysis.md',NULL)
        , (N'USP_PerformanceCounters',N'Typisierte Performance Counter','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','SAMPLE_DELTA','LOW_MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Liest typisierte SQL-Server-Performance-Counter und berechnet bei Bedarf Sample- und Delta-Werte.',N'Countertyp, Basiswert, Reset und Sampleintervall vor Schwelleninterpretation prüfen.',N'EXEC [monitor].[USP_PerformanceCounters] @SampleSeconds = 5, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_PerformanceCounters.md',NULL)
        , (N'USP_CriticalEngineEvents',N'Kritische Engine-Ereignisse','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','EVENT_HISTORY','EVENT_HISTORY','MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Liest schwere Engine-Ereignisse aus system_health und optionalen Diagnosequellen.',N'Nur erhaltene Ereignisse sind sichtbar; Event-XML und weitere Quellen bleiben opt-in.',N'EXEC [monitor].[USP_CriticalEngineEvents] @MitEventXml = 0, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_CriticalEngineEvents.md',NULL)
        , (N'USP_InternalContentionAnalysis',N'Interne Latch- und Spinlock-Contention','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','SAMPLE_DELTA','LOW_MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Analysiert Spinlocks, Latches und Hot Pages über ein begrenztes Sample.',N'Stichprobe wiederholen und konkrete Workload-/Page-Evidenz ergänzen; kein Einzelwert ist Root Cause.',N'EXEC [monitor].[USP_InternalContentionAnalysis] @SampleSeconds = 5, @MitPageDetails = 0, @MaxZeilen = 50, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_InternalContentionAnalysis.md',NULL)
        , (N'USP_BufferPoolAnalysis',N'Buffer Pool und Memory Clerks','SERVER',N'CPU, Memory, Worker und Server Health','FOLLOW_UP','SERVER','LIVE_SNAPSHOT','LOW_HIGH_OPT_IN','SERVER_HEALTH_CURRENT',0,0,1,'CORE',NULL,N'Zeigt Buffer-Pool-Verteilung, Memory Clerks und Pressure-Kontext.',N'Breite Datenbankverteilung bleibt opt-in; Clerkgrößen ohne Workload- und Target-Memory-Kontext nicht bewerten.',N'EXEC [monitor].[USP_BufferPoolAnalysis] @MitMemoryClerks = 1, @MitBufferPoolVerteilung = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_BufferPoolAnalysis.md',NULL)
        , (N'USP_DiagnosticFindings',N'Priorisierte diagnostische Findings','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','MULTI_DATABASE','MIXED','LOW_HIGH_OPT_IN','SERVER_HEALTH_CURRENT',0,0,1,'CORE',NULL,N'Konsolidiert normalisierte Findings mit Priorität, Konfidenz, Evidenz und Aussagegrenze.',N'Findings sind Triage; Childstatus und unabhängige Gegenprobe bleiben zwingend.',N'EXEC [monitor].[USP_DiagnosticFindings] @DatabaseNames = N''[ExampleDatabase]'', @NurAbPrioritaet = ''INFO'', @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_DiagnosticFindings.md',NULL)
        , (N'USP_WorkerPressureAnalysis',N'Worker- und Scheduler-Druck','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','SERVER','SAMPLE_DELTA','LOW_MEDIUM','SERVER_HEALTH_CURRENT',0,0,0,'CORE',NULL,N'Trennt Worker-Warteschlangen von CPU-Runnable-Queues und korreliert begrenzten Laufzeitkontext.',N'Kurzes Sample; Threadpool-, Runnable-, Blocking- und Request-Evidenz gemeinsam lesen.',N'EXEC [monitor].[USP_WorkerPressureAnalysis] @SampleSeconds = 1, @MinRequestElapsedMs = 5000, @MaxZeilen = 100, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_WorkerPressureAnalysis.md',NULL)
        , (N'USP_DatabaseConfigurationAnalysis',N'Datenbankkonfiguration und Drift','SERVER',N'CPU, Memory, Worker und Server Health','ENTRY','MULTI_DATABASE','CATALOG_CONFIGURATION','LOW_MEDIUM','SERVER_CONFIGURATION_CURRENT',0,0,0,'CORE',NULL,N'Inventarisiert Datenbankoptionen und trennt lokale Variation von expliziter Profilabweichung.',N'Lokale Mehrheit ist kein Sollwert; belastbare Driftbewertung benötigt ein freigegebenes Profil.',N'EXEC [monitor].[USP_DatabaseConfigurationAnalysis] @DatabaseNames = N''[ExampleDatabaseA]|[ExampleDatabaseB]'', @MaxZeilen = 200, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_DatabaseConfigurationAnalysis.md',NULL)

        , (N'USP_ServerFeatureCapabilities',N'Versions- und Feature-Capabilities','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','ENTRY','MULTI_DATABASE','CATALOG_CONFIGURATION','LOW_MEDIUM','OBJECT_ANALYSIS_CURRENT',0,0,0,'CORE',NULL,N'Zeigt versions-, editions-, plattform- und datenbankbezogene Featurefähigkeiten einschließlich JSON-Index-Metadaten.',N'Capability bedeutet technische Verfügbarkeit, nicht aktive Nutzung oder fehlerfreien Betrieb; JSON-Index-Präsenz ist kein Healthbefund.',N'EXEC [monitor].[USP_ServerFeatureCapabilities] @DatabaseNames = N''[ExampleDatabase]'', @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerFeatureCapabilities.md',NULL)
        , (N'USP_ServerVersionInformation',N'SQL-Server-Version und Lifecycle','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','ENTRY','SERVER','FRAMEWORK_METADATA','LOW','STANDARD_CURRENT',0,0,0,'CORE',NULL,N'Ordnet Instanzbuild, Servicing-Zweig und Microsoft-Lifecycle anhand eines Offline-Katalogs ein.',N'Der Offline-Katalog kann neuer veröffentlichte Builds noch nicht kennen; verlinkte Microsoftquelle gegenprüfen.',N'EXEC [monitor].[USP_ServerVersionInformation] @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServerVersionInformation.md',NULL)
        , (N'USP_SpecialFeatureInventory',N'Spezialfeatures inventarisieren','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','ENTRY','MULTI_DATABASE','CATALOG_CONFIGURATION','LOW',NULL,0,0,0,'CORE',12,N'Erkennt leichtgewichtig verwendete Spezialfeatures und empfiehlt passende Tiefenanalysen.',N'Sichtbare Katalognutzung ist kein Gesundheitsurteil; nicht sichtbare Zeilen beweisen keine Abwesenheit.',N'EXEC [monitor].[USP_SpecialFeatureInventory] @DatabaseNames = N''[ExampleDatabase]'', @NurErkannteFeatures = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_SpecialFeatureInventory.md',NULL)
        , (N'USP_InMemoryOltpAnalysis',N'In-Memory-OLTP-Analyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','DATABASE','MIXED','MEDIUM_HIGH_OPT_IN','OBJECT_ANALYSIS_CURRENT',1,0,1,'CORE',NULL,N'Analysiert XTP-Tabellen, Hashindizes, Checkpoints, Transaktionen und Resource Pools.',N'Aktive sichtbare XTP-Nutzung und Datenbankscope erforderlich; Hashketten bleiben opt-in.',N'EXEC [monitor].[USP_InMemoryOltpAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @MitHashIndexStats = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_InMemoryOltpAnalysis.md',NULL)
        , (N'USP_TemporalAnalysis',N'Temporal-Tables-Analyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','DATABASE','CATALOG_CONFIGURATION','MEDIUM_HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Analysiert Temporal-Current-/History-Beziehungen, Retention, Größe und Indizes.',N'Sichtbare aktive Temporal-Tabellen und High-Impact-Bestätigung erforderlich; keine Zeilenkonsistenzprüfung.',N'EXEC [monitor].[USP_TemporalAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_TemporalAnalysis.md',NULL)
        , (N'USP_ServiceBrokerAnalysis',N'Service-Broker-Analyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','DATABASE','LIVE_SNAPSHOT','MEDIUM_HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Bewertet Queues, Aktivierung, Transmission und Conversations ohne Nachrichteninhalt.',N'Sichtbare Broker-Nutzung, Datenbankscope und High-Impact-Bestätigung erforderlich.',N'EXEC [monitor].[USP_ServiceBrokerAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @NurProblematisch = 1, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ServiceBrokerAnalysis.md',NULL)
        , (N'USP_FullTextAnalysis',N'Full-Text-Analyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','DATABASE','MIXED','MEDIUM_HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Bewertet Full-Text-Kataloge, Indizes und aggregierte Laufzeitmetadaten ohne indizierte Inhalte.',N'Sichtbare Full-Text-Nutzung, Datenbankscope und High-Impact-Bestätigung erforderlich.',N'EXEC [monitor].[USP_FullTextAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @NurProblematisch = 1, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_FullTextAnalysis.md',NULL)
        , (N'USP_DataCaptureDeepAnalysis',N'Data-Capture-Tiefenanalyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','DATABASE','MIXED','MEDIUM_HIGH_OPT_IN','CATALOG_DEEP',1,1,1,'CORE',NULL,N'Bewertet Change Tracking, CDC und lokal erreichbare Replikationsmetadaten ohne Nutzdaten.',N'Datenbankscope, High-Impact-Bestätigung und für CT-Verlust einen Consumer-Wasserstand bereitstellen.',N'EXEC [monitor].[USP_DataCaptureDeepAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @NurProblematisch = 1, @HighImpactConfirmed = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_DataCaptureDeepAnalysis.md',NULL)
        , (N'USP_EncryptionAnalysis',N'Verschlüsselungs- und Schutzstatus','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','ENTRY','MULTI_DATABASE','CATALOG_CONFIGURATION','MEDIUM',NULL,0,0,0,'CORE',NULL,N'Bewertet TDE-, Schutzobjekt-, Backupverschlüsselungs-, Always-Encrypted- und Ledger-Metadaten.',N'Keine Schlüssel, Pfade oder geschützten Inhalte werden gelesen; externe Schlüsselkopie und Restore bleiben außerhalb.',N'EXEC [monitor].[USP_EncryptionAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @NurProblematisch = 1, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_EncryptionAnalysis.md',NULL)
        , (N'USP_ExternalRuntimeAnalysis',N'External-Runtime-Analyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','MULTI_DATABASE','MIXED','MEDIUM_HIGH_OPT_IN','EXTERNAL_RUNTIME_CURRENT',0,0,1,'CORE',NULL,N'Analysiert External Languages, Libraries, aktive External-Script-Requests, Resource Pools und Runtime-Counter.',N'Die lesende Evidenz beweist keine Startfähigkeit einer Runtime; Datei-, Besitzer- und Sitzungskontext bleiben Opt-ins.',N'EXEC [monitor].[USP_ExternalRuntimeAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @SampleSeconds = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ExternalRuntimeAnalysis.md',NULL)
        , (N'USP_ClrAnalysis',N'SQL-CLR-Analyse','SPECIAL_FEATURE',N'Konfiguration, Sicherheit und Spezialfeatures','TARGETED','MULTI_DATABASE','MIXED','MEDIUM_HIGH_OPT_IN','CLR_CURRENT',0,0,1,'CORE',NULL,N'Analysiert SQL-CLR-Konfiguration, Assemblies, Module, Hostzustand, AppDomains, Tasks, Requests, Speicher und Counter.',N'Binärinhalt und Hashabgleich sind ausgeschlossen; die Analyse aktiviert CLR nicht und lädt keine Assembly.',N'EXEC [monitor].[USP_ClrAnalysis] @DatabaseNames = N''[ExampleDatabase]'', @SampleSeconds = 0, @ResultSetArt = ''CONSOLE'';',N'Documentation/Analysis_Guides/Procedures/USP_ClrAnalysis.md',NULL)

        , (N'USP_ConfigureSnapshotTarget',N'Snapshotziel konfigurieren','SNAPSHOT',N'Optionales Snapshot- und Baseline-Paket','SETUP','SNAPSHOT_TARGET','CATALOG_CONFIGURATION','LOW',NULL,1,0,0,'SNAPSHOT_OPTIONAL',NULL,N'Verknüpft die Frameworkdatenbank mit einer separat installierten Snapshotdatenbank und schreibt typisierte Policies.',N'SC-023 muss separat installiert sein; Zielname, Retention, Budget und Datenschutzvertrag explizit festlegen.',N'EXEC [monitor].[USP_ConfigureSnapshotTarget] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_ConfigureSnapshotTarget.md',NULL)
        , (N'USP_RunSnapshotCollectionCycle',N'Snapshot-Collection-Cycle','SNAPSHOT',N'Optionales Snapshot- und Baseline-Paket','TARGETED','SNAPSHOT_TARGET','PERSISTED_SNAPSHOT','LOW_MEDIUM',NULL,1,0,0,'SNAPSHOT_OPTIONAL',NULL,N'Führt einen begrenzten, schedulerneutralen Collection Cycle in das konfigurierte Snapshotziel aus.',N'SC-023 installiert, Ziel aktiv und Policy konfiguriert; schreibt reale Laufzeitevidenz in die lokale Zieldatenbank.',N'EXEC [monitor].[USP_RunSnapshotCollectionCycle] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_RunSnapshotCollectionCycle.md',NULL)
        , (N'USP_PurgeSnapshotData',N'Abgelaufene Snapshotdaten löschen','SNAPSHOT',N'Optionales Snapshot- und Baseline-Paket','SETUP','SNAPSHOT_TARGET','PERSISTED_SNAPSHOT','LOW_MEDIUM',NULL,1,0,0,'SNAPSHOT_OPTIONAL',NULL,N'Entfernt ausschließlich abgelaufene Snapshotdaten in begrenzten Child-first-Batches.',N'Destruktiver, aber retentiongebundener SC-023-Betriebspfad; Ziel, Policy und Batchgrenzen vor Ausführung prüfen.',N'EXEC [monitor].[USP_PurgeSnapshotData] @Hilfe = 1;',N'Documentation/Analysis_Guides/Procedures/USP_PurgeSnapshotData.md',NULL)
        , (N'USP_FrameworkUsageFromQueryStore',N'Framework-Nutzung aus Query Store','VERSION_ADAPTIVE',N'Versionsadaptive Spezialanalysen','ENTRY','CURRENT_DATABASE','QUERY_STORE_SNAPSHOT','LOW','QUERY_STORE_CURRENT',0,0,0,'CORE',NULL,N'Zeigt aus dem Query Store, welche Framework-Procedures mit welcher Häufigkeit und Laufzeit aufgerufen wurden.',N'Query Store muss in der Installationsdatenbank aktiviert sein.',N'EXEC [monitor].[USP_FrameworkUsageFromQueryStore];',N'Documentation/Analysis_Guides/Procedures/USP_FrameworkUsageFromQueryStore.md',NULL)
    ) AS [v]
    (
          [ProcedureName], [DisplayName], [PrimaryAreaCode], [PrimaryAreaName]
        , [NavigationRole], [ScopeCode], [EvidenceType], [CostRangeCode]
        , [RepresentativeAnalysisClass], [RequiresKnownTarget]
        , [RequiresHighImpactForSafeStart], [HighImpactPathAvailable]
        , [PackageCode], [DefaultRank], [Purpose], [PrerequisiteSummary]
        , [SafeCall], [DocumentationPath], [RunbookPath]
    );
GO
