USE [DeineDatenbank];
GO

/*
===============================================================================
Objekt       : monitor.VW_AnalysisSearchTerm
Version      : 1.2.0
Stand        : 2026-07-23
Typ          : View
Zweck        : Liefert deutsch- und englischsprachige Symptome, Ziele,
               Synonyme und technische Suchbegriffe für den Analysis Navigator.
Semantik     : Mehrere Zeilen je Procedure sind beabsichtigt. SearchWeight
               priorisiert fachlich spezifische Begriffe; MatchReason erklärt
               dem Anwender, warum ein Treffer vorgeschlagen wird.
Eigenlast    : Konstante Frameworkmetadaten; keine fachlichen Datenzugriffe.
===============================================================================
*/
CREATE OR ALTER VIEW [monitor].[VW_AnalysisSearchTerm]
AS
    SELECT
          CONVERT(sysname, [v].[ProcedureName]) AS [ProcedureName]
        , CONVERT(nvarchar(200), [v].[SearchTerm]) AS [SearchTerm]
        , CONVERT(char(2), [v].[LanguageCode]) AS [LanguageCode]
        , CONVERT(tinyint, [v].[SearchWeight]) AS [SearchWeight]
        , CONVERT(nvarchar(500), [v].[MatchReason]) AS [MatchReason]
    FROM
    (
        VALUES
          (N'USP_AnalysisNavigator',N'welche Analyse verwenden','de',100,N'Der Navigator beantwortet die Auswahlfrage, ohne eine Diagnose zu starten.')
        , (N'USP_AnalysisNavigator',N'find analysis','en',100,N'Direkter Einstieg in die symptom- und zielorientierte Suche.')
        , (N'USP_CheckAnalyseAccess',N'Analyse nicht freigegeben','de',100,N'Prüft die interne Ressourcenfreigabe des aktuellen Sicherheitskontexts.')
        , (N'USP_CheckAnalyseAccess',N'access denied analysis class','en',95,N'Zeigt Gruppenmatch und Analyseklassenpolicy.')
        , (N'USP_CheckFrameworkCapabilities',N'fehlende Berechtigung oder Feature','de',100,N'Prüft Version, Rechte, Policy und Featurefähigkeit gemeinsam.')
        , (N'USP_CheckFrameworkCapabilities',N'capability permission feature unavailable','en',95,N'Geeignet zur Erklärung nicht verfügbarer Diagnosepfade.')
        , (N'USP_PrepareDatabaseCandidates',N'Datenbankauswahlvertrag','de',90,N'Interner Vertrag für die konsistente Datenbankauswahl.')
        , (N'USP_PrepareDatabaseCandidates',N'database candidate selection','en',85,N'Unterstützender Datenbankscope-Baustein.')
        , (N'USP_PrepareNameFilters',N'Namensfiltervertrag','de',90,N'Interner Vertrag für exakte und Pattern-basierte Namensfilter.')
        , (N'USP_PrepareNameFilters',N'name filter parser','en',85,N'Unterstützender Filterbaustein.')

        , (N'USP_CurrentSessions',N'aktive Sessions Verbindungen','de',90,N'Inventarisiert aktuelle Sessions und Verbindungen.')
        , (N'USP_CurrentSessions',N'current sessions connections','en',85,N'Geeignet für Session- und Verbindungskontext.')
        , (N'USP_CurrentRequests',N'CPU hoch','de',100,N'Zeigt aktuell CPU-intensive Requests und ihren Laufzeitkontext.')
        , (N'USP_CurrentRequests',N'langsame Query jetzt','de',100,N'Geeignet, wenn die Query im Moment noch läuft.')
        , (N'USP_CurrentRequests',N'high CPU active request slow query','en',95,N'Korrelierte Live-Sicht auf aktive Requests.')
        , (N'USP_CurrentBlocking',N'Benutzer warten','de',100,N'Prüft aktuelle Blockingketten und den Root Blocker.')
        , (N'USP_CurrentBlocking',N'Hänger Blocking Sperre','de',100,N'Direkter Live-Einstieg bei blockierten Benutzern.')
        , (N'USP_CurrentBlocking',N'blocking root blocker lock chain','en',95,N'Rekonstruiert aktuelle Blocking Chains.')
        , (N'USP_CurrentWaits',N'aktuelle Waits Wartezeiten','de',95,N'Ordnet aktuelle und gesampelte Waits fachlich ein.')
        , (N'USP_CurrentWaits',N'current waits wait statistics','en',90,N'Wait-Snapshot und optionales Delta.')
        , (N'USP_CurrentTransactions',N'alte offene Transaktion','de',100,N'Findet lange oder vergessene offene Transaktionen.')
        , (N'USP_CurrentTransactions',N'old open transaction sleeping session','en',95,N'Korrelierter Transaktions- und Sessionkontext.')
        , (N'USP_CurrentMemoryGrants',N'Memory Grants warten','de',100,N'Zeigt wartende Query Memory Grants.')
        , (N'USP_CurrentMemoryGrants',N'Benutzer warten Speicher','de',75,N'Kann bei RESOURCE_SEMAPHORE-Warteschlangen relevant sein.')
        , (N'USP_CurrentMemoryGrants',N'memory grant queue resource semaphore','en',95,N'Korrelierte Grant- und Waitsicht.')
        , (N'USP_CurrentTempDB',N'TempDB wächst','de',100,N'Zeigt aktuellen TempDB-Verbrauch nach Ursache und Session.')
        , (N'USP_CurrentTempDB',N'TempDB voll Version Store','de',95,N'Trennt User Objects, Internal Objects und Version Store.')
        , (N'USP_CurrentTempDB',N'tempdb growth space usage','en',95,N'Aktueller TempDB-Verbrauch.')
        , (N'USP_CurrentTempDB',N'TempDB Workload Group Limit Verletzung','de',100,N'Trennt wirksames Limit, Nutzung, Peak und kumulative Verletzungen.')
        , (N'USP_CurrentTempDB',N'tempdb resource governance limit violation','en',100,N'SQL-Server-2025-Workload-Group-Governance im TempDB-Kontext.')
        , (N'USP_CurrentIO',N'I/O Latenz hoch','de',100,N'Bewertet aktuelle Datei-I/O-Latenz und Pending I/O.')
        , (N'USP_CurrentIO',N'langsame Datendatei Storage','de',90,N'Korrelierte Datei- und Sampleevidenz.')
        , (N'USP_CurrentIO',N'io latency slow storage pending io','en',95,N'Kumulative und gesampelte I/O-Sicht.')
        , (N'USP_CurrentLog',N'Log voll','de',100,N'Zeigt Logauslastung und Wiederverwendungswartegrund.')
        , (N'USP_CurrentLog',N'Transaktionslog wächst','de',100,N'Verknüpft Logverbrauch, Reuse Wait und VLF-Kontext.')
        , (N'USP_CurrentLog',N'transaction log full log reuse wait','en',95,N'Aktueller Log- und Wiederverwendungskontext.')
        , (N'USP_CurrentOverview',N'etwas ist jetzt langsam','de',100,N'Orchestrierter leichter Live-Einstieg bei unklarem aktuellem Symptom.')
        , (N'USP_CurrentOverview',N'Server hängt aktuell','de',95,N'Bündelt mehrere aktuelle Triagequellen.')
        , (N'USP_CurrentOverview',N'live triage current overview','en',95,N'Sicherer allgemeiner Live-Einstieg.')

        , (N'USP_ObjectInventory',N'Objekte Größe Indizes inventarisieren','de',95,N'Liefert Objekt-, Index-, Größen- und Partitionsinventar.')
        , (N'USP_ObjectInventory',N'object inventory index size','en',90,N'Gezielte Objektinventur.')
        , (N'USP_ObjectInventory',N'JSON-Index Pfade inventarisieren','de',100,N'Liefert sichtbare SQL-Server-2025-JSON-Index- und SQL/JSON-Pfadmetadaten.')
        , (N'USP_ObjectInventory',N'json index paths inventory','en',100,N'Routes visible JSON-index definitions and path metadata to the object inventory.')
        , (N'USP_IndexUsage',N'Index ungenutzt','de',100,N'Zeigt kumulative Lese- und Schreibnutzung seit Reset.')
        , (N'USP_IndexUsage',N'unused index usage statistics','en',95,N'Prüft Indexnutzung mit Resetgrenzen.')
        , (N'USP_IndexOperationalStats',N'Index Locks Latches Page Splits','de',100,N'Zeigt operative Indexzähler je Partition.')
        , (N'USP_IndexOperationalStats',N'index operational stats latch lock','en',95,N'Vertiefung für operative Indexaktivität.')
        , (N'USP_MissingIndexes',N'fehlender Index','de',100,N'Priorisiert flüchtige Missing-Index-Evidenz.')
        , (N'USP_MissingIndexes',N'missing index suggestion','en',95,N'Optimizerhinweise ohne automatische DDL-Empfehlung.')
        , (N'USP_Statistics',N'Statistik veraltet Änderungen Sample','de',100,N'Zeigt Statistikdefinition, Sample und Modification Counter.')
        , (N'USP_Statistics',N'stale statistics sample modification counter','en',95,N'Gezielter Statistikzustand.')
        , (N'USP_Statistics',N'lesbare Secondary Statistik Replikat Herkunft','de',100,N'Ordnet SQL-Server-2025-Statistiken ihrer gespeicherten Replica-Herkunft zu und trennt die aktuelle Datenbankrolle.')
        , (N'USP_Statistics',N'readable secondary statistics replica origin','en',100,N'Finds SQL Server 2025 statistics origin metadata without treating it as query-usage evidence.')
        , (N'USP_StatisticsDistributionAnalysis',N'Histogramm Skew Schieflage','de',100,N'Analysiert Histogrammverteilung und dominante Schritte.')
        , (N'USP_StatisticsDistributionAnalysis',N'statistics histogram skew tail','en',95,N'Vertiefte Statistikverteilung.')
        , (N'USP_Partitions',N'Partitionen Grenzen Kompression','de',95,N'Zeigt Partitionsgrenzen, Ablage und Kompression.')
        , (N'USP_Partitions',N'partition boundary compression','en',90,N'Gezielte Partitionsanalyse.')
        , (N'USP_Columnstore',N'Columnstore Deleted Rows Rowgroups','de',100,N'Analysiert Rowgroups und optionale Speicherdetails.')
        , (N'USP_Columnstore',N'columnstore rowgroup dictionary segment','en',95,N'Gezielte Columnstore-Analyse.')
        , (N'USP_IndexPhysicalStats',N'Index Fragmentierung Seitendichte','de',100,N'Misst die physische Indexstruktur.')
        , (N'USP_IndexPhysicalStats',N'index fragmentation page density physical stats','en',95,N'Physischer High-Impact-Scan mit Zielscope.')
        , (N'USP_VectorIndexAnalysis',N'Vector Index Staleness Wartung','de',100,N'Prüft sichtbare Vector-Indizes und den aktuellen Hintergrundwartungszustand.')
        , (N'USP_VectorIndexAnalysis',N'Vector Index Hintergrundtask fehlgeschlagen','de',95,N'Ordnet Taskfehler und den konfigurierbaren Staleness-Reviewwert ein.')
        , (N'USP_VectorIndexAnalysis',N'vector index health staleness maintenance','en',100,N'Correlates visible vector indexes with current background maintenance evidence.')
        , (N'USP_VectorIndexAnalysis',N'vector background task failed','en',95,N'Finds the last visible maintenance failure without recommending an automatic rebuild.')
        , (N'USP_ObjectAnalysis',N'Objekt vollständig analysieren','de',100,N'Orchestrierter Einstieg für ein bekanntes Objekt.')
        , (N'USP_ObjectAnalysis',N'object index deep analysis','en',95,N'Bündelt mehrere Objekt- und Indexpfade.')
        , (N'USP_SchemaDesignAnalysis',N'Schema Design Foreign Key Constraint','de',100,N'Erzeugt Reviewfindings zu Schema- und Constraintdesign.')
        , (N'USP_SchemaDesignAnalysis',N'schema design foreign key constraint identity','en',95,N'Vertiefter Katalogreview.')

        , (N'USP_QueryStats',N'langsame Query Plan Cache','de',100,N'Rangiert gecachte Statements nach Ressourcenverbrauch.')
        , (N'USP_QueryStats',N'top CPU query logical reads','en',95,N'Plan-Cache-Einstieg nach Ressourcenmetrik.')
        , (N'USP_QueryHashAnalysis',N'Query Hash mehrere Pläne','de',100,N'Gruppiert Cachezeilen nach Query Hash und Planvariante.')
        , (N'USP_QueryHashAnalysis',N'query hash plan variants','en',95,N'Vertiefung bei mehreren Cacheplänen.')
        , (N'USP_PlanCacheHealth',N'Plan Cache aufgebläht Single Use','de',100,N'Bewertet Cachegröße und Single-Use-Anteil.')
        , (N'USP_PlanCacheHealth',N'plan cache bloat single use','en',95,N'Plan-Cache-Gesundheit auf Instanzebene.')
        , (N'USP_PlanDetails',N'Planhandle letzter tatsächlicher Plan','de',100,N'Löst gezielte Planattribute und Planquellen auf.')
        , (N'USP_PlanDetails',N'plan handle last actual live query plan','en',95,N'Gezielte Planbeschaffung.')
        , (N'USP_ShowplanAnalysis',N'Execution Plan Operator Warnungen','de',100,N'Extrahiert Operator-, Kardinalitäts-, Grant- und Warnungsevidenz.')
        , (N'USP_ShowplanAnalysis',N'showplan operator warning cardinality','en',95,N'Gezielte Showplan-XML-Analyse.')
        , (N'USP_PlanCacheAnalysis',N'Plan Cache vollständig analysieren','de',100,N'Orchestriert die Plan-Cache-Analysen.')
        , (N'USP_PlanCacheAnalysis',N'plan cache analysis orchestrator','en',95,N'Gebündelte Plan-Cache-Tiefenanalyse.')
        , (N'USP_CreateExecutionEvidenceJson',N'STATISTICS IO TIME normalisieren','de',100,N'Erzeugt ein normalisiertes Evidence-JSON aus bereits erfasster Evidenz.')
        , (N'USP_CreateExecutionEvidenceJson',N'execution evidence json statistics io time','en',95,N'Normalisiert Ausführungsevidenz für die Plananalyse.')
        , (N'USP_ExecutionPlanAnalysis',N'Plan XML analysieren','de',100,N'Eigenständiger Einstieg für ein vorhandenes Showplan-XML.')
        , (N'USP_ExecutionPlanAnalysis',N'langsame Query mit Plan','de',90,N'Analysiert Statements, Operatoren, Kardinalität, Spills und Grants.')
        , (N'USP_ExecutionPlanAnalysis',N'execution plan xml analyze actual plan','en',100,N'Eigenständige statement- und operatorbezogene Plananalyse.')

        , (N'USP_QueryStoreStatus',N'Query Store Status Read Only voll','de',100,N'Prüft Capture, Retention, Speicher und Cleanup vor Detailanalysen.')
        , (N'USP_QueryStoreStatus',N'query store status read only cleanup','en',95,N'Query-Store-Voraussetzungsprüfung.')
        , (N'USP_QueryStoreRuntimeStats',N'Query Historie Laufzeit CPU Reads','de',100,N'Aggregiert historische Query- und Planmetriken.')
        , (N'USP_QueryStoreRuntimeStats',N'query store runtime history','en',95,N'Historische Laufzeit- und Ressourcenauswertung.')
        , (N'USP_QueryStoreWaitStats',N'historische Query Waits','de',100,N'Aggregiert Query-Store-Waitkategorien.')
        , (N'USP_QueryStoreWaitStats',N'query store wait statistics','en',95,N'Historische Waitanalyse je Query und Plan.')
        , (N'USP_QueryStorePlanChanges',N'Planwechsel Compile Context','de',100,N'Findet Query-Store-Queries mit mehreren Plänen.')
        , (N'USP_QueryStorePlanChanges',N'query store plan changes compile','en',95,N'Planwechsel- und Compilekontext.')
        , (N'USP_QueryStoreRegressions',N'Query plötzlich langsamer','de',100,N'Vergleicht Baseline- und Problemzeitfenster.')
        , (N'USP_QueryStoreRegressions',N'langsame Query gestern heute','de',100,N'Historischer Regressionsvergleich.')
        , (N'USP_QueryStoreRegressions',N'query regression slower over time','en',100,N'Query-Store-Zeitfenstervergleich.')
        , (N'USP_QueryStoreForcedPlans',N'Forced Plan Fehler','de',100,N'Inventarisiert erzwungene Pläne und Force-Fehler.')
        , (N'USP_QueryStoreForcedPlans',N'forced plan forcing failure','en',95,N'Governance- und Fehlerprüfung für Forced Plans.')
        , (N'USP_QueryStoreHints',N'Query Store Hint Fehler','de',100,N'Zeigt Hints, Herkunft und Anwendungsfehler.')
        , (N'USP_QueryStoreHints',N'query store hints failure','en',95,N'Query-Hint-Governance.')
        , (N'USP_QueryStoreAnalysis',N'Query Store vollständig analysieren','de',100,N'Orchestriert Status, Historie, Regressionen und Governance.')
        , (N'USP_QueryStoreAnalysis',N'query store analysis orchestrator','en',95,N'Gebündelte Query-Store-Analyse.')
        , (N'USP_IntelligentQueryProcessingAnalysis',N'IQP Feedback Parameter Sensitive Plan','de',100,N'Zeigt IQP-Eignung, Konfiguration und Feedbacksignale.')
        , (N'USP_IntelligentQueryProcessingAnalysis',N'intelligent query processing memory grant feedback psp','en',95,N'Vertiefung für IQP-Features.')

        , (N'USP_ExtendedEventsSessions',N'Extended Events Sessions inventarisieren','de',100,N'Zeigt Definition und Laufzeitstatus vorhandener XE-Sessions.')
        , (N'USP_ExtendedEventsSessions',N'extended events session inventory','en',95,N'Leichter XE-Inventareinstieg.')
        , (N'USP_ExtendedEventsReadEvents',N'XEL Datei Ereignisse lesen','de',100,N'Liest einzelne erhaltene XE-Ereignisse aus einer bekannten Quelle.')
        , (N'USP_ExtendedEventsReadEvents',N'read xel event file ring buffer','en',95,N'Gezielte XE-Ereignisforensik.')
        , (N'USP_ExtendedEventsDeadlocks',N'Deadlock','de',100,N'Zerlegt erhaltene Deadlockgraphs.')
        , (N'USP_ExtendedEventsDeadlocks',N'Todesblockierung','de',80,N'Historische Deadlockanalyse aus XE-Daten.')
        , (N'USP_ExtendedEventsDeadlocks',N'deadlock graph victim resource','en',100,N'Deadlock-Victim-, Prozess- und Ressourcenansicht.')
        , (N'USP_ExtendedEventsBlockedProcesses',N'vergangenes Blocking','de',100,N'Liest historische Blocked-Process-Reports.')
        , (N'USP_ExtendedEventsBlockedProcesses',N'blocked process report history','en',95,N'Historische Blocking-Ereignisse.')
        , (N'USP_ExtendedEventsTargetRuntime',N'XE Target verloren dropped events','de',100,N'Zeigt Targetruntime und Verlustsignale.')
        , (N'USP_ExtendedEventsTargetRuntime',N'extended events target runtime dropped','en',95,N'Runtime- und Verlustkontext für XE-Targets.')
        , (N'USP_ExtendedEventsAnalysis',N'Extended Events vollständig analysieren','de',100,N'Orchestriert XE-Inventar und optionale Ereignispfade.')
        , (N'USP_ExtendedEventsAnalysis',N'extended events analysis orchestrator','en',95,N'Gebündelte XE-Analyse.')

        , (N'USP_AgentStatus',N'SQL Agent läuft nicht','de',100,N'Zeigt Dienst- und Basiskontext des SQL Server Agent.')
        , (N'USP_AgentStatus',N'sql server agent service status','en',95,N'Leichter Agentstatus.')
        , (N'USP_AgentJobs',N'Job fehlgeschlagen lange Laufzeit','de',100,N'Zeigt problematische Jobs und Historie.')
        , (N'USP_AgentJobs',N'failed long running agent job','en',95,N'Jobstatus-, Dauer- und Fehleranalyse.')
        , (N'USP_ResourceGovernorAnalysis',N'Resource Governor Pool Gruppe','de',100,N'Zeigt Pools, Gruppen, Limits und Sessions.')
        , (N'USP_ResourceGovernorAnalysis',N'resource governor pool workload group','en',95,N'Resource-Governor-Kontext.')
        , (N'USP_ResourceGovernorAnalysis',N'TempDB Resource Governance Wirksamkeit','de',100,N'Zeigt gespeichertes und wirksames Workload-Group-Limit getrennt.')
        , (N'USP_ResourceGovernorAnalysis',N'tempdb workload group effective limit','en',100,N'Limitquelle, Nutzung, Peak, Verletzungen und Resetgrenze.')
        , (N'USP_AvailabilityGroups',N'Availability Group Status','de',100,N'Zeigt Replica-, Datenbank- und Routingzustand.')
        , (N'USP_AvailabilityGroups',N'always on availability group status','en',95,N'AG-Basisstatus.')
        , (N'USP_BackupRecovery',N'Backup fehlt zu alt','de',100,N'Prüft Backupalter, Recovery Model und Restorehistorie.')
        , (N'USP_BackupRecovery',N'backup overdue recovery restore history','en',95,N'Backup- und Recovery-Einstieg.')
        , (N'USP_LogShippingStatus',N'Log Shipping hängt','de',100,N'Zeigt Backup-, Copy- und Restorepipeline.')
        , (N'USP_LogShippingStatus',N'log shipping copy restore delay','en',95,N'Log-Shipping-Statusanalyse.')
        , (N'USP_ReplicationStatus',N'Replikation hängt Backlog','de',100,N'Zeigt Agents, Latenz und Backlog.')
        , (N'USP_ReplicationStatus',N'replication latency backlog agent','en',95,N'Replikationsstatus und lokale Topologie.')
        , (N'USP_DataCaptureStatus',N'CDC Change Tracking Status','de',100,N'Zeigt Data-Capture-Konfiguration und Jobs.')
        , (N'USP_DataCaptureStatus',N'cdc change tracking capture status','en',95,N'Leichte Data-Capture-Inventur.')
        , (N'USP_InfrastructureAnalysis',N'Betrieb Infrastruktur prüfen','de',100,N'Orchestrierter Überblick über Agent, Backup und HA/DR.')
        , (N'USP_InfrastructureAnalysis',N'infrastructure operations health','en',95,N'Gebündelte Betriebsanalyse.')
        , (N'USP_BackupChainAnalysis',N'Backupkette LSN Restore','de',100,N'Prüft die logische Sicherungskette.')
        , (N'USP_BackupChainAnalysis',N'backup chain lsn restore sequence','en',95,N'Vertiefte Backupkettenanalyse.')
        , (N'USP_AvailabilityDeepAnalysis',N'AG Lag Redo Queue Send Queue','de',100,N'Vertieft Availability-Lag und Queues.')
        , (N'USP_AvailabilityDeepAnalysis',N'availability group lag redo send queue','en',100,N'AG-Lag- und Replicaevidenz.')
        , (N'USP_AgentMonitoringAnalysis',N'Alert Operator Database Mail','de',100,N'Verknüpft Agentprobleme mit Benachrichtigungswegen.')
        , (N'USP_AgentMonitoringAnalysis',N'agent alert operator database mail','en',95,N'Agent-Monitoring- und Alertpfad.')
        , (N'USP_MaintenanceOperations',N'Index Rebuild pausiert Wartung läuft','de',100,N'Zeigt laufende und resumierbare Wartungsoperationen read-only.')
        , (N'USP_MaintenanceOperations',N'resumable index maintenance operation','en',95,N'Wartungs- und Operationsstatus.')
        , (N'USP_ErrorLogAnalysis',N'Errorlog schwere Fehler','de',100,N'Verdichtet aktuelle Errorlogkategorien.')
        , (N'USP_ErrorLogAnalysis',N'sql server error log critical error','en',95,N'Begrenzte Errorloganalyse.')

        , (N'USP_ServerCpuTopology',N'CPU Kerne Scheduler Topologie','de',100,N'Zeigt Hardware- und Schedulerkontext.')
        , (N'USP_ServerCpuTopology',N'cpu socket core scheduler topology','en',95,N'CPU-Topologie und Schedulerverteilung.')
        , (N'USP_ServerNuma',N'NUMA Ungleichgewicht','de',100,N'Zeigt NUMA- und Memory-Node-Verteilung.')
        , (N'USP_ServerNuma',N'numa node imbalance','en',95,N'NUMA-Kontextanalyse.')
        , (N'USP_ServerMemory',N'Memory Pressure Speicher knapp','de',100,N'Verknüpft OS- und SQL-Memory-Evidenz.')
        , (N'USP_ServerMemory',N'sql server memory pressure clerks','en',95,N'Server- und Prozessmemory.')
        , (N'USP_TempDBConfiguration',N'TempDB Dateien Wachstum Konfiguration','de',100,N'Prüft Dateigleichheit und Wachstumseinstellungen.')
        , (N'USP_TempDBConfiguration',N'tempdb file configuration autogrowth','en',95,N'TempDB-Konfigurationsanalyse.')
        , (N'USP_ServerConfiguration',N'Server Konfiguration prüfen','de',100,N'Zeigt konfigurierte und aktive Serveroptionen.')
        , (N'USP_ServerConfiguration',N'sp_configure server configuration','en',95,N'Serverkonfigurationsreview.')
        , (N'USP_TraceFlags',N'aktive Trace Flags','de',100,N'Inventarisiert Trace Flags und Scope.')
        , (N'USP_TraceFlags',N'active trace flags','en',95,N'Trace-Flag-Inventur.')
        , (N'USP_StartupParameters',N'Startparameter Startup Pfad','de',100,N'Zeigt Startparameter und persistente Flags.')
        , (N'USP_StartupParameters',N'sql server startup parameters','en',95,N'Startkonfigurationsanalyse.')
        , (N'USP_OSInformation',N'Betriebssystem Virtualisierung Uptime','de',100,N'Zeigt Plattform- und Hostkontext.')
        , (N'USP_OSInformation',N'operating system virtualization uptime','en',95,N'OS- und Plattforminformation.')
        , (N'USP_ServerSecurityConfiguration',N'Sicherheitskonfiguration unsicher','de',100,N'Erzeugt Reviewbefunde zu sicherheitsrelevanten Optionen.')
        , (N'USP_ServerSecurityConfiguration',N'server security configuration review','en',95,N'Sicherheitskonfigurationsreview.')
        , (N'USP_ServerHealthAnalysis',N'Server Health prüfen','de',100,N'Orchestrierter Überblick über Serverzustand und Konfiguration.')
        , (N'USP_ServerHealthAnalysis',N'server health analysis','en',95,N'Gebündelte Server-Health-Triage.')
        , (N'USP_DatabaseIntegrityAnalysis',N'Integrität CHECKDB suspect pages','de',100,N'Korrelierte Integritätsevidenz ohne DBCC-Ausführung.')
        , (N'USP_DatabaseIntegrityAnalysis',N'database integrity checkdb suspect pages','en',95,N'Integritäts- und Backupevidenz.')
        , (N'USP_DatabaseCapacityAnalysis',N'Datenbank voll Volume Platz','de',100,N'Bewertet Datei- und Volumekapazität.')
        , (N'USP_DatabaseCapacityAnalysis',N'database capacity disk volume free space','en',95,N'Kapazitäts- und Wachstumsspielraum.')
        , (N'USP_PerformanceCounters',N'Performance Counter Delta','de',100,N'Liest typisierte Counter und berechnet Samples.')
        , (N'USP_PerformanceCounters',N'performance counters sample delta','en',95,N'Countertyp- und Deltaanalyse.')
        , (N'USP_CriticalEngineEvents',N'kritische Engine Fehler system_health','de',100,N'Liest schwere erhaltene Engine-Ereignisse.')
        , (N'USP_CriticalEngineEvents',N'critical engine events system health','en',95,N'Kritische XE- und Diagnostikevidenz.')
        , (N'USP_InternalContentionAnalysis',N'Spinlock Latch Hot Page','de',100,N'Analysiert interne Contention über ein Sample.')
        , (N'USP_InternalContentionAnalysis',N'spinlock latch hot page contention','en',95,N'Interne Contention-Vertiefung.')
        , (N'USP_BufferPoolAnalysis',N'Buffer Pool Clerks Pressure','de',100,N'Verknüpft Buffer Pool und Memory Clerks.')
        , (N'USP_BufferPoolAnalysis',N'buffer pool memory clerks pressure','en',95,N'Buffer-Pool- und Clerk-Analyse.')
        , (N'USP_DiagnosticFindings',N'priorisierte Findings Ursachenhinweise','de',100,N'Konsolidiert Triagefindings mehrerer Module.')
        , (N'USP_DiagnosticFindings',N'diagnostic findings severity confidence','en',95,N'Priorisierte Befunde mit Evidenzgrenzen.')
        , (N'USP_WorkerPressureAnalysis',N'THREADPOOL Worker erschöpft','de',100,N'Trennt Worker- von CPU-Runnable-Druck.')
        , (N'USP_WorkerPressureAnalysis',N'CPU hoch runnable queue','de',75,N'Kann Schedulerdruck von Workerknappheit abgrenzen.')
        , (N'USP_WorkerPressureAnalysis',N'worker threadpool runnable queue pressure','en',95,N'Worker- und Schedulerdruck.')
        , (N'USP_DatabaseConfigurationAnalysis',N'Datenbank Konfigurationsdrift','de',100,N'Vergleicht Datenbankoptionen mit lokaler Variation oder Profil.')
        , (N'USP_DatabaseConfigurationAnalysis',N'database configuration drift profile','en',95,N'Datenbankkonfigurationsanalyse.')

        , (N'USP_ServerFeatureCapabilities',N'Feature verfügbar Version Edition','de',100,N'Zeigt Capability nach Version, Edition und Plattform.')
        , (N'USP_ServerFeatureCapabilities',N'feature capability version edition platform','en',95,N'Versionsadaptive Featureprüfung.')
        , (N'USP_ServerFeatureCapabilities',N'JSON-Index Capability Preview','de',100,N'Zeigt die versions- und buildabhängige JSON-Index-Metadatenfähigkeit.')
        , (N'USP_ServerFeatureCapabilities',N'json index capability preview','en',100,N'Checks JSON-index catalog capability and visible structural inventory.')
        , (N'USP_ServerVersionInformation',N'SQL Server Version CU Lifecycle','de',100,N'Ordnet Build, Servicing und Lifecycle ein.')
        , (N'USP_ServerVersionInformation',N'sql server version build cu lifecycle','en',100,N'Versions- und Lifecycleinformation.')
        , (N'USP_SpecialFeatureInventory',N'welche Spezialfeatures werden verwendet','de',100,N'Leichte Inventur und Auswahl passender Tiefenmodule.')
        , (N'USP_SpecialFeatureInventory',N'special feature inventory','en',95,N'Findet sichtbare Spezialfeaturenutzung.')
        , (N'USP_InMemoryOltpAnalysis',N'In-Memory OLTP XTP Hash Index','de',100,N'Analysiert XTP-Objekte und Laufzeitmetadaten.')
        , (N'USP_InMemoryOltpAnalysis',N'in memory oltp xtp hash index','en',95,N'XTP-Tiefenanalyse.')
        , (N'USP_TemporalAnalysis',N'Temporal History Table Retention','de',100,N'Analysiert Temporalbeziehungen und Retention.')
        , (N'USP_TemporalAnalysis',N'temporal tables history retention','en',95,N'Temporal-Tables-Tiefenanalyse.')
        , (N'USP_ServiceBrokerAnalysis',N'Service Broker Queue Transmission','de',100,N'Analysiert Brokerqueues und Transmissionzustände.')
        , (N'USP_ServiceBrokerAnalysis',N'service broker queue transmission activation','en',95,N'Service-Broker-Tiefenanalyse.')
        , (N'USP_FullTextAnalysis',N'Full Text Population Fragment','de',100,N'Analysiert Full-Text-Katalog- und Laufzeitzustände.')
        , (N'USP_FullTextAnalysis',N'full text population fragment catalog','en',95,N'Full-Text-Tiefenanalyse.')
        , (N'USP_DataCaptureDeepAnalysis',N'CDC Latenz Change Tracking Verlust','de',100,N'Vertieft CDC, CT und lokale Replikation.')
        , (N'USP_DataCaptureDeepAnalysis',N'cdc latency change tracking retention','en',95,N'Data-Capture-Tiefenanalyse.')
        , (N'USP_EncryptionAnalysis',N'TDE Backupverschlüsselung Always Encrypted','de',100,N'Bewertet sichtbare Verschlüsselungs- und Schutzmetadaten.')
        , (N'USP_EncryptionAnalysis',N'tde backup encryption always encrypted ledger','en',95,N'Verschlüsselungs- und Schutzstatus.')
        , (N'USP_ExternalRuntimeAnalysis',N'R Python Java C# Launchpad External Script','de',100,N'External-Runtime-Konfiguration, Kataloge und aktuelle Laufzeitevidenz.')
        , (N'USP_ExternalRuntimeAnalysis',N'external runtime language library launchpad resource pool','en',95,N'External-Runtime-Tiefenanalyse ohne Testausführung.')
        , (N'USP_ClrAnalysis',N'SQL CLR Assembly AppDomain Managed Code','de',100,N'SQL-CLR-Katalog-, Host- und Laufzeitanalyse.')
        , (N'USP_ClrAnalysis',N'sql clr assembly appdomain managed code task','en',95,N'SQL-CLR-Tiefenanalyse ohne Assemblyausführung.')

        , (N'USP_ConfigureSnapshotTarget',N'Snapshot konfigurieren Retention','de',100,N'Konfiguriert das optionale persistente Snapshotziel.')
        , (N'USP_ConfigureSnapshotTarget',N'configure snapshot target retention','en',95,N'SC-023-Ziel- und Policykonfiguration.')
        , (N'USP_RunSnapshotCollectionCycle',N'Snapshot erfassen Baseline','de',100,N'Führt einen begrenzten Collection Cycle aus.')
        , (N'USP_RunSnapshotCollectionCycle',N'run snapshot collection baseline','en',95,N'Persistiert einen SC-023-Snapshotlauf.')
        , (N'USP_PurgeSnapshotData',N'Snapshot Retention löschen','de',100,N'Entfernt abgelaufene SC-023-Daten nach Policy.')
        , (N'USP_PurgeSnapshotData',N'purge expired snapshot data','en',95,N'Retentiongebundener Snapshot-Purge.')
        , (N'USP_FrameworkUsageFromQueryStore',N'Nutzung Statistik welche Procedures aufgerufen Query Store','de',100,N'Zeigt welche Framework-Procedures tatsächlich genutzt werden.')
        , (N'USP_FrameworkUsageFromQueryStore',N'framework usage statistics query store procedure frequency','en',95,N'Framework self-awareness from Query Store data.')
        , (N'USP_FrameworkUsageFromQueryStore',N'meistgenutzt ungenutzt Häufigkeit Laufzeit','de',90,N'Identifiziert viel- und nie-genutzte Module.')
    ) AS [v]([ProcedureName],[SearchTerm],[LanguageCode],[SearchWeight],[MatchReason]);
GO
