USE [DeineDatenbank];
GO

/*
===============================================================================
Objekt       : monitor.VW_FrameworkFeatureCatalog
Version      : 1.7.0
Stand        : 2026-07-14
Typ          : View
Zweck        : Stellt den deklarativen Katalog prüfbarer Monitoring-
               Datenquellen und Framework-Funktionsklassen für SQL Server 2019
               und neuer bereit.
Parameter    : Keine.
Resultset    : Feature-, Versions-, Berechtigungs-, Kosten- und Probe-Metadaten.
Berechtigung : SELECT auf der View. Die genannten Berechtigungen sind Hinweise;
               das Framework führt niemals GRANT, DENY oder REVOKE aus.
Sicherheit   : ProbeSqlTemplate enthält ausschließlich statische Framework-
               Definitionen. Der Datenbank-Platzhalter wird in der Prüf-USP mit QUOTENAME ersetzt.
Eigenlast    : Die View selbst ist konstant. Die Probe-Statements verwenden TOP(0)
               beziehungsweise reine Statusabfragen und führen keine Deep-Scans aus.
Aufruf       : SELECT * FROM monitor.VW_FrameworkFeatureCatalog;
Änderungen   : 1.7.0 - Maschinenlesbare PermissionCheckType-/PermissionName-Spalten ergänzt; freie Hinweistexte werden nur noch per Probe geprüft.
               1.6.0 - Phase-6-Quellen für Agent, Resource Governor, HA/DR, Backup, Replication, CDC und Change Tracking ergänzt.
               1.5.0 - Extended-Events-Katalog, Targetruntime, Filezugriff, Deadlocks und Blocked-Process-Reports differenziert.
               1.4.0 - Query-Store-Status, Runtime, Waits, Pläne, Forced Plans und SQL-2022-Hints getrennt katalogisiert.
               1.3.0 - Plan-Cache-, Planattribut-, Showplan-, Last-Actual- und Live-Plan-Capabilities präzisiert.
               1.2.0 - Index Operational Stats und In-Memory-OLTP-Indexnutzung ergänzt.
               1.1.0 - Phase-2-Objekt-, Statistik-, Partitions- und Columnstore-Quellen ergänzt.
               1.0.0 - Erstfassung Phase 1A.
===============================================================================
*/
CREATE OR ALTER VIEW [monitor].[VW_FrameworkFeatureCatalog]
AS
    SELECT
        [f].[FeatureOrdinal],
        [f].[FeatureCode],
        [f].[FeatureName],
        [f].[ScopeType],
        [f].[AnalysisClass],
        [f].[AnalysisLevel],
        [f].[IsResourceIntensive],
        [f].[MinimumMajorVersion],
        [f].[PermissionScopeBeforeSql2022],
        [f].[PermissionScopeFromSql2022],
        [f].[PermissionBeforeSql2022],
        [f].[PermissionFromSql2022],
        CAST(CASE WHEN [f].[PermissionBeforeSql2022] IN
          (N'VIEW SERVER STATE',N'VIEW SERVER PERFORMANCE STATE',N'VIEW DATABASE STATE',N'VIEW DATABASE PERFORMANCE STATE',N'VIEW ANY DEFINITION',N'VIEW ANY DATABASE',N'VIEW DEFINITION')
          THEN 'HAS_PERMS_BY_NAME' ELSE 'PROBE_ONLY' END AS varchar(24)) AS [PermissionCheckTypeBeforeSql2022],
        CAST(CASE WHEN [f].[PermissionBeforeSql2022] IN
          (N'VIEW SERVER STATE',N'VIEW SERVER PERFORMANCE STATE',N'VIEW DATABASE STATE',N'VIEW DATABASE PERFORMANCE STATE',N'VIEW ANY DEFINITION',N'VIEW ANY DATABASE',N'VIEW DEFINITION')
          THEN [f].[PermissionBeforeSql2022] END AS sysname) AS [PermissionNameBeforeSql2022],
        [f].[PermissionBeforeSql2022] AS [PermissionDisplayTextBeforeSql2022],
        CAST(CASE WHEN [f].[PermissionFromSql2022] IN
          (N'VIEW SERVER STATE',N'VIEW SERVER PERFORMANCE STATE',N'VIEW DATABASE STATE',N'VIEW DATABASE PERFORMANCE STATE',N'VIEW ANY DEFINITION',N'VIEW ANY DATABASE',N'VIEW DEFINITION')
          THEN 'HAS_PERMS_BY_NAME' ELSE 'PROBE_ONLY' END AS varchar(24)) AS [PermissionCheckTypeFromSql2022],
        CAST(CASE WHEN [f].[PermissionFromSql2022] IN
          (N'VIEW SERVER STATE',N'VIEW SERVER PERFORMANCE STATE',N'VIEW DATABASE STATE',N'VIEW DATABASE PERFORMANCE STATE',N'VIEW ANY DEFINITION',N'VIEW ANY DATABASE',N'VIEW DEFINITION')
          THEN [f].[PermissionFromSql2022] END AS sysname) AS [PermissionNameFromSql2022],
        [f].[PermissionFromSql2022] AS [PermissionDisplayTextFromSql2022],
        [f].[ExpectedWithoutPermission],
        [f].[ProbeSqlTemplate],
        [f].[EnablementSqlTemplate],
        [f].[Description]
    FROM
    (
        VALUES
          (CAST(10 AS smallint), CAST('CURRENT_SESSIONS' AS varchar(64)), CAST(N'Aktuelle Sessions' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [session_id] FROM sys.dm_exec_sessions WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Sessions; ohne Server-State-Recht typischerweise nur eingeschränkte Sicht.' AS nvarchar(1000))),
          (CAST(20 AS smallint), CAST('CURRENT_REQUESTS' AS varchar(64)), CAST(N'Aktuelle Requests' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [session_id] FROM sys.dm_exec_requests WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktive Requests und Current-State-Ausführungsinformationen.' AS nvarchar(1000))),
          (CAST(30 AS smallint), CAST('CURRENT_CONNECTIONS' AS varchar(64)), CAST(N'Aktuelle Connections' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [session_id] FROM sys.dm_exec_connections WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Connection-, Netzwerk- und Transportinformationen.' AS nvarchar(1000))),
          (CAST(40 AS smallint), CAST('WAITING_TASKS' AS varchar(64)), CAST(N'Aktuell wartende Tasks' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [session_id] FROM sys.dm_os_waiting_tasks WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Current Waits und Ressourcenwartebeziehungen.' AS nvarchar(1000))),
          (CAST(50 AS smallint), CAST('CURRENT_LOCKS' AS varchar(64)), CAST(N'Aktuelle Locks' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [request_session_id] FROM sys.dm_tran_locks WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktuelle Lockressourcen; keine historische Deadlockquelle.' AS nvarchar(1000))),
          (CAST(60 AS smallint), CAST('ACTIVE_TRANSACTIONS' AS varchar(64)), CAST(N'Aktive Transaktionen' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [at].[transaction_id] FROM sys.dm_tran_active_transactions AS [at] WITH (NOLOCK) LEFT JOIN sys.dm_tran_session_transactions AS [st] WITH (NOLOCK) ON [st].[transaction_id] = [at].[transaction_id];' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktive Transaktionen und Sessionzuordnung.' AS nvarchar(1000))),
          (CAST(70 AS smallint), CAST('MEMORY_GRANTS' AS varchar(64)), CAST(N'Query Memory Grants' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [session_id] FROM sys.dm_exec_query_memory_grants WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktuelle und wartende Query Memory Grants.' AS nvarchar(1000))),
          (CAST(80 AS smallint), CAST('WAIT_STATS' AS varchar(64)), CAST(N'Kumulative Wait Statistics' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [wait_type] FROM sys.dm_os_wait_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Kumulative Server-Waits seit Start oder Reset; Current-State-Ausgabe ohne Framework-Aufbewahrung.' AS nvarchar(1000))),
          (CAST(90 AS smallint), CAST('SCHEDULERS' AS varchar(64)), CAST(N'Schedulerstatus' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [scheduler_id] FROM sys.dm_os_schedulers WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Scheduler, Runnable Queue und CPU-Druckindikatoren.' AS nvarchar(1000))),
          (CAST(100 AS smallint), CAST('SERVER_MEMORY' AS varchar(64)), CAST(N'Server- und Prozessspeicher' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [physical_memory_in_use_kb] FROM sys.dm_os_process_memory WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'SQL-Server-Prozessspeicher und Memory Pressure.' AS nvarchar(1000))),
          (CAST(110 AS smallint), CAST('FILE_IO' AS varchar(64)), CAST(N'Virtuelle Dateistatistik' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [database_id] FROM sys.dm_io_virtual_file_stats(NULL, NULL);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Kumulative I/O-Zähler je Datenbankdatei.' AS nvarchar(1000))),
          (CAST(120 AS smallint), CAST('QUERY_STATS' AS varchar(64)), CAST(N'Kumulative Query Stats' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('PLAN_CACHE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [sql_handle] FROM sys.dm_exec_query_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Plan-Cache-basierte kumulative Query-Statistiken; vollständige Scans werden separat begrenzt.' AS nvarchar(1000))),
          (CAST(130 AS smallint), CAST('PLAN_CACHE' AS varchar(64)), CAST(N'Plan Cache' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('PLAN_CACHE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [plan_handle] FROM sys.dm_exec_cached_plans WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Gecachte Pläne; die Capability-Probe führt keinen breiten Scan aus.' AS nvarchar(1000))),
          (CAST(135 AS smallint), CAST('PLAN_ATTRIBUTES' AS varchar(64)), CAST(N'Planattribute' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('PLAN_CACHE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [attribute] FROM sys.dm_exec_cached_plans AS [cp] WITH (NOLOCK) OUTER APPLY sys.dm_exec_plan_attributes([cp].[plan_handle]) AS [pa];' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Gezielte Auflösung von dbid, set_options, user_id und weiteren Cache-Key-Attributen.' AS nvarchar(1000))),
          (CAST(136 AS smallint), CAST('PLAN_CACHE_DEEP_SCAN' AS varchar(64)), CAST(N'Breiter Plan-Cache-Scan' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('PLAN_CACHE_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [plan_handle] FROM sys.dm_exec_cached_plans WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Explizite breite Query-Stats-, Single-use-, Datenbankverteilungs- und Cacheanalyse.' AS nvarchar(1000))),
          (CAST(137 AS smallint), CAST('TEXT_QUERY_PLAN' AS varchar(64)), CAST(N'Text-Showplan' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SHOWPLAN_TARGETED' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [query_plan] FROM sys.dm_exec_text_query_plan(0x0,0,-1);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Textausgabe ist nicht durch die XML-Nesting-Grenze beschränkt und unterstützt Statement-Offets.' AS nvarchar(1000))),
          (CAST(138 AS smallint), CAST('LAST_QUERY_PLAN_STATS' AS varchar(64)), CAST(N'Last Actual Query Plan' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('SHOWPLAN_TARGETED' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [query_plan] FROM sys.dm_exec_query_plan_stats(0x0);' AS nvarchar(2000)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT @IsEnabledOut=CONVERT(bit,COALESCE(MAX(CASE WHEN [name]=N''LAST_QUERY_PLAN_STATS'' AND [value]=1 THEN 1 ELSE 0 END),0)) FROM sys.database_scoped_configurations WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'Opt-in Last-Actual-Plan-Quelle ab SQL Server 2019; das Framework aktiviert die Option nicht.' AS nvarchar(1000))),
          (CAST(139 AS smallint), CAST('LIVE_QUERY_PLAN' AS varchar(64)), CAST(N'Live Query Plan' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SHOWPLAN_TARGETED' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [query_plan] FROM sys.dm_exec_query_statistics_xml(@@SPID);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Gezielter transienter Runtime-Showplan eines aktiven Requests; keine Historie.' AS nvarchar(1000))),
          (CAST(140 AS smallint), CAST('SHOWPLAN_XML' AS varchar(64)), CAST(N'Gezieltes Showplan-XML aus dem Cache' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SHOWPLAN_TARGETED' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [qp].[query_plan] FROM sys.dm_exec_query_stats AS [qs] WITH (NOLOCK) OUTER APPLY sys.dm_exec_text_query_plan([qs].[plan_handle], [qs].[statement_start_offset], [qs].[statement_end_offset]) AS [qp];' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Gecachte Text-Showplans; XML-Shredding erfolgt erst nach Kandidatenselektion.' AS nvarchar(1000))),
          (CAST(145 AS smallint), CAST('SHOWPLAN_XML_DEEP_SCAN' AS varchar(64)), CAST(N'Breites Showplan-XML-Shredding' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SHOWPLAN_XML_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [query_plan] FROM sys.dm_exec_query_plan(0x0);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Explizite planweise XML-Analyse nach Kandidatenselektion, mit Zeit- und Zeilenbudget.' AS nvarchar(1000))),
          (CAST(150 AS smallint), CAST('TEMPDB_TASK_SPACE' AS varchar(64)), CAST(N'TempDB Task- und Sessionverbrauch' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'USE [tempdb]; SELECT TOP (0) [session_id] FROM sys.dm_db_session_space_usage WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktueller TempDB-Verbrauch je Session und Task.' AS nvarchar(1000))),
          (CAST(160 AS smallint), CAST('DATABASE_FILE_SPACE' AS varchar(64)), CAST(N'Datenbank-Dateiraum' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('STANDARD_CURRENT' AS varchar(64)), CAST('STANDARD' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [file_id] FROM sys.dm_db_file_space_usage WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktueller Dateiraum der gewählten Datenbank.' AS nvarchar(1000))),
          (CAST(170 AS smallint), CAST('INDEX_USAGE' AS varchar(64)), CAST(N'Index Usage Statistics' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('OBJECT_ANALYSIS_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [database_id] FROM sys.dm_db_index_usage_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Kumulative Indexnutzung; Reset bei Neustart, Detach oder Datenbankereignissen beachten.' AS nvarchar(1000))),
          (CAST(175 AS smallint), CAST('XTP_INDEX_USAGE' AS varchar(64)), CAST(N'In-Memory-OLTP Index Usage' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('OBJECT_ANALYSIS_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [object_id] FROM sys.dm_db_xtp_index_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'In-Memory-OLTP-Scans, Retries und berührte beziehungsweise gelieferte Zeilen.' AS nvarchar(1000))),
          (CAST(180 AS smallint), CAST('INDEX_PHYSICAL_STATS' AS varchar(64)), CAST(N'Index Physical Stats' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('PHYSICAL_STATS_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [database_id] FROM sys.dm_db_index_physical_stats(DB_ID(), NULL, NULL, NULL, ''LIMITED'');' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Physische Indexstatistik. Die Probe verwendet TOP(0); echte Scans sind immer explizit und gruppengeschützt.' AS nvarchar(1000))),
          (CAST(185 AS smallint), CAST('INDEX_OPERATIONAL_STATS' AS varchar(64)), CAST(N'Index Operational Stats' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('INDEX_OPERATIONAL_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [database_id] FROM sys.dm_db_index_operational_stats(DB_ID(), NULL, NULL, NULL);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Kumulative Zugriffs-, Lock-, Latch-, I/O-Latch-, Page-Split- und Eskalationszähler; breite Auswertung ist gruppengeschützt.' AS nvarchar(1000))),
          (CAST(190 AS smallint), CAST('COLUMNSTORE_ROWGROUPS' AS varchar(64)), CAST(N'Columnstore Rowgroup Physical Stats' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('COLUMNSTORE_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [object_id] FROM sys.dm_db_column_store_row_group_physical_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Rowgroups, aktive und gelöschte Zeilen sowie Kompressionszustände; SQL Server 2019 benötigt für die Vollsicht VIEW DATABASE STATE oder alternativ passende CONTROL-Rechte auf Tabellen.' AS nvarchar(1000))),
          (CAST(200 AS smallint), CAST('QUERY_STORE_STATUS' AS varchar(64)), CAST(N'Query Store Status und Optionen' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('QUERY_STORE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [actual_state] FROM sys.database_query_store_options WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT @IsEnabledOut = CASE WHEN [actual_state] IN (1,2,4) THEN 1 ELSE 0 END FROM sys.database_query_store_options WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'Aktueller Query-Store-Zustand und Konfiguration; ausschließlich lesend.' AS nvarchar(1000))),
          (CAST(201 AS smallint), CAST('QUERY_STORE_RUNTIME' AS varchar(64)), CAST(N'Query Store Runtime Statistics' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('QUERY_STORE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [plan_id] FROM sys.query_store_runtime_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT @IsEnabledOut = CASE WHEN [actual_state] IN (1,2,4) THEN 1 ELSE 0 END FROM sys.database_query_store_options WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'Historische Ausführungsaggregate; aktive Intervalle können mehrere Zeilen enthalten und werden verdichtet.' AS nvarchar(1000))),
          (CAST(202 AS smallint), CAST('QUERY_STORE_WAITS' AS varchar(64)), CAST(N'Query Store Wait Statistics' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('QUERY_STORE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [plan_id] FROM sys.query_store_wait_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT @IsEnabledOut = CONVERT(bit,[wait_stats_capture_mode]) FROM sys.database_query_store_options WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'Historische Wait-Kategorien pro Query und Plan, sofern Wait-Stats-Capture aktiviert ist.' AS nvarchar(1000))),
          (CAST(203 AS smallint), CAST('QUERY_STORE_PLANS' AS varchar(64)), CAST(N'Query Store Plans und Force-Status' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('QUERY_STORE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [plan_id] FROM sys.query_store_plan WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT @IsEnabledOut = CASE WHEN [actual_state] IN (1,2,4) THEN 1 ELSE 0 END FROM sys.database_query_store_options WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'Planwechsel, Compile-Metadaten, Forced Plans und Force-Fehler; keine Änderungen.' AS nvarchar(1000))),
          (CAST(204 AS smallint), CAST('QUERY_STORE_HINTS' AS varchar(64)), CAST(N'Query Store Hints' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('QUERY_STORE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(16 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [query_hint_id] FROM sys.query_store_query_hints WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Nur SQL Server 2022+; ausschließlich lesende Hint- und Fehlerdiagnose.' AS nvarchar(1000))),
          (CAST(205 AS smallint), CAST('QUERY_STORE_DEEP_SCAN' AS varchar(64)), CAST(N'Breite Query Store Analyse' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('QUERY_STORE_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [query_id] FROM sys.query_store_query WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT @IsEnabledOut = CASE WHEN [actual_state] IN (1,2,4) THEN 1 ELSE 0 END FROM sys.database_query_store_options WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'Breite Zeitfenster, große Ergebnismengen und Query-Store-Plan-XML; gruppengeschützt.' AS nvarchar(1000))),
          (CAST(210 AS smallint), CAST('LOG_STATS' AS varchar(64)), CAST(N'Datenbank-Logstatistik' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('EXTENDED_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [database_id] FROM sys.dm_db_log_stats(DB_ID());' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Loggröße, aktive Loganteile, VLF- und Truncation-Grundinformationen.' AS nvarchar(1000))),
          (CAST(220 AS smallint), CAST('LOG_INFO' AS varchar(64)), CAST(N'Virtual Log File Information' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('EXTENDED_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [database_id] FROM sys.dm_db_log_info(DB_ID());' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'VLF-Informationen der gewählten Datenbank.' AS nvarchar(1000))),
          (CAST(230 AS smallint), CAST('ADR_PVS' AS varchar(64)), CAST(N'ADR Persistent Version Store' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('EXTENDED_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [database_id] FROM sys.dm_tran_persistent_version_store_stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'SELECT @IsEnabledOut = CONVERT(bit, [is_accelerated_database_recovery_on]) FROM sys.databases WITH (NOLOCK) WHERE [name] = N''' + N'$' + N'(DATABASENAME)'';' AS nvarchar(2000)), CAST(N'Persistent Version Store bei Accelerated Database Recovery.' AS nvarchar(1000))),
          (CAST(240 AS smallint), CAST('AVAILABILITY_GROUPS' AS varchar(64)), CAST(N'Always On Availability Groups' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [group_id] FROM sys.dm_hadr_availability_group_states WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'SELECT @IsEnabledOut = CONVERT(bit, SERVERPROPERTY(N''IsHadrEnabled''));' AS nvarchar(2000)), CAST(N'Availability-Group-Zustand, sofern HADR aktiviert ist.' AS nvarchar(1000))),
          (CAST(250 AS smallint), CAST('EXTENDED_EVENTS_SESSION_CATALOG' AS varchar(64)), CAST(N'Extended-Events-Sessiondefinitionen' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [name] FROM sys.server_event_sessions WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Leichte Definitionsermittlung ohne Lesen von Targetdaten oder Ereignisdateien.' AS nvarchar(1000))),
          (CAST(251 AS smallint), CAST('EXTENDED_EVENTS_SESSION_RUNTIME' AS varchar(64)), CAST(N'Laufende Extended-Events-Sessions' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [name] FROM sys.dm_xe_sessions WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Laufzeitstatus ohne Targetdaten; keine Sessionänderung.' AS nvarchar(1000))),
          (CAST(252 AS smallint), CAST('EXTENDED_EVENTS_TARGET_RUNTIME' AS varchar(64)), CAST(N'Extended-Events-Targetlaufzeit' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_FORENSICS_DEEP' AS varchar(64)), CAST('FORENSIK' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [target_name] FROM sys.dm_xe_session_targets WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Der Zugriff kann einen Target-Flush auslösen und ist daher explizit gruppengeschützt.' AS nvarchar(1000))),
          (CAST(253 AS smallint), CAST('EXTENDED_EVENTS_FILE_READER' AS varchar(64)), CAST(N'Extended-Events-XEL-Dateileser' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_FORENSICS_DEEP' AS varchar(64)), CAST('FORENSIK' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [name] FROM sys.system_objects WITH (NOLOCK) WHERE [name]=N''fn_xe_file_target_read_file'';' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Das tatsächliche Lesen benötigt zusätzlich einen erreichbaren Pfad und Dateizugriff des SQL-Server-Dienstkontos.' AS nvarchar(1000))),
          (CAST(254 AS smallint), CAST('SYSTEM_HEALTH_XE' AS varchar(64)), CAST(N'system_health Extended Events' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_FORENSICS_DEEP' AS varchar(64)), CAST('FORENSIK' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR' AS varchar(32)), CAST(N'SELECT TOP (0) [s].[name] FROM sys.server_event_sessions AS [s] WITH (NOLOCK) WHERE [s].[name]=N''system_health'';' AS nvarchar(2000)), CAST(N'SELECT @IsEnabledOut=CASE WHEN EXISTS(SELECT 1 FROM sys.dm_xe_sessions WITH (NOLOCK) WHERE [name]=N''system_health'') THEN 1 ELSE 0 END;' AS nvarchar(2000)), CAST(N'Optionale system_health-Quelle; das Framework stoppt oder verändert sie niemals.' AS nvarchar(1000))),
          (CAST(255 AS smallint), CAST('EXTENDED_EVENTS_DEADLOCKS' AS varchar(64)), CAST(N'Extended-Events-Deadlockgraphen' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_FORENSICS_DEEP' AS varchar(64)), CAST('FORENSIK' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [e].[name] FROM sys.server_event_session_events AS [e] WITH (NOLOCK) WHERE [e].[name]=N''xml_deadlock_report'';' AS nvarchar(2000)), CAST(N'SELECT @IsEnabledOut=CASE WHEN EXISTS(SELECT 1 FROM sys.server_event_session_events WITH (NOLOCK) WHERE [name]=N''xml_deadlock_report'') THEN 1 ELSE 0 END;' AS nvarchar(2000)), CAST(N'Bereits erfasste Deadlockgraphen aus vorhandenen Targets; keine separate Session erforderlich, sofern system_health verfügbar ist.' AS nvarchar(1000))),
          (CAST(256 AS smallint), CAST('EXTENDED_EVENTS_BLOCKED_PROCESS' AS varchar(64)), CAST(N'Extended-Events-Blocked-Process-Reports' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('EXTENDED_EVENTS_FORENSICS_DEEP' AS varchar(64)), CAST('FORENSIK' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [e].[name] FROM sys.server_event_session_events AS [e] WITH (NOLOCK) WHERE [e].[name]=N''blocked_process_report'';' AS nvarchar(2000)), CAST(N'SELECT @IsEnabledOut=CASE WHEN EXISTS(SELECT 1 FROM sys.server_event_session_events WITH (NOLOCK) WHERE [name]=N''blocked_process_report'') THEN 1 ELSE 0 END;' AS nvarchar(2000)), CAST(N'Nur vorhanden, wenn Threshold und erfassende Session außerhalb des Frameworks konfiguriert wurden.' AS nvarchar(1000))),
          (CAST(280 AS smallint), CAST('OBJECT_CATALOG' AS varchar(64)), CAST(N'Objekt- und Indexkatalog' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('OBJECT_ANALYSIS_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [object_id] FROM sys.objects WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Objekte, Indizes, Indexspalten und Metadaten; Ergebnis gemäß Metadata Visibility.' AS nvarchar(1000))),
          (CAST(290 AS smallint), CAST('PARTITION_CATALOG' AS varchar(64)), CAST(N'Partitionen und Kompression' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('OBJECT_ANALYSIS_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [partition_id] FROM sys.partitions WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Partitionen, Allocation Units, Filegroups und Kompressionszustände.' AS nvarchar(1000))),
          (CAST(300 AS smallint), CAST('MISSING_INDEXES' AS varchar(64)), CAST(N'Missing Index DMVs' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('MISSING_INDEX_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [index_handle] FROM sys.dm_db_missing_index_details WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Flüchtige Missing-Index-Hinweise; keine vollständige oder direkte Wartungsempfehlung.' AS nvarchar(1000))),
          (CAST(310 AS smallint), CAST('STATS_PROPERTIES' AS varchar(64)), CAST(N'Statistik-Eigenschaften' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('STATISTICS_TARGETED' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(NULL AS nvarchar(128)), CAST(NULL AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [object_id] FROM sys.stats WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'sys.dm_db_stats_properties liefert bei fehlender Sichtbarkeit möglicherweise keine Zeile statt eines Fehlers.' AS nvarchar(1000))),
          (CAST(320 AS smallint), CAST('COLUMNSTORE_CATALOG' AS varchar(64)), CAST(N'Columnstore Rowgroups' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('COLUMNSTORE_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [object_id] FROM sys.column_store_row_groups WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Basis-Rowgroupinformationen gemäß Metadata Visibility.' AS nvarchar(1000))),
          (CAST(330 AS smallint), CAST('COLUMNSTORE_SEGMENTS' AS varchar(64)), CAST(N'Columnstore Segmente' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('COLUMNSTORE_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [partition_id] FROM sys.column_store_segments WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Eine Zeile je Spalte und Rowgroup; potenziell große Ergebnismenge.' AS nvarchar(1000))),
          (CAST(340 AS smallint), CAST('COLUMNSTORE_DICTIONARIES' AS varchar(64)), CAST(N'Columnstore Dictionaries' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('COLUMNSTORE_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST(N'VIEW DEFINITION' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [partition_id] FROM sys.column_store_dictionaries WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Dictionary-Metadaten; einzelne Detailspalten können ohne SELECT NULL sein.' AS nvarchar(1000))),
          (CAST(264 AS smallint), CAST('SERVER_CPU_TOPOLOGY' AS varchar(64)), CAST(N'CPU- und Scheduler-Topologie' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_HEALTH_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'sys.dm_os_sys_info und Scheduler/Nodes' AS nvarchar(1000))),
          (CAST(265 AS smallint), CAST('SERVER_NUMA' AS varchar(64)), CAST(N'NUMA und Soft-NUMA' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_HEALTH_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'NUMA-, Memory-Node- und Scheduler-Verteilung' AS nvarchar(1000))),
          (CAST(266 AS smallint), CAST('SERVER_MEMORY' AS varchar(64)), CAST(N'Server- und Prozessspeicher' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_HEALTH_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Memory Clerks, Prozessspeicher und Query Grants' AS nvarchar(1000))),
          (CAST(267 AS smallint), CAST('TEMPDB_CONFIGURATION' AS varchar(64)), CAST(N'TempDB-Konfiguration' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_HEALTH_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Dateien, Größenverteilung und Autogrowth' AS nvarchar(1000))),
          (CAST(268 AS smallint), CAST('SERVER_CONFIGURATION' AS varchar(64)), CAST(N'SQL-Server-Konfiguration' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_CONFIGURATION_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Konfigurierte und aktive sys.configurations-Werte' AS nvarchar(1000))),
          (CAST(269 AS smallint), CAST('TRACE_FLAGS' AS varchar(64)), CAST(N'Trace Flags' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_CONFIGURATION_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Aktive globale und Session-Trace-Flags' AS nvarchar(1000))),
          (CAST(271 AS smallint), CAST('STARTUP_PARAMETERS' AS varchar(64)), CAST(N'Startup-Parameter' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_CONFIGURATION_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Startparameter aus sys.dm_server_registry' AS nvarchar(1000))),
          (CAST(272 AS smallint), CAST('OS_INFORMATION' AS varchar(64)), CAST(N'Betriebssysteminformationen' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SERVER_HEALTH_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Host-, Speicher-, Prozess- und Dienstinformationen' AS nvarchar(1000))),
          (CAST(273 AS smallint), CAST('SECURITY_CONFIGURATION' AS varchar(64)), CAST(N'Security-Konfiguration' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SECURITY_CONFIGURATION_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [cpu_count] FROM sys.dm_os_sys_info WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Sicherheits- und dienstbezogene Betriebsparameter' AS nvarchar(1000))),
          (CAST(257 AS smallint), CAST('SQL_AGENT_MSDB' AS varchar(64)), CAST(N'SQL Server Agent msdb' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('SQL_AGENT_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'SQLAgentReaderRole oder geeignete msdb-Rechte' AS nvarchar(128)), CAST(N'SQLAgentReaderRole oder geeignete msdb-Rechte' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [job_id] FROM msdb.dbo.sysjobs WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Agent-Jobs, Schedules, Jobactivity und Historie; keine Jobsteuerung.' AS nvarchar(1000))),
          (CAST(258 AS smallint), CAST('RESOURCE_GOVERNOR' AS varchar(64)), CAST(N'Resource Governor' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('RESOURCE_GOVERNOR_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [pool_id] FROM sys.dm_resource_governor_resource_pools WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Konfiguration und kumulative Laufzeitkennzahlen; keine Reconfiguration.' AS nvarchar(1000))),
          (CAST(259 AS smallint), CAST('AVAILABILITY_GROUPS' AS varchar(64)), CAST(N'Availability Groups' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('HA_DR_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW SERVER STATE' AS nvarchar(128)), CAST(N'VIEW SERVER PERFORMANCE STATE' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [group_id] FROM sys.availability_groups WITH (NOLOCK);' AS nvarchar(2000)), CAST(N'SELECT @IsEnabledOut=CONVERT(bit,SERVERPROPERTY(''IsHadrEnabled''));' AS nvarchar(2000)), CAST(N'Replikate, Datenbanken, Queues, Lag, Listener und Read-only Routing.' AS nvarchar(1000))),
          (CAST(260 AS smallint), CAST('BACKUP_HISTORY' AS varchar(64)), CAST(N'Backup- und Restore-Historie' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('HA_DR_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'Leserechte in msdb' AS nvarchar(128)), CAST(N'Leserechte in msdb' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [backup_set_id] FROM msdb.dbo.backupset WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Backup-Aktualität, Medien und Restore-Historie.' AS nvarchar(1000))),
          (CAST(261 AS smallint), CAST('LOG_SHIPPING' AS varchar(64)), CAST(N'Log Shipping' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('HA_DR_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'Leserechte in msdb' AS nvarchar(128)), CAST(N'Leserechte in msdb' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [primary_id] FROM msdb.dbo.log_shipping_primary_databases WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Primary-/Secondary-Monitorzustand und Zeitabstände.' AS nvarchar(1000))),
          (CAST(262 AS smallint), CAST('REPLICATION' AS varchar(64)), CAST(N'SQL Server Replication' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('ENTERPRISE_TOPOLOGY_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'Geeignete Replication-/Distribution-Leserechte' AS nvarchar(128)), CAST(N'Geeignete Replication-/Distribution-Leserechte' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [name] FROM sys.databases WITH (NOLOCK) WHERE [is_distributor]=1;' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Publikationen, Subscriptions, Agents und Fehler; Distribution-Details explizit opt-in.' AS nvarchar(1000))),
          (CAST(263 AS smallint), CAST('CDC_CHANGE_TRACKING' AS varchar(64)), CAST(N'CDC und Change Tracking' AS nvarchar(200)), CAST('DATABASE' AS varchar(16)), CAST('HA_DR_CURRENT' AS varchar(64)), CAST('ERWEITERT' AS varchar(16)), CAST(0 AS bit), CAST(15 AS tinyint), CAST('DATABASE' AS varchar(16)), CAST('DATABASE' AS varchar(16)), CAST(N'VIEW DATABASE STATE/VIEW DEFINITION' AS nvarchar(128)), CAST(N'VIEW DATABASE PERFORMANCE STATE/VIEW DEFINITION' AS nvarchar(128)), CAST('ERROR_OR_LIMITED' AS varchar(32)), CAST(N'USE ' + N'$' + N'(DATABASE); SELECT TOP (0) [object_id] FROM sys.change_tracking_tables WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Datenbank- und Tabellenstatus von CDC und Change Tracking.' AS nvarchar(1000))),
          (CAST(270 AS smallint), CAST('CROSS_DATABASE_CATALOG' AS varchar(64)), CAST(N'Datenbankübergreifender Katalogzugriff' AS nvarchar(200)), CAST('SERVER' AS varchar(16)), CAST('CROSS_DATABASE_DEEP' AS varchar(64)), CAST('DEEP' AS varchar(16)), CAST(1 AS bit), CAST(15 AS tinyint), CAST('SERVER' AS varchar(16)), CAST('SERVER' AS varchar(16)), CAST(N'VIEW ANY DATABASE' AS nvarchar(128)), CAST(N'VIEW ANY DATABASE' AS nvarchar(128)), CAST('LIMITED' AS varchar(32)), CAST(N'SELECT TOP (0) [name] FROM sys.databases WITH (NOLOCK);' AS nvarchar(2000)), CAST(NULL AS nvarchar(2000)), CAST(N'Datenbankliste und Basis für explizite Cross-Database-Analysen; tatsächlicher Zugriff wird je Datenbank isoliert geprüft.' AS nvarchar(1000)))
    ) AS [f]
    (
        [FeatureOrdinal],
        [FeatureCode],
        [FeatureName],
        [ScopeType],
        [AnalysisClass],
        [AnalysisLevel],
        [IsResourceIntensive],
        [MinimumMajorVersion],
        [PermissionScopeBeforeSql2022],
        [PermissionScopeFromSql2022],
        [PermissionBeforeSql2022],
        [PermissionFromSql2022],
        [ExpectedWithoutPermission],
        [ProbeSqlTemplate],
        [EnablementSqlTemplate],
        [Description]
    );
GO
