USE [DeineDatenbank];
GO

/* Wait-Type-Katalog: kuratierter Seed-Teil 01 von 04. */
DELETE FROM [monitor].[WaitTypeCatalog]
WHERE [IsFrameworkDefault]=1
  AND [WaitType] IN
  (
      N'CURSOR',N'DBTABLE',N'IDES',N'LCK_MSCH_M',N'LCK_M_RI_NL',N'LCK_M_RI_S',N'LCK_M_RI_U',N'LCK_M_RI_X',
      N'NETWORKIO',N'PAGESUPP',N'PARALLEL_PAGE_SUPPLIER',N'PSS_CHILD',N'SLEEP',N'UMSTHREAD'
  );

DECLARE @Seed TABLE
([WaitType] nvarchar(120),[WaitGroup] nvarchar(64),[Severity] tinyint,[IsGenerallyBenign] bit,[Meaning] nvarchar(1000),
 [TypicalOccurrence] nvarchar(1200),[HighWaitImpact] nvarchar(1200),[RecommendedChecks] nvarchar(1500),
 [DescriptionSource] varchar(40),[DescriptionQuality] varchar(40));
INSERT @Seed VALUES
(N'ABR',N'OTHER_OR_NEW',2,0,N'Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'ASSEMBLY_LOAD',N'OTHER_OR_NEW',2,0,N'Occurs during exclusive access to assembly loading.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'ASYNC_DISKPOOL_LOCK',N'STORAGE_DATA_IO',2,0,N'Diesen Wartetyp sehen Sie eventuell während lange andauernder E/A-gebundener Operationen, wie z. B. dem Erstellen, Erweitern oder Löschen einer Datenbankdatei. (Occurs when there is an attempt to synchronize parallel threads that are performing tasks such as creating or initializing a file.)',N'Daten-, Metadaten- oder asynchroner Datei-I/O.',N'Hohe Delta-Werte können auf Storage-Latenz, Scans oder Buffer-Pool-Druck hinweisen.',N'sys.dm_io_virtual_file_stats, Volume, Buffer Pool, große Reads und aktive Operation korrelieren.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'ASYNC_IO_COMPLETION',N'STORAGE_DATA_IO',2,0,N'Warten auf asynchronen I/O-Abschluss.',N'Häufig bei Backup, Restore, DBCC oder größeren asynchronen I/O-Operationen.',N'Operationen benötigen länger; nicht automatisch ein OLTP-Storageproblem.',N'Mit laufender Operation, Throughput und Storage-Latenz korrelieren.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'ASYNC_NETWORK_IO',N'NETWORK_CLIENT',3,0,N'SQL Server wartet darauf, dass Client oder Netzwerk Ergebnisdaten abnimmt.',N'Große Resultsets, langsame Clientverarbeitung oder Row-by-row-Fetching.',N'Worker bleiben gebunden; Durchsatz sinkt.',N'Resultsetgröße, Client-Fetchrate, Applikationscode und Netzwerk prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'AUDIT_GROUPCACHE_LOCK',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait on a lock that controls access to a special cache. The cache contains information about which audits are being used to audit each audit action group.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'AUDIT_LOGINCACHE_LOCK',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait on a lock that controls access to a special cache. The cache contains information about which audits are being used to audit login audit action groups.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'AUDIT_ON_DEMAND_TARGET_LOCK',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait on a lock that is used to ensure single initialization of audit related Extended Event targets.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'AUDIT_XE_SESSION_MGR',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait on a lock that is used to synchronize the starting and stopping of audit related Extended Events sessions.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BACKUP',N'BACKUP_RESTORE',2,0,N'Occurs when a task is blocked as part of backup processing.',N'Backup-, Restore- oder Medienverarbeitung.',N'Operationen dauern länger; konkurrierender I/O kann beeinflusst werden.',N'Aktive Operation, Throughput, Zielmedium, Stripe und Storage prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BACKUPBUFFER',N'BACKUP_RESTORE',2,0,N'Occurs when a backup task is waiting for data, or is waiting for a buffer in which to store data. This type is not typical, except when a task is waiting for a tape mount.',N'Backup-, Restore- oder Medienverarbeitung.',N'Operationen dauern länger; konkurrierender I/O kann beeinflusst werden.',N'Aktive Operation, Throughput, Zielmedium, Stripe und Storage prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BACKUPIO',N'BACKUP_RESTORE',2,0,N'Backup wartet auf I/O im Backup-Datenpfad.',N'Backup-Ziel oder Quelldateien liefern unzureichenden Throughput.',N'Backupdauer steigt; konkurrierender I/O kann beeinflusst werden.',N'Backup-Throughput, Zielmedium, Stripe-Anzahl und Storage prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BACKUPTHREAD',N'BACKUP_RESTORE',2,0,N'Occurs when a task is waiting for a backup task to finish. Wait times may be long, from several minutes to several hours. If the task that is being waited on is in an I/O process, this type does not indicate a problem.',N'Backup-, Restore- oder Medienverarbeitung.',N'Operationen dauern länger; konkurrierender I/O kann beeinflusst werden.',N'Aktive Operation, Throughput, Zielmedium, Stripe und Storage prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BACKUP_OPERATOR',N'BACKUP_RESTORE',2,0,N'Occurs when a task is waiting for a tape mount. To view the tape status, query sys.dm_io_backup_tapes. If a mount operation is not pending, this wait type may indicate a hardware problem with the tape drive.',N'Backup-, Restore- oder Medienverarbeitung.',N'Operationen dauern länger; konkurrierender I/O kann beeinflusst werden.',N'Aktive Operation, Throughput, Zielmedium, Stripe und Storage prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BAD_PAGE_PROCESS',N'OTHER_OR_NEW',2,0,N'Occurs when the background suspect page logger is trying to avoid running more than every five seconds. Excessive suspect pages cause the logger to run frequently.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_CONNECTION_RECEIVE_TASK',N'SERVICE_BROKER',2,0,N'Occurs when waiting for access to receive a message on a connection endpoint. Receive access to the endpoint is serialized.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_ENDPOINT_STATE_MUTEX',N'SERVICE_BROKER',2,0,N'Occurs when there is contention to access the state of a Service Broker connection endpoint. Access to the state for changes is serialized.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_EVENTHANDLER',N'SERVICE_BROKER',0,1,N'Occurs when a task is waiting in the primary event handler of the Service Broker. This should occur very briefly.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_INIT',N'SERVICE_BROKER',2,0,N'Occurs when initializing Service Broker in each active database. This should occur infrequently.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_MASTERSTART',N'SERVICE_BROKER',2,0,N'Occurs when a task is waiting for the primary event handler of the Service Broker to start. This should occur very briefly.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_RECEIVE_WAITFOR',N'SERVICE_BROKER',0,1,N'Occurs when the RECEIVE WAITFOR is waiting. This is typical if no messages are ready to be received.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_REGISTERALLENDPOINTS',N'SERVICE_BROKER',2,0,N'Occurs during the initialization of a Service Broker connection endpoint. This should occur very briefly.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_SERVICE',N'SERVICE_BROKER',2,0,N'Occurs when the Service Broker destination list that is associated with a target service is updated or re-prioritized.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_SHUTDOWN',N'SERVICE_BROKER',2,0,N'Occurs when there is a planned shutdown of Service Broker. This should occur very briefly, if at all.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_TASK_STOP',N'SERVICE_BROKER',0,1,N'Occurs when the Service Broker queue task handler tries to shut down the task. The state check is serialized and must be in a running state beforehand.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_TO_FLUSH',N'SERVICE_BROKER',0,1,N'Occurs when the Service Broker lazy flusher flushes the in-memory transmission objects to a work table.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BROKER_TRANSMITTER',N'SERVICE_BROKER',0,1,N'Occurs when the Service Broker transmitter is waiting for work.',N'Service-Broker-Queue, Transport oder Hintergrundtask.',N'Idle-Queues sind erwartbar; aktive Transportprobleme können Nachrichten verzögern.',N'Benign-Flag, Transmission Queue, Endpoints und Routes prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'BUILTIN_HASHKEY_MUTEX',N'OTHER_OR_NEW',2,0,N'May occur after startup of instance, while internal data structures are initializing. Will not recur once data structures have initialized.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CHECKPOINT_QUEUE',N'BENIGN_BACKGROUND',0,1,N'Occurs while the checkpoint task is waiting for the next checkpoint request.',N'Normaler Idle-, Timer-, Queue- oder Hintergrundzustand.',N'Hohe kumulative Werte sind in der Regel erwartbar und kein Engpassbeweis.',N'Standardmäßig aus Top-Ranking ausblenden; nur bei passender Funktionsstörung untersuchen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CHECK_PRINT_RECORD',N'OTHER_OR_NEW',2,0,N'Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CHKPT',N'BENIGN_BACKGROUND',0,1,N'Occurs at server startup to tell the checkpoint thread that it can start.',N'Normaler Idle-, Timer-, Queue- oder Hintergrundzustand.',N'Hohe kumulative Werte sind in der Regel erwartbar und kein Engpassbeweis.',N'Standardmäßig aus Top-Ranking ausblenden; nur bei passender Funktionsstörung untersuchen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLEAR_DB',N'OTHER_OR_NEW',2,0,N'Occurs during operations that change the state of a database, such as opening or closing a database.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLRHOST_STATE_ACCESS',N'OTHER_OR_NEW',2,0,N'Occurs where there is a wait to acquire exclusive access to the CLR-hosting data structures. This wait type occurs while setting up or tearing down the CLR runtime.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_AUTO_EVENT',N'CLR',0,1,N'Occurs when a task is currently performing common language runtime (CLR) execution and is waiting for a particular autoevent to be initiated. Long waits are typical, and do not indicate a problem.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_CRST',N'CLR',2,0,N'Occurs when a task is currently performing CLR execution and is waiting to enter a critical section of the task that is currently being used by another task.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_JOIN',N'CLR',2,0,N'Occurs when a task is currently performing CLR execution and waiting for another task to end. This wait state occurs when there is a join between tasks.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_MANUAL_EVENT',N'CLR',0,1,N'Occurs when a task is currently performing CLR execution and is waiting for a specific manual event to be initiated.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_MEMORY_SPY',N'MEMORY',2,0,N'Occurs during a wait on lock acquisition for a data structure that is used to record all virtual memory allocations that come from CLR. The data structure is locked to maintain its integrity if there is parallel access.',N'Speicherzuteilung, Memory Grants oder interne Memory-Manager.',N'Hohe Werte verzögern Start oder Ausführung von Abfragen.',N'Pending Grants, Grantgrößen, Cardinality, Spills und max server memory prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_MONITOR',N'CLR',2,0,N'Occurs when a task is currently performing CLR execution and is waiting to obtain a lock on the monitor.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_RWLOCK_READER',N'CLR',2,0,N'Occurs when a task is currently performing CLR execution and is waiting for a reader lock.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_RWLOCK_WRITER',N'CLR',2,0,N'Occurs when a task is currently performing CLR execution and is waiting for a writer lock.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_SEMAPHORE',N'CLR',0,1,N'Occurs when a task is currently performing CLR execution and is waiting for a semaphore.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CLR_TASK_START',N'CLR',2,0,N'Occurs while waiting for a CLR task to complete startup.',N'CLR-Ausführung oder CLR-Hintergrundsynchronisation.',N'Hohe aktive Werte können CLR-Aufrufe verzögern.',N'CLR-Workload, AppDomain, externe Abhängigkeiten und Benign-Flag prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CMEMTHREAD',N'INTERNAL_SYNCHRONIZATION',2,0,N'Dieser Wartetyp deutet darauf hin, dass die SPID auf Zugang zu einem Thread-sicheren Speicherobjekt wartet. Durch die Serialisierung wird sichergestellt, dass während der Zuordnung oder Freigabe von Speicher des Speicherobjekts durch den Benutzer alle anderen SPIDs, die die gleiche Task ausführen wollen, warten müssen. Außerdem gewährleistet die Serialisierung, dass der Wartetyp CMEMTHREAD gesetzt wird, wenn die SPIDs warten.',N'Interne Synchronisation von Speicher- oder Engine-Strukturen.',N'Hohe Delta-Werte können auf interne Hotspots oder Workload-Skalierungsgrenzen hinweisen.',N'Konkrete Wait-Detailseite, Spinlocks/Latches, Plan Cache und Workload-Korrelation prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'COLUMNSTORE_BUILD_THROTTLE',N'OTHER_OR_NEW',2,0,N'This wait type is when parallel threads for a columnstore index build operation are waiting for the first segment of the index to be built single-threaded.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CXCONSUMER',N'PARALLELISM',1,1,N'Konsumentenwait in einem parallelen Plan.',N'Normaler Bestandteil paralleler Ausführung; meist zusammen mit CXPACKET bewerten.',N'Allein häufig unkritisch; hohe Gesamtdauer kann auf Planprobleme hinweisen.',N'Nicht isoliert optimieren; Plan, CPU und verwandte Parallelism-Waits prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CXPACKET',N'PARALLELISM',2,0,N'Synchronisation zwischen parallelen Ausführungszweigen.',N'Parallele Pläne; relevant bei Skew, hoher CPU oder ineffizienten Plänen.',N'Kann Symptom unausgeglichener paralleler Arbeit sein.',N'Plan, Row Skew, CPU, MAXDOP und Cost Threshold prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'CXROWSET_SYNC',N'PARALLELISM',2,0,N'Occurs during a parallel range scan.',N'Synchronisation paralleler Ausführungszweige.',N'Hohe Werte können auf Skew, langsame Zweige oder ungeeignete Parallelität hinweisen.',N'Plan, Row Skew, Spills, CPU, MAXDOP und Cost Threshold prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DAC_INIT',N'OTHER_OR_NEW',2,0,N'Occurs while the dedicated administrator connection is initializing.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DBMIRRORING_CMD',N'BENIGN_BACKGROUND',0,1,N'Occurs when a task is waiting for log records to be flushed to disk. This wait state is expected to be held for long periods of time.',N'Normaler Idle-, Timer-, Queue- oder Hintergrundzustand.',N'Hohe kumulative Werte sind in der Regel erwartbar und kein Engpassbeweis.',N'Standardmäßig aus Top-Ranking ausblenden; nur bei passender Funktionsstörung untersuchen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DBMIRROR_DBM_EVENT',N'HA_REPLICATION',0,1,N'Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.',N'Availability Groups, Mirroring oder HA-Hintergrundarbeit.',N'Je Wait entweder erwarteter Idle-Zustand oder erhöhte Commit-/Redo-/Send-Latenz.',N'Benign-Flag beachten; Replica-Zustand, Queues, Netzwerk und Log-I/O prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DBMIRROR_DBM_MUTEX',N'HA_REPLICATION',2,0,N'Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.',N'Availability Groups, Mirroring oder HA-Hintergrundarbeit.',N'Je Wait entweder erwarteter Idle-Zustand oder erhöhte Commit-/Redo-/Send-Latenz.',N'Benign-Flag beachten; Replica-Zustand, Queues, Netzwerk und Log-I/O prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DBMIRROR_EVENTS_QUEUE',N'HA_REPLICATION',0,1,N'Occurs when database mirroring waits for events to process.',N'Availability Groups, Mirroring oder HA-Hintergrundarbeit.',N'Je Wait entweder erwarteter Idle-Zustand oder erhöhte Commit-/Redo-/Send-Latenz.',N'Benign-Flag beachten; Replica-Zustand, Queues, Netzwerk und Log-I/O prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DBMIRROR_SEND',N'HA_REPLICATION',2,0,N'Occurs when a task is waiting for a communications backlog at the network layer to clear to be able to send messages. Indicates that the communications layer is starting to become overloaded and affect the database mirroring data throughput.',N'Availability Groups, Mirroring oder HA-Hintergrundarbeit.',N'Je Wait entweder erwarteter Idle-Zustand oder erhöhte Commit-/Redo-/Send-Latenz.',N'Benign-Flag beachten; Replica-Zustand, Queues, Netzwerk und Log-I/O prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DBMIRROR_WORKER_QUEUE',N'HA_REPLICATION',0,1,N'Indicates that the database mirroring worker task is waiting for more work.',N'Availability Groups, Mirroring oder HA-Hintergrundarbeit.',N'Je Wait entweder erwarteter Idle-Zustand oder erhöhte Commit-/Redo-/Send-Latenz.',N'Benign-Flag beachten; Replica-Zustand, Queues, Netzwerk und Log-I/O prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DEADLOCK_ENUM_MUTEX',N'OTHER_OR_NEW',2,0,N'Occurs when the deadlock monitor and sys.dm_os_waiting_tasks try to make sure that SQL Server is not running multiple deadlock searches at the same time.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DEADLOCK_TASK_SEARCH',N'OTHER_OR_NEW',2,0,N'Large waiting time on this resource indicates that the server is executing queries on top of sys.dm_os_waiting_tasks, and these queries are blocking deadlock monitor from running deadlock search. This wait type is used by deadlock monitor only. Queries on',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DEBUG',N'OTHER_OR_NEW',2,0,N'Occurs during Transact-SQL and CLR debugging for internal synchronization.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DISABLE_VERSIONING',N'OTHER_OR_NEW',2,0,N'Occurs when SQL Server polls the version transaction manager to see whether the timestamp of the earliest active transaction is later than the timestamp of when the state started changing. If this is this case, all the snapshot transactions that were star',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DISKIO_SUSPEND',N'STORAGE_DATA_IO',2,0,N'Occurs when a task is waiting to access a file when an external backup is active. This is reported for each waiting user process. A count larger than five per user process may indicate that the external backup is taking too much time to finish.',N'Daten-, Metadaten- oder asynchroner Datei-I/O.',N'Hohe Delta-Werte können auf Storage-Latenz, Scans oder Buffer-Pool-Druck hinweisen.',N'sys.dm_io_virtual_file_stats, Volume, Buffer Pool, große Reads und aktive Operation korrelieren.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DISPATCHER_QUEUE_SEMAPHORE',N'BENIGN_BACKGROUND',0,1,N'Occurs when a thread from the dispatcher pool is waiting for more work to process. The wait time for this wait type is expected to increase when the dispatcher is idle.',N'Normaler Idle-, Timer-, Queue- oder Hintergrundzustand.',N'Hohe kumulative Werte sind in der Regel erwartbar und kein Engpassbeweis.',N'Standardmäßig aus Top-Ranking ausblenden; nur bei passender Funktionsstörung untersuchen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DLL_LOADING_MUTEX',N'OTHER_OR_NEW',2,0,N'Occurs once while waiting for the XML parser DLL to load.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DROPTEMP',N'OTHER_OR_NEW',2,0,N'Occurs between attempts to drop a temporary object if the previous attempt failed. The wait duration grows exponentially with each failed drop attempt.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DTC',N'OTHER_OR_NEW',2,0,N'Dieser Wartetyp weist darauf hin, dass die SPID auf den Dienst "Microsoft Distributed Transaction Coordinator" (MS DTC) wartet. (Occurs when a task is waiting on an event that is used to manage state transition. This state controls when the recovery of Microsoft Distributed Transaction Coordinator (MS DTC) transactions occurs after SQL Server receives notification that the MS DTC s)',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DTC_ABORT_REQUEST',N'OTHER_OR_NEW',2,0,N'Eine MSDTC-Worker-Session wartet auf die Übernahme einer verteilten Transaktion, damit sie diese zurückrollen kann; meist verwendet eine andere Session die Transaktion noch.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DTC_RESOLVE',N'OTHER_OR_NEW',2,0,N'Occurs when a recovery task is waiting for the master database in a cross-database transaction so that the task can query the outcome of the transaction.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DTC_STATE',N'OTHER_OR_NEW',2,0,N'Occurs when a task is waiting on an event that protects changes to the internal MS DTC global state object. This state should be held for very short periods of time.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DTC_TMDOWN_REQUEST',N'OTHER_OR_NEW',2,0,N'Occurs in a MS DTC worker session when SQL Server receives notification that the MS DTC service is not available. First, the worker will wait for the MS DTC recovery process to start. Then, the worker waits to obtain the outcome of the distributed transac',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DTC_WAITFOR_OUTCOME',N'OTHER_OR_NEW',2,0,N'Occurs when recovery tasks wait for MS DTC to become active to enable the resolution of prepared transactions.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DUMPTRIGGER',N'OTHER_OR_NEW',2,0,N'Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'DUMP_LOG_COORDINATOR',N'OTHER_OR_NEW',2,0,N'Occurs when a main task is waiting for a subtask to generate data. Ordinarily, this state does not occur. A long wait indicates an unexpected blockage. The subtask should be investigated.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'EC',N'OTHER_OR_NEW',2,0,N'Dieser Wartetyp deutet darauf hin, dass die SPID auf Zugang zum Ausführungskontext wartet. (Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.)',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'EE_PMOLOCK',N'OTHER_OR_NEW',2,0,N'Occurs during synchronization of certain types of memory allocations during statement execution.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'EE_SPECPROC_MAP_INIT',N'OTHER_OR_NEW',2,0,N'Occurs during synchronization of internal procedure hash table creation. This wait can only occur during the initial accessing of the hash table after the SQL Server instance starts.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'ENABLE_VERSIONING',N'OTHER_OR_NEW',2,0,N'Occurs when SQL Server waits for all update transactions in this database to finish before declaring the database ready to transition to snapshot isolation allowed state. This state is used when SQL Server enables snapshot isolation by using the ALTER DAT',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'ERROR_REPORTING_MANAGER',N'OTHER_OR_NEW',2,0,N'Occurs during synchronization of multiple concurrent error log initializations.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'EXCHANGE',N'PARALLELISM',2,0,N'Weist darauf hin, dass die SPID darauf wartet, dass ein paralleler Prozess gestartet oder abgeschlossen wird. (Occurs during synchronization in the query processor exchange iterator during parallel queries.)',N'Synchronisation paralleler Ausführungszweige.',N'Hohe Werte können auf Skew, langsame Zweige oder ungeeignete Parallelität hinweisen.',N'Plan, Row Skew, Spills, CPU, MAXDOP und Cost Threshold prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'EXECSYNC',N'BENIGN_BACKGROUND',0,1,N'Occurs during parallel queries while synchronizing in query processor in areas not related to the exchange iterator. Examples of such areas are bitmaps, large binary objects (LOBs), and the spool iterator. LOBs may frequently use this wait state.',N'Normaler Idle-, Timer-, Queue- oder Hintergrundzustand.',N'Hohe kumulative Werte sind in der Regel erwartbar und kein Engpassbeweis.',N'Standardmäßig aus Top-Ranking ausblenden; nur bei passender Funktionsstörung untersuchen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'EXECUTION_PIPE_EVENT_INTERNAL',N'OTHER_OR_NEW',2,0,N'Occurs during synchronization between producer and consumer parts of batch execution that are submitted through the connection context.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FAILPOINT',N'OTHER_OR_NEW',2,0,N'Identified for informational purposes only. Not supported. Future compatibility is not guaranteed.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FCB_REPLICA_READ',N'OTHER_OR_NEW',2,0,N'Occurs when the reads of a snapshot (or a temporary snapshot created by DBCC) sparse file are synchronized.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FCB_REPLICA_WRITE',N'OTHER_OR_NEW',2,0,N'Occurs when the pushing or pulling of a page to a snapshot (or a temporary snapshot created by DBCC) sparse file is synchronized.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FSAGENT',N'BENIGN_BACKGROUND',0,1,N'Occurs when a FILESTREAM file I/O operation is waiting for a FILESTREAM agent resource that is being used by another file I/O operation.',N'Normaler Idle-, Timer-, Queue- oder Hintergrundzustand.',N'Hohe kumulative Werte sind in der Regel erwartbar und kein Engpassbeweis.',N'Standardmäßig aus Top-Ranking ausblenden; nur bei passender Funktionsstörung untersuchen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FSA_FORCE_OWN_XACT',N'OTHER_OR_NEW',2,0,N'Occurs when a FILESTREAM file I/O operation needs to bind to the associated transaction, but the transaction is currently owned by another session.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FSTR_CONFIG_MUTEX',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait for another FILESTREAM feature reconfiguration to be completed.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FSTR_CONFIG_RWLOCK',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait to serialize access to the FILESTREAM configuration parameters.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FS_FC_RWLOCK',N'OTHER_OR_NEW',2,0,N'Occurs when there is a wait by the FILESTREAM garbage collector to do either of the following: Disable garbage collection (used by backup and restore).',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED'),
(N'FS_GARBAGE_COLLECTOR_SHUTDOWN',N'OTHER_OR_NEW',2,0,N'Occurs when the FILESTREAM garbage collector is waiting for cleanup tasks to be completed.',N'Spezialisierter, interner oder neuer SQL-Server-Wait-Type.',N'Hohe Werte sind nur im Delta- und Workload-Kontext bewertbar.',N'Aktive Tasks, Ressource, Version, Microsoft-Referenz und Versionskontext prüfen.',N'FRAMEWORK_CURATED',N'FRAMEWORK_CURATED');

UPDATE [c] SET [WaitGroup]=[s].[WaitGroup],[Severity]=[s].[Severity],[IsGenerallyBenign]=[s].[IsGenerallyBenign],[Meaning]=[s].[Meaning],
 [TypicalOccurrence]=[s].[TypicalOccurrence],[HighWaitImpact]=[s].[HighWaitImpact],[RecommendedChecks]=[s].[RecommendedChecks],
 [HelpUrl]=N'https://www.sqlskills.com/help/waits/'+[s].[WaitType],[DescriptionSource]=[s].[DescriptionSource],
 [DescriptionQuality]=[s].[DescriptionQuality],[SourceReference]=N'https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-objects/sys-dm-os-wait-stats-transact-sql?view=sql-server-ver17',
 [IsFrameworkDefault]=1,[LastUpdatedUtc]=SYSUTCDATETIME()
FROM [monitor].[WaitTypeCatalog] [c] JOIN @Seed [s] ON [s].[WaitType]=[c].[WaitType] WHERE [c].[IsFrameworkDefault]=1;

INSERT [monitor].[WaitTypeCatalog]
([WaitType],[WaitGroup],[Severity],[IsGenerallyBenign],[Meaning],[TypicalOccurrence],[HighWaitImpact],[RecommendedChecks],[HelpUrl],
 [DescriptionSource],[DescriptionQuality],[SourceReference],[IsFrameworkDefault])
SELECT [s].[WaitType],[s].[WaitGroup],[s].[Severity],[s].[IsGenerallyBenign],[s].[Meaning],[s].[TypicalOccurrence],[s].[HighWaitImpact],[s].[RecommendedChecks],
 N'https://www.sqlskills.com/help/waits/'+[s].[WaitType],[s].[DescriptionSource],[s].[DescriptionQuality],
 N'https://learn.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-objects/sys-dm-os-wait-stats-transact-sql?view=sql-server-ver17',1
FROM @Seed [s] WHERE NOT EXISTS(SELECT 1 FROM [monitor].[WaitTypeCatalog] [c] WHERE [c].[WaitType]=[s].[WaitType]);
GO
