function ConvertTo-EnvPath {
    param([Parameter(Mandatory)][string] $Path)
    if ($script:IsWindowsHost) {
        return $Path.Replace('\', '/')
    }
    return $Path
}

function Format-EnvValue {
    param([AllowEmptyString()][string] $Value)
    if ($Value -match "['\r\n]") {
        throw 'Ein .env-Wert enthält ein nicht unterstütztes Zeichen.'
    }
    return "'$Value'"
}

function Write-EnvFile {
    param([Parameter(Mandatory)][hashtable] $Values)

    $keys = @(
        'QUICKSTART_SCHEMA_VERSION', 'QUICKSTART_SCOPE_ID', 'QUICKSTART_RUNTIME_MODE',
        'COMPOSE_PROJECT_NAME', 'COMPOSE_PROFILES', 'SQL_VERSIONS', 'BIND_ADDRESS',
        'MSSQL_SA_PASSWORD', 'MSSQL_COLLATION', 'MSSQL_AGENT_ENABLED', 'FRAMEWORK_DATABASE', 'INSTALL_FRAMEWORK',
        'RESOURCE_PROFILE', 'CONTAINER_CPUS', 'CONTAINER_MEMORY', 'SQL_MEMORY_LIMIT_MB',
        'STORAGE_LAYOUT', 'LAB_ROOT', 'DATA_ROOT', 'LOG_ROOT', 'BACKUP_ROOT', 'INSTALLER_ROOT',
        'SQL2019_PORT', 'SQL2022_PORT', 'SQL2025_PORT',
        'SQL2019_DATA_DIR', 'SQL2019_LOG_DIR', 'SQL2019_BACKUP_DIR',
        'SQL2022_DATA_DIR', 'SQL2022_LOG_DIR', 'SQL2022_BACKUP_DIR',
        'SQL2025_DATA_DIR', 'SQL2025_LOG_DIR', 'SQL2025_BACKUP_DIR',
        'SQL2019_IMAGE', 'SQL2022_IMAGE', 'SQL2025_IMAGE',
        'IO_PROFILE', 'SLOW_IO_DEVICE', 'SLOW_IO_READ_BPS', 'SLOW_IO_WRITE_BPS'
    )

    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('# Local runtime configuration. This file contains a secret and must not be committed.')
    $lines.Add('# Generated by QuickStart/Docker/Setup.ps1.')
    foreach ($key in $keys) {
        if (-not $Values.ContainsKey($key)) {
            throw "Interner Fehler: .env-Wert '$key' fehlt."
        }
        $lines.Add("$key=$(Format-EnvValue -Value ([string] $Values[$key]))")
    }
    $temporaryPath = "$script:EnvPath.$([guid]::NewGuid().ToString('N')).tmp"
    try {
        [IO.File]::WriteAllLines($temporaryPath, $lines, [Text.UTF8Encoding]::new($false))
        Move-Item -LiteralPath $temporaryPath -Destination $script:EnvPath -Force
        if (-not $script:IsWindowsHost -and (Get-Command -Name chmod -ErrorAction SilentlyContinue)) {
            Invoke-ExternalCommand -FilePath 'chmod' -Arguments @('600', '--', $script:EnvPath) -Quiet | Out-Null
        }
    }
    finally {
        if (Test-Path -LiteralPath $temporaryPath -PathType Leaf) {
            Remove-Item -LiteralPath $temporaryPath -Force
        }
    }
}

function Read-EnvFile {
    if (-not (Test-Path -LiteralPath $script:EnvPath -PathType Leaf)) {
        throw "Die lokale Konfiguration '$script:EnvPath' fehlt. Zuerst Setup ausführen."
    }

    $values = @{}
    foreach ($line in [IO.File]::ReadAllLines($script:EnvPath, [Text.Encoding]::UTF8)) {
        $trimmed = $line.Trim()
        if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith('#')) {
            continue
        }
        $separator = $trimmed.IndexOf('=')
        if ($separator -le 0) {
            throw 'Die .env-Datei enthält eine ungültige Zeile.'
        }
        $name = $trimmed.Substring(0, $separator).Trim()
        if ($name -notmatch '^[A-Z][A-Z0-9_]{0,63}$') {
            throw "Die .env-Datei enthält den ungültigen Variablennamen '$name'."
        }
        if ($values.ContainsKey($name)) {
            throw "Die .env-Datei enthält '$name' mehrfach."
        }
        $value = $trimmed.Substring($separator + 1).Trim()
        if ($value.Length -ge 2 -and $value.StartsWith("'") -and $value.EndsWith("'")) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        elseif ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        $values[$name] = $value
    }
    return $values
}

function Assert-EnvContract {
    param([Parameter(Mandatory)][hashtable] $Env)

    $requiredKeys = @(
        'QUICKSTART_SCHEMA_VERSION', 'QUICKSTART_SCOPE_ID', 'QUICKSTART_RUNTIME_MODE',
        'COMPOSE_PROJECT_NAME', 'COMPOSE_PROFILES', 'SQL_VERSIONS', 'BIND_ADDRESS',
        'MSSQL_SA_PASSWORD', 'MSSQL_COLLATION', 'MSSQL_AGENT_ENABLED',
        'FRAMEWORK_DATABASE', 'INSTALL_FRAMEWORK', 'RESOURCE_PROFILE',
        'CONTAINER_CPUS', 'CONTAINER_MEMORY', 'SQL_MEMORY_LIMIT_MB',
        'STORAGE_LAYOUT', 'LAB_ROOT', 'DATA_ROOT', 'LOG_ROOT', 'BACKUP_ROOT',
        'INSTALLER_ROOT', 'SQL2019_PORT', 'SQL2022_PORT', 'SQL2025_PORT',
        'SQL2019_DATA_DIR', 'SQL2019_LOG_DIR', 'SQL2019_BACKUP_DIR',
        'SQL2022_DATA_DIR', 'SQL2022_LOG_DIR', 'SQL2022_BACKUP_DIR',
        'SQL2025_DATA_DIR', 'SQL2025_LOG_DIR', 'SQL2025_BACKUP_DIR',
        'SQL2019_IMAGE', 'SQL2022_IMAGE', 'SQL2025_IMAGE',
        'IO_PROFILE', 'SLOW_IO_DEVICE', 'SLOW_IO_READ_BPS', 'SLOW_IO_WRITE_BPS'
    )
    foreach ($key in $requiredKeys) {
        if (-not $Env.ContainsKey($key)) {
            throw "Die .env-Datei enthält den erforderlichen Wert '$key' nicht."
        }
    }

    if ($Env.QUICKSTART_SCHEMA_VERSION -ne '1') {
        throw 'Die .env-Datei verwendet eine nicht unterstützte QuickStart-Schemaversion.'
    }
    $scopeId = [string] $Env.QUICKSTART_SCOPE_ID
    if ($scopeId -notmatch '^[a-f0-9]{12}$') {
        throw 'QUICKSTART_SCOPE_ID ist ungültig.'
    }
    if ($Env.COMPOSE_PROJECT_NAME -ne "ssa-quickstart-$scopeId") {
        throw 'COMPOSE_PROJECT_NAME stimmt nicht mit dem QuickStart-Scope überein.'
    }
    if ($Env.QUICKSTART_RUNTIME_MODE -notin @('DOCKER_DESKTOP_WINDOWS', 'DOCKER_ENGINE_LINUX', 'HYPERV_LINUX_DOCKER')) {
        throw 'QUICKSTART_RUNTIME_MODE ist ungültig.'
    }
    if ($Env.BIND_ADDRESS -ne '127.0.0.1') {
        throw 'Der sichere QuickStart bindet SQL-Ports ausschließlich an 127.0.0.1.'
    }
    if ($Env.MSSQL_COLLATION -ne 'SQL_Latin1_General_CP1_CS_AS') {
        throw 'MSSQL_COLLATION weicht vom QuickStart-Vertrag ab.'
    }
    if ($Env.MSSQL_AGENT_ENABLED -notin @('true', 'false')) {
        throw 'MSSQL_AGENT_ENABLED muss true oder false sein.'
    }
    if ($Env.FRAMEWORK_DATABASE -ne 'LabAnalyze') {
        throw 'FRAMEWORK_DATABASE muss LabAnalyze sein.'
    }
    if ($Env.INSTALL_FRAMEWORK -notin @('true', 'false')) {
        throw 'INSTALL_FRAMEWORK muss true oder false sein.'
    }
    if ($Env.RESOURCE_PROFILE -notin @('COMPACT', 'STANDARD', 'PERFORMANCE')) {
        throw 'RESOURCE_PROFILE ist ungültig.'
    }
    $resourceContracts = @{
        COMPACT = @{ Cpus = '2.0'; Memory = '3g'; SqlMemory = '2048' }
        STANDARD = @{ Cpus = '4.0'; Memory = '8g'; SqlMemory = '6144' }
        PERFORMANCE = @{ Cpus = '8.0'; Memory = '16g'; SqlMemory = '12288' }
    }
    $resourceContract = $resourceContracts[[string] $Env.RESOURCE_PROFILE]
    if (
        $Env.CONTAINER_CPUS -ne $resourceContract.Cpus -or
        $Env.CONTAINER_MEMORY -ne $resourceContract.Memory -or
        $Env.SQL_MEMORY_LIMIT_MB -ne $resourceContract.SqlMemory
    ) {
        throw 'Die Ressourcenwerte stimmen nicht mit dem gewählten QuickStart-Profil überein.'
    }

    $password = [string] $Env.MSSQL_SA_PASSWORD
    if (
        $password.Length -lt 16 -or $password.Length -gt 128 -or
        $password -notmatch '[A-Z]' -or $password -notmatch '[a-z]' -or
        $password -notmatch '\d' -or $password -notmatch '[^A-Za-z0-9]' -or
        $password -match "['\r\n]" -or $password -match '\s'
    ) {
        throw 'MSSQL_SA_PASSWORD in .env erfüllt den lokalen QuickStart-Passwortvertrag nicht.'
    }
    if ($Env.STORAGE_LAYOUT -notin @('SINGLE_ROOT', 'SPLIT_DATA_LOG')) {
        throw 'STORAGE_LAYOUT ist ungültig.'
    }
    if ($Env.IO_PROFILE -notin @('NORMAL', 'SLOW_IO')) {
        throw 'IO_PROFILE ist ungültig.'
    }
    if ($Env.IO_PROFILE -eq 'SLOW_IO' -and $Env.QUICKSTART_RUNTIME_MODE -eq 'DOCKER_DESKTOP_WINDOWS') {
        throw 'Slow-I/O ist für Docker Desktop auf Windows nicht zulässig.'
    }
    if ($Env.IO_PROFILE -eq 'SLOW_IO') {
        if ($Env.STORAGE_LAYOUT -ne 'SINGLE_ROOT') {
            throw 'Slow-I/O ist nur mit SINGLE_ROOT zulässig.'
        }
        if ($Env.SLOW_IO_DEVICE -notmatch '^/dev/[A-Za-z0-9_./-]+$') {
            throw 'SLOW_IO_DEVICE ist ungültig.'
        }
        if ($Env.SLOW_IO_READ_BPS -notmatch '^\d+(kb|mb|gb)$' -or $Env.SLOW_IO_WRITE_BPS -notmatch '^\d+(kb|mb|gb)$') {
            throw 'Die Slow-I/O-Raten sind ungültig.'
        }
    }

    $versions = @([string] $Env.SQL_VERSIONS -split ',' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    if ($versions.Count -eq 0 -or @($versions | Where-Object { $_ -notin @('2019', '2022', '2025') }).Count -gt 0) {
        throw 'SQL_VERSIONS enthält einen nicht unterstützten Wert.'
    }
    if (@($versions | Select-Object -Unique).Count -ne $versions.Count) {
        throw 'SQL_VERSIONS enthält doppelte Werte.'
    }
    $expectedProfiles = @($versions | ForEach-Object { "sql$_" }) -join ','
    if ($Env.COMPOSE_PROFILES -ne $expectedProfiles) {
        throw 'COMPOSE_PROFILES stimmt nicht mit SQL_VERSIONS überein.'
    }

    $ports = [Collections.Generic.List[int]]::new()
    foreach ($version in @('2019', '2022', '2025')) {
        $parsedPort = 0
        if (-not [int]::TryParse([string] $Env["SQL${version}_PORT"], [ref] $parsedPort) -or $parsedPort -lt 1024 -or $parsedPort -gt 65535) {
            throw "SQL${version}_PORT ist ungültig."
        }
        $ports.Add($parsedPort)
    }
    if (@($ports | Select-Object -Unique).Count -ne $ports.Count) {
        throw 'Die SQL-Ports in der .env-Datei müssen eindeutig sein.'
    }

    $expectedImages = @{
        '2019' = 'mcr.microsoft.com/mssql/server:2019-latest'
        '2022' = 'mcr.microsoft.com/mssql/server:2022-latest'
        '2025' = 'mcr.microsoft.com/mssql/server:2025-latest'
    }
    foreach ($version in @('2019', '2022', '2025')) {
        if ($Env["SQL${version}_IMAGE"] -ne $expectedImages[$version]) {
            throw "SQL${version}_IMAGE weicht vom veröffentlichten QuickStart-Vertrag ab."
        }
    }

    $labRoot = Get-CanonicalPath -Path ([string] $Env.LAB_ROOT)
    $dataRoot = Get-CanonicalPath -Path ([string] $Env.DATA_ROOT)
    $logRoot = Get-CanonicalPath -Path ([string] $Env.LOG_ROOT)
    $backupRoot = Get-CanonicalPath -Path ([string] $Env.BACKUP_ROOT)
    $installerRoot = Get-CanonicalPath -Path ([string] $Env.INSTALLER_ROOT)
    if (-not $backupRoot.Equals((Get-CanonicalPath -Path (Join-Path $labRoot 'backup')), $script:PathComparison)) {
        throw 'BACKUP_ROOT liegt nicht im erwarteten Lab-Scope.'
    }
    if (-not $installerRoot.Equals((Get-CanonicalPath -Path (Join-Path $labRoot 'control/installer')), $script:PathComparison)) {
        throw 'INSTALLER_ROOT liegt nicht im erwarteten Lab-Scope.'
    }
    if ($Env.STORAGE_LAYOUT -eq 'SINGLE_ROOT') {
        if (-not $dataRoot.Equals((Get-CanonicalPath -Path (Join-Path $labRoot 'data')), $script:PathComparison)) {
            throw 'DATA_ROOT liegt nicht im erwarteten Single-Root-Scope.'
        }
        if (-not $logRoot.Equals((Get-CanonicalPath -Path (Join-Path $labRoot 'log')), $script:PathComparison)) {
            throw 'LOG_ROOT liegt nicht im erwarteten Single-Root-Scope.'
        }
    }
    else {
        Assert-RootsDoNotOverlap -Paths @($labRoot, $dataRoot, $logRoot)
    }

    foreach ($version in @('2019', '2022', '2025')) {
        $expectedData = Get-CanonicalPath -Path (Join-Path $dataRoot $version)
        $expectedLog = Get-CanonicalPath -Path (Join-Path $logRoot $version)
        $expectedBackup = Get-CanonicalPath -Path (Join-Path $backupRoot $version)
        if (-not (Get-CanonicalPath -Path ([string] $Env["SQL${version}_DATA_DIR"])).Equals($expectedData, $script:PathComparison)) {
            throw "SQL${version}_DATA_DIR liegt nicht im markierten Daten-Scope."
        }
        if (-not (Get-CanonicalPath -Path ([string] $Env["SQL${version}_LOG_DIR"])).Equals($expectedLog, $script:PathComparison)) {
            throw "SQL${version}_LOG_DIR liegt nicht im markierten Log-Scope."
        }
        if (-not (Get-CanonicalPath -Path ([string] $Env["SQL${version}_BACKUP_DIR"])).Equals($expectedBackup, $script:PathComparison)) {
            throw "SQL${version}_BACKUP_DIR liegt nicht im markierten Backup-Scope."
        }
    }
}
