#Requires -Version 7.2

function ConvertTo-LabPowerShellSingleQuotedLiteral {
    [CmdletBinding()]
    param([Parameter(Mandatory)][string]$Value)

    return "'$($Value.Replace("'", "''"))'"
}

function Get-LabContainerAutoStartTaskName {
    [CmdletBinding()]
    param([Parameter(Mandatory)][ValidateSet('docker', 'podman')][string]$Provider)

    return "SQL_Server_Lab-$Provider-Autostart"
}

function Get-LabContainerAutoStartScriptPath {
    [CmdletBinding()]
    param([Parameter(Mandatory)][ValidateSet('docker', 'podman')][string]$Provider)

    if (-not $IsWindows) { return $null }
    $root = Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'SQL_Server_Lab/autostart'
    return Join-Path $root "Start-$Provider-Labs.ps1"
}

function New-LabWindowsContainerAutoStartScript {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][ValidateSet('docker', 'podman')][string]$Provider,
        [Parameter(Mandatory)][string]$RuntimePath,
        [Parameter(Mandatory)][string]$Path
    )

    $runtimeLiteral = ConvertTo-LabPowerShellSingleQuotedLiteral -Value $RuntimePath
    $runtimeBootstrap = if ($Provider -eq 'docker') {
        $desktopCandidates = @(
            (Join-Path $env:ProgramFiles 'Docker/Docker/Docker Desktop.exe'),
            (Join-Path ([Environment]::GetFolderPath('LocalApplicationData')) 'Docker/Docker Desktop.exe')
        )
        $desktopPath = $desktopCandidates | Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } | Select-Object -First 1
        if ($desktopPath) {
            $desktopLiteral = ConvertTo-LabPowerShellSingleQuotedLiteral -Value $desktopPath
            @"
if (-not (& `$runtime info 2>`$null)) {
    Start-Process -FilePath $desktopLiteral -WindowStyle Hidden
}
"@
        }
        else { '' }
    }
    else {
        @"
& `$runtime machine start 1>`$null 2>`$null
"@
    }

    $content = @"
# Generated by SQL_Server_Lab. Manual changes are overwritten.
# Starts only managed containers carrying sql-server-lab.autostart=on.
#Requires -Version 7.2
`$ErrorActionPreference = 'SilentlyContinue'
`$runtime = $runtimeLiteral
$runtimeBootstrap
`$deadline = [DateTime]::UtcNow.AddMinutes(3)
do {
    & `$runtime info 1>`$null 2>`$null
    if (`$LASTEXITCODE -eq 0) { break }
    Start-Sleep -Seconds 3
} while ([DateTime]::UtcNow -lt `$deadline)

if (`$LASTEXITCODE -ne 0) { exit 1 }
`$containerIds = @(& `$runtime ps -a -q --filter 'label=sql-server-lab.autostart=on' 2>`$null)
foreach (`$containerId in `$containerIds) {
    if (-not [string]::IsNullOrWhiteSpace([string]`$containerId)) {
        & `$runtime start ([string]`$containerId).Trim() 1>`$null 2>`$null
    }
}
"@

    $directory = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
        $null = New-Item -Path $directory -ItemType Directory -Force
    }
    Set-Content -LiteralPath $Path -Value $content -Encoding utf8
}

function Test-LabWindowsContainerAutoStartIdentity {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$TaskUser,
        [Parameter(Mandatory)][string]$CurrentUser
    )

    if ([string]::Equals($TaskUser, $CurrentUser, [StringComparison]::OrdinalIgnoreCase)) { return $true }

    $currentParts = @($CurrentUser -split '\\', 2)
    return (
        $TaskUser -notmatch '\\' -and
        $currentParts.Count -eq 2 -and
        [string]::Equals($currentParts[0], [Environment]::MachineName, [StringComparison]::OrdinalIgnoreCase) -and
        [string]::Equals($TaskUser, $currentParts[1], [StringComparison]::OrdinalIgnoreCase)
    )
}

function Test-LabWindowsContainerAutoStartTaskReusable {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]$Task,
        [Parameter(Mandatory)][string]$PowerShellPath,
        [Parameter(Mandatory)][string]$Arguments,
        [Parameter(Mandatory)][string]$CurrentUser
    )

    $actions = @($Task.Actions)
    $triggers = @($Task.Triggers)
    if ($actions.Count -ne 1 -or $triggers.Count -ne 1 -or -not $Task.Principal) { return $false }

    $principalMatches = Test-LabWindowsContainerAutoStartIdentity -TaskUser ([string]$Task.Principal.UserId) -CurrentUser $CurrentUser
    $triggerMatches = Test-LabWindowsContainerAutoStartIdentity -TaskUser ([string]$triggers[0].UserId) -CurrentUser $CurrentUser
    return (
        $principalMatches -and
        $triggerMatches -and
        [string]$Task.Principal.LogonType -eq 'Interactive' -and
        [string]$Task.Principal.RunLevel -eq 'Limited' -and
        $triggers[0].Enabled -ne $false -and
        [string]::Equals([string]$actions[0].Execute, $PowerShellPath, [StringComparison]::OrdinalIgnoreCase) -and
        [string]::Equals([string]$actions[0].Arguments, $Arguments, [StringComparison]::Ordinal)
    )
}

function Enable-LabWindowsContainerAutoStartCoordinator {
    [CmdletBinding()]
    param([Parameter(Mandatory)][ValidateSet('docker', 'podman')][string]$Provider)

    $runtimeCommand = Get-Command $Provider -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $runtimeCommand) { throw "LAB_CONTAINER_AUTOSTART_RUNTIME_NOT_FOUND: $Provider" }

    $requiredCommands = @('Get-ScheduledTask', 'New-ScheduledTaskAction', 'New-ScheduledTaskTrigger', 'New-ScheduledTaskPrincipal', 'New-ScheduledTaskSettingsSet', 'Register-ScheduledTask')
    foreach ($commandName in $requiredCommands) {
        if (-not (Get-Command $commandName -ErrorAction SilentlyContinue)) {
            throw "LAB_CONTAINER_AUTOSTART_SCHEDULED_TASKS_UNAVAILABLE: $commandName"
        }
    }

    $scriptPath = Get-LabContainerAutoStartScriptPath -Provider $Provider
    New-LabWindowsContainerAutoStartScript -Provider $Provider -RuntimePath $runtimeCommand.Source -Path $scriptPath

    $pwshPath = (Get-Process -Id $PID).Path
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent().Name
    $taskArguments = "-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$scriptPath`""
    $taskName = Get-LabContainerAutoStartTaskName -Provider $Provider
    $existingTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
    if ($existingTask -and (Test-LabWindowsContainerAutoStartTaskReusable -Task $existingTask -PowerShellPath $pwshPath -Arguments $taskArguments -CurrentUser $currentUser)) {
        return [PSCustomObject]@{ Provider = $Provider; Mode = 'WindowsLogonTask'; Name = $taskName; ScriptPath = $scriptPath }
    }

    $action = New-ScheduledTaskAction -Execute $pwshPath -Argument $taskArguments
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $currentUser
    $principal = New-ScheduledTaskPrincipal -UserId $currentUser -LogonType Interactive -RunLevel Limited
    $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 10) -StartWhenAvailable -MultipleInstances IgnoreNew

    try {
        $null = Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description "Startet SQL_Server_Lab-$Provider-Instanzen mit autostart=on nach der Benutzeranmeldung." -Force -ErrorAction Stop
    }
    catch {
        $existingTask = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
        if ($existingTask -and (Test-LabWindowsContainerAutoStartTaskReusable -Task $existingTask -PowerShellPath $pwshPath -Arguments $taskArguments -CurrentUser $currentUser)) {
            return [PSCustomObject]@{ Provider = $Provider; Mode = 'WindowsLogonTask'; Name = $taskName; ScriptPath = $scriptPath }
        }
        throw "LAB_CONTAINER_AUTOSTART_TASK_REGISTRATION_FAILED: $($_.Exception.Message)"
    }

    return [PSCustomObject]@{ Provider = $Provider; Mode = 'WindowsLogonTask'; Name = $taskName; ScriptPath = $scriptPath }
}

function Enable-LabContainerHostAutoStart {
    [CmdletBinding()]
    param([Parameter(Mandatory)][ValidateSet('docker', 'podman')][string]$Provider)

    if ($IsWindows) {
        return Enable-LabWindowsContainerAutoStartCoordinator -Provider $Provider
    }

    if ($Provider -eq 'podman' -and $IsLinux) {
        $systemctl = Get-Command systemctl -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $systemctl) { throw 'LAB_PODMAN_AUTOSTART_SYSTEMD_UNAVAILABLE: systemctl fehlt.' }
        $loginctl = Get-Command loginctl -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $loginctl) { throw 'LAB_PODMAN_AUTOSTART_LINGER_UNAVAILABLE: loginctl fehlt.' }
        & $loginctl.Source enable-linger ([Environment]::UserName) 1>$null
        if ($LASTEXITCODE -ne 0) { throw 'LAB_PODMAN_AUTOSTART_LINGER_ENABLE_FAILED: systemd-Linger konnte für den aktuellen Benutzer nicht aktiviert werden.' }
        & $systemctl.Source --user enable podman-restart.service 1>$null
        if ($LASTEXITCODE -ne 0) { throw 'LAB_PODMAN_AUTOSTART_SYSTEMD_ENABLE_FAILED: podman-restart.service konnte nicht aktiviert werden.' }
        return [PSCustomObject]@{ Provider = $Provider; Mode = 'PodmanUserSystemdWithLinger'; Name = 'podman-restart.service' }
    }

    if ($Provider -eq 'docker' -and $IsLinux) {
        $systemctl = Get-Command systemctl -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1
        if (-not $systemctl) { throw 'LAB_DOCKER_AUTOSTART_SYSTEMD_UNAVAILABLE: systemctl fehlt.' }
        & $systemctl.Source is-enabled docker.service 1>$null 2>$null
        if ($LASTEXITCODE -ne 0) { throw 'LAB_DOCKER_AUTOSTART_DAEMON_DISABLED: docker.service muss beim Boot aktiviert sein.' }
        return [PSCustomObject]@{ Provider = $Provider; Mode = 'DockerSystemdWithRestartPolicy'; Name = 'docker.service' }
    }

    throw "LAB_CONTAINER_AUTOSTART_HOST_UNSUPPORTED: $Provider auf dieser Hostplattform."
}

function Remove-LabContainerAutoStartCoordinatorIfUnused {
    [CmdletBinding()]
    param([Parameter(Mandatory)][ValidateSet('docker', 'podman')][string]$Provider)

    if (-not $IsWindows) { return }
    $ids = @(& $Provider ps -a -q --filter 'label=sql-server-lab.autostart=on' 2>$null | Where-Object { $_ })
    if ($LASTEXITCODE -ne 0 -or $ids.Count -gt 0) { return }

    $taskName = Get-LabContainerAutoStartTaskName -Provider $Provider
    if (Get-Command Unregister-ScheduledTask -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
    }
    $scriptPath = Get-LabContainerAutoStartScriptPath -Provider $Provider
    if ($scriptPath -and (Test-Path -LiteralPath $scriptPath -PathType Leaf)) {
        Remove-Item -LiteralPath $scriptPath -Force
    }
}
