#Requires -Version 7.2
[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$results=[Collections.Generic.List[object]]::new();function Add-CheckResult{param([string]$Name,[bool]$Success)$results.Add([pscustomobject]@{Name=$Name;Success=$Success});Write-Host "$(if($Success){'PASS'}else{'FAIL'}): $Name"}
$private=Get-Content -LiteralPath (Join-Path $repoRoot 'Private/PortableContainerTransferPreflight.ps1') -Raw -Encoding utf8;$public=Get-Content -LiteralPath (Join-Path $repoRoot 'Public/Invoke-SqlServerLabPortableContainerTransferPreflight.ps1') -Raw -Encoding utf8
$preflightPath=Join-Path $repoRoot 'Private/PortableContainerTransferPreflight.ps1'
$tokens=$null;$parseErrors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($preflightPath,[ref]$tokens,[ref]$parseErrors)
$functionDefinitions=@($ast.FindAll({param($node)$node -is [Management.Automation.Language.FunctionDefinitionAst]},$true))
$duplicateDefinitions=@($functionDefinitions|Group-Object Name|Where-Object Count -gt 1)
Add-CheckResult 'Preflight-Datei hat eindeutige Funktionsdefinitionen und einen fehlerfreien AST' ($parseErrors.Count -eq 0 -and $duplicateDefinitions.Count -eq 0)
$schemas=@('portable-container-transfer-preflight-request.schema.json','portable-container-transfer-preflight-result.schema.json','portable-container-transfer-preflight-journal.schema.json');foreach($schema in $schemas){Add-CheckResult "Schema ist valide: $schema" ((Get-Content -LiteralPath (Join-Path $repoRoot "Schemas/$schema") -Raw -Encoding utf8|Test-Json))}
Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;$module=Import-Module (Join-Path $repoRoot 'SqlServerLab.psd1') -Force -PassThru
try{
 $sourceRun='11111111-1111-1111-1111-111111111111';$targetRun='22222222-2222-2222-2222-222222222222';$backupId='33333333-3333-3333-3333-333333333333';$root=Join-Path ([IO.Path]::GetTempPath()) "sql-server-lab-transfer-preflight-$([guid]::NewGuid().ToString('N'))";New-Item -ItemType Directory -Path $root -Force|Out-Null
 $selection=@([pscustomobject]@{SourceDatabaseName='SourceDb';TargetDatabaseName='TargetDb';BackupSetId=$backupId})
 $result=Invoke-SqlServerLabPortableContainerTransferPreflight -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers $selection -DataRoot $root -StateRoot $root
 Add-CheckResult 'Fehlende lokale Backup-Evidence blockiert vor jeder Staging-Mutation' ($result.Status -eq 'BLOCKED' -and $result.CleanupStatus -eq 'NO_MUTATION_PERFORMED' -and 'BACKUP_LOCAL_OWNERSHIP_OR_INTEGRITY_UNVERIFIABLE' -in $result.Blockers -and $result.TransferExecutorStatus -eq 'BLOCKED' -and -not $result.TransferExecutionImplemented)
 $json=$result|ConvertTo-Json -Depth 20;Add-CheckResult 'Oeffentliches Ergebnis bleibt ohne Pfad, Secret, Rohheader, Container-ID und Endpoint' (($json -notmatch '(?i)""(?:password|credential|secret|path|containerid|hostname|port)""\s*:|""Header(?:Database|Position|Backup)""\s*:') -and ($json|Test-Json -SchemaFile (Join-Path $repoRoot 'Schemas/portable-container-transfer-preflight-result.schema.json')))
 $duplicateRejected=& $module {param($sourceRun,$targetRun,$backupId)try{New-LabPortableContainerTransferPreflightRequest -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='a';TargetDatabaseName='t1';BackupSetId=$backupId},[pscustomobject]@{SourceDatabaseName='a';TargetDatabaseName='t2';BackupSetId='44444444-4444-4444-4444-444444444444'})|Out-Null;$false}catch{$_.Exception.Message -eq 'PORTABLE_CONTAINER_TRANSFER_PREFLIGHT_SOURCE_DATABASE_DUPLICATE'}} $sourceRun $targetRun $backupId
 Add-CheckResult 'Doppelte Quelle und BackupSetId werden vor jeder Mutation abgewiesen' $duplicateRejected
 $backupDuplicateRejected=& $module {param($sourceRun,$targetRun,$backupId)try{New-LabPortableContainerTransferPreflightRequest -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='a';TargetDatabaseName='t1';BackupSetId=$backupId},[pscustomobject]@{SourceDatabaseName='b';TargetDatabaseName='t2';BackupSetId=$backupId})|Out-Null;$false}catch{$_.Exception.Message -eq 'PORTABLE_CONTAINER_TRANSFER_PREFLIGHT_BACKUPSET_DUPLICATE'}} $sourceRun $targetRun $backupId
 Add-CheckResult 'Doppelte BackupSetId wird vor jeder Mutation abgewiesen' $backupDuplicateRejected
 $beforeWhatIf=@(Get-ChildItem -LiteralPath $root -Force).Count;$whatIfResult=@(Invoke-SqlServerLabPortableContainerTransferPreflight -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers $selection -DataRoot $root -StateRoot $root -WhatIf)[-1];$afterWhatIf=@(Get-ChildItem -LiteralPath $root -Force).Count
 Add-CheckResult 'WhatIf erzeugt weder Journal noch Stagingverzeichnis oder SQL-Verbindung' ($whatIfResult.CleanupStatus -eq 'NO_MUTATION_PERFORMED' -and $beforeWhatIf -eq $afterWhatIf)
 $rootTraversal=& $module {param($Path)$anchor=[IO.Path]::GetPathRoot((Resolve-Path -LiteralPath $Path).Path);Assert-LabPortableContainerTransferPreflightNoReparsePath -Root $anchor -Path $Path;$true} $root
 Add-CheckResult 'NoReparse-Pfadpruefung bewahrt das Plattformwurzelverzeichnis einschliesslich Linux /' ($rootTraversal -eq $true)
 $headerValid=& $module { $header=[pscustomobject]@{Position=1;BackupType=1;SoftwareVersionMajor=17;DatabaseName='SourceDb';BindingID=[guid]'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';FamilyGUID=[guid]'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';HasBackupChecksums=$true;IsDamaged=$false;IsSnapshot=$false;KeyAlgorithm='NO_Encryption';EncryptorType=[DBNull]::Value;EncryptorThumbprint=[DBNull]::Value};Test-LabPortableContainerTransferPreflightHeaderObservation -Header $header -ExpectedDatabaseName SourceDb }
 Add-CheckResult 'HEADERONLY akzeptiert BindingID und das dokumentierte NO_Encryption-Muster' ($headerValid -eq $true)
 $headerNullTripletValid=& $module { $header=[pscustomobject]@{Position=1;BackupType=1;SoftwareVersionMajor=17;DatabaseName='SourceDb';BindingID=[guid]'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';FamilyGUID=[guid]'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';HasBackupChecksums=$true;IsDamaged=$false;IsSnapshot=$false;KeyAlgorithm=[DBNull]::Value;EncryptorType=[DBNull]::Value;EncryptorThumbprint=[DBNull]::Value};Test-LabPortableContainerTransferPreflightHeaderObservation -Header $header -ExpectedDatabaseName SourceDb }
 Add-CheckResult 'HEADERONLY akzeptiert nur die vollstaendige dokumentierte NULL-Kombination des unverschluesselten SQL-2025-Mediums' ($headerNullTripletValid -eq $true)
 $headerDatabaseGuidRejected=& $module { try{$header=[pscustomobject]@{Position=1;BackupType=1;SoftwareVersionMajor=17;DatabaseName='SourceDb';DatabaseGuid=[guid]'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';FamilyGUID=[guid]'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';HasBackupChecksums=$true;IsDamaged=$false;IsSnapshot=$false;KeyAlgorithm='NO_Encryption';EncryptorType=[DBNull]::Value;EncryptorThumbprint=[DBNull]::Value};Test-LabPortableContainerTransferPreflightHeaderObservation -Header $header -ExpectedDatabaseName SourceDb|Out-Null;$false}catch{$_.Exception.Message -eq 'SQL_MEDIA_HEADERONLY_GUID_INVALID'} }
 Add-CheckResult 'HEADERONLY verwendet BindingID statt einer nicht dokumentierten DatabaseGuid-Spalte' $headerDatabaseGuidRejected
 $headerUnsafe=& $module { try{$header=[pscustomobject]@{Position=1;BackupType=1;SoftwareVersionMajor=17;DatabaseName='SourceDb';BindingID=[guid]'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';FamilyGUID=[guid]'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';HasBackupChecksums=$true;IsDamaged=$false;IsSnapshot=$false;KeyAlgorithm='AES_256';EncryptorType='CERTIFICATE';EncryptorThumbprint=[byte[]](1,2,3)};Test-LabPortableContainerTransferPreflightHeaderObservation -Header $header -ExpectedDatabaseName SourceDb|Out-Null;$false}catch{$_.Exception.Message -eq 'SQL_MEDIA_HEADERONLY_ENCRYPTION_UNKNOWN_OR_UNSUPPORTED'} }
 Add-CheckResult 'HEADERONLY blockiert verschluesselte und unbekannte Medienformen' $headerUnsafe
 $podmanMountMapping=& $module {param($root)$hostRoot=(Resolve-Path -LiteralPath $root).Path.TrimEnd('\','/');$drive=[IO.Path]::GetPathRoot($hostRoot).TrimEnd('\','/');$vmPath=('/mnt/'+$drive.Substring(0,1).ToLowerInvariant()+'/'+$hostRoot.Substring(3).Replace('\','/')).TrimEnd('/');[pscustomobject]@{Valid=(Test-LabPortableContainerTransferPreflightBoundBackupMount -Provider podman -MountSource $vmPath -HostRoot $hostRoot);Invalid=(Test-LabPortableContainerTransferPreflightBoundBackupMount -Provider podman -MountSource ($vmPath+'-foreign') -HostRoot $hostRoot)}} $root
 Add-CheckResult 'Podman-WSL-Bind-Mount wird nur gegen den persistenten Host-Backup-Root akzeptiert' ($podmanMountMapping.Valid -and -not $podmanMountMapping.Invalid)
 $dockerDesktopMountMapping=& $module {param($root)if(-not $IsWindows){return $true};$hostRoot=(Resolve-Path -LiteralPath $root).Path.TrimEnd('\','/');$drive=[IO.Path]::GetPathRoot($hostRoot).TrimEnd('\','/');$vmPath=('/run/desktop/mnt/host/'+$drive.Substring(0,1).ToLowerInvariant()+'/'+$hostRoot.Substring(3).Replace('\','/')).TrimEnd('/');[pscustomobject]@{Valid=(Test-LabPortableContainerTransferPreflightBoundBackupMount -Provider docker -MountSource $vmPath -HostRoot $hostRoot);Invalid=(Test-LabPortableContainerTransferPreflightBoundBackupMount -Provider docker -MountSource ($vmPath+'-foreign') -HostRoot $hostRoot)}} $root
 Add-CheckResult 'Docker-Desktop-VM-Bind-Mount wird nur gegen den persistenten Host-Backup-Root akzeptiert' ($dockerDesktopMountMapping.Valid -and -not $dockerDesktopMountMapping.Invalid)
 $operation=Join-Path $root 'operation';$journal=Join-Path $root 'operation.journal.json';New-Item -ItemType Directory -Path $operation|Out-Null;$stage=Join-Path $operation '33333333-3333-3333-3333-333333333333.bak';$missingStage=Join-Path $operation '44444444-4444-4444-4444-444444444444.bak';Set-Content -LiteralPath $stage -Value x;Set-Content -LiteralPath $journal -Value x;$cleanup=& $module {param($root,$journal,$operation,$stage,$missingStage)Invoke-LabPortableContainerTransferPreflightCleanup -HostRoot $root -JournalPath $journal -OperationDirectory $operation -StageFiles @($stage,$missingStage)} $root $journal $operation $stage $missingStage
 Add-CheckResult 'Cleanup toleriert noch nicht erzeugte geplante Stagefiles und entfernt keine rekursiven Reste' ($cleanup -eq 'CLEANED' -and -not(Test-Path -LiteralPath $operation) -and -not(Test-Path -LiteralPath $journal))
 $foreignOperation=Join-Path $root 'foreign-operation';$foreignJournal=Join-Path $root 'foreign-operation.journal.json';New-Item -ItemType Directory -Path $foreignOperation|Out-Null;$foreignStage=Join-Path $foreignOperation '33333333-3333-3333-3333-333333333333.bak';$foreignRemainder=Join-Path $foreignOperation 'foreign.bak';Set-Content -LiteralPath $foreignStage -Value x;Set-Content -LiteralPath $foreignRemainder -Value foreign;Set-Content -LiteralPath $foreignJournal -Value journal;$foreignCleanup=& $module {param($root,$journal,$operation,$stage)Invoke-LabPortableContainerTransferPreflightCleanup -HostRoot $root -JournalPath $journal -OperationDirectory $operation -StageFiles @($stage)} $root $foreignJournal $foreignOperation $foreignStage
 Add-CheckResult 'Cleanup laesst fremde Reste und zugehoeriges Journal unveraendert' ($foreignCleanup -eq 'RECOVERY_REQUIRED' -and (Test-Path -LiteralPath $foreignRemainder) -and (Test-Path -LiteralPath $foreignJournal))
 $collisionEvidence=& $module {param($root,$sourceRun,$targetRun,$backupId)
    $request=New-LabPortableContainerTransferPreflightRequest -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='SourceDb';TargetDatabaseName='TargetDb';BackupSetId=$backupId})
    $leaf="transfer-preflight-$($request.OperationId)";$journal=Join-Path $root "$leaf.journal.json";Set-Content -LiteralPath $journal -Value 'foreign-journal' -NoNewline
    Set-Item Function:script:Get-LabPortableContainerTransferPreflightBackups -Value {param($Request,$DataRoot)[pscustomobject]@{Records=@([pscustomobject]@{Public=[pscustomobject]@{BackupSetId=$backupId;SourceDatabaseName='SourceDb';TargetDatabaseName='TargetDb';Sha256=('a'*64);Bytes=1;HeaderOnly='NOT_EXECUTED';VerifyOnly='NOT_EXECUTED'};SourcePath='unused';StageFileName="$backupId.bak"});Blockers=@()}}
    Set-Item Function:script:Get-LabPortableContainerTransferPreflightTargetBinding -Value {param($Request,$StateRoot)[pscustomobject]@{Available=$true;Code=$null;Public=[pscustomobject]@{Provider='docker';RunId=$Request.TargetRunId;InstanceId=$Request.TargetInstanceId;RuntimeScopeId='scope';BindingStatus='VERIFIED'};HostRoot=$root;HostName='127.0.0.1';Port=1433;ContainerId=('a'*64)}}
    Set-Item Function:script:Get-LabRelationalCoreSecret -Value {param($RunId,$StateRoot)[Security.SecureString]::new()}
    Set-Item Function:script:Test-LabPortableContainerTransferPreflightSqlConnection -Value {param($Binding,$Secret)}
    $result=Invoke-LabPortableContainerTransferPreflight -Request $request -DataRoot $root -StateRoot $root -MutationAuthorized
    [pscustomobject]@{Result=$result;Journal=(Get-Content -LiteralPath $journal -Raw)}
 } $root $sourceRun $targetRun $backupId
 Add-CheckResult 'Kollision blockiert vor Journal- oder Reste-Cleanup und bewahrt vorhandenes Journal bytegenau' ($collisionEvidence.Result.Status -eq 'BLOCKED' -and $collisionEvidence.Result.CleanupStatus -eq 'NO_MUTATION_PERFORMED' -and 'SQL_MEDIA_PREFLIGHT_OPERATION_COLLISION' -in $collisionEvidence.Result.Blockers -and $collisionEvidence.Journal -ceq 'foreign-journal')
 Add-CheckResult 'WhatIf, sichere Verbindung, Journal und Drift-Pruefung sind vertraglich vorhanden' ((Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('WhatIf') -and $public -match 'SupportsShouldProcess' -and $public -match '\$PSCmdlet.ShouldProcess' -and $private -match 'Data Source=\$\(' -and $private -match 'Pooling=False' -and $private -match 'Persist Security Info=False' -and $private -match 'INTENT_PERSISTED' -and $private -match 'SQL_MEDIA_PREFLIGHT_TARGET_BINDING_DRIFT' -and $private -notmatch 'Remove-Item\s+-LiteralPath\s+\$operationDirectory\s+-Recurse')
 Add-CheckResult 'Nur explizite Transfers, SqlCredential und parametrisierte SQL-Medienpruefung sind vorhanden' ((Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('DatabaseTransfers') -and -not(Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('AllEligible') -and $private -match 'System\.Data\.SqlClient\.SqlCredential' -and $private -match 'RESTORE HEADERONLY FROM DISK = @backupPath;' -and $private -match 'RESTORE VERIFYONLY FROM DISK = @backupPath WITH CHECKSUM, STOP_ON_ERROR;' -and $private -notmatch 'Invoke-SqlQuery|sqlcmd\s+-P')
 Add-CheckResult 'Mount-Fallbacks und Transferfreigabe sind ausgeschlossen' ($private -notmatch "ArgumentList\s+@\('(?:cp|exec|mkdir|mount)" -and $private -notmatch "\b(?:docker|podman)\s+(?:cp|exec|mkdir|mount|recreate)\b" -and $private -match 'SQL_VISIBLE_STAGING_BINDING_UNAVAILABLE' -and $private -match "TransferExecutorStatus='BLOCKED'")
}finally{Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;if($root){Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
$failed=@($results|Where-Object{-not $_.Success});if($failed){throw "PORTABLE CONTAINER TRANSFER PREFLIGHT CHECKS FAILED: $($failed.Name -join '; ')"};Write-Host "PORTABLE CONTAINER TRANSFER PREFLIGHT CHECKS: PASS ($($results.Count))"
