#Requires -Version 7.2
[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$results=[Collections.Generic.List[object]]::new();function Add-CheckResult{param([string]$Name,[bool]$Success)$results.Add([pscustomobject]@{Name=$Name;Success=$Success});Write-Host "$(if($Success){'PASS'}else{'FAIL'}): $Name"}
$private=Get-Content -LiteralPath (Join-Path $repoRoot 'Private/PortableContainerTransferPreflight.ps1') -Raw -Encoding utf8
$public=Get-Content -LiteralPath (Join-Path $repoRoot 'Public/Invoke-SqlServerLabPortableContainerTransferPreflight.ps1') -Raw -Encoding utf8
$schemas=@('portable-container-transfer-preflight-request.schema.json','portable-container-transfer-preflight-result.schema.json','portable-container-transfer-preflight-journal.schema.json')
foreach($schema in $schemas){Add-CheckResult "Schema ist valide: $schema" ((Get-Content -LiteralPath (Join-Path $repoRoot "Schemas/$schema") -Raw -Encoding utf8|Test-Json))}
Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;$module=Import-Module (Join-Path $repoRoot 'SqlServerLab.psd1') -Force -PassThru
try {
 $sourceRun='11111111-1111-1111-1111-111111111111';$targetRun='22222222-2222-2222-2222-222222222222';$backupId='33333333-3333-3333-3333-333333333333';$root=Join-Path ([IO.Path]::GetTempPath()) "sql-server-lab-transfer-preflight-$([guid]::NewGuid().ToString('N'))";New-Item -ItemType Directory -Path $root -Force|Out-Null
 $result=Invoke-SqlServerLabPortableContainerTransferPreflight -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='SourceDb';TargetDatabaseName='TargetDb';BackupSetId=$backupId}) -DataRoot $root -StateRoot $root
 Add-CheckResult 'Fehlende lokale Backup-Evidence blockiert vor jeder Staging-Mutation' ($result.Status -eq 'BLOCKED' -and $result.CleanupStatus -eq 'NO_MUTATION_PERFORMED' -and 'BACKUP_LOCAL_OWNERSHIP_OR_INTEGRITY_UNVERIFIABLE' -in $result.Blockers -and $result.TransferExecutorStatus -eq 'BLOCKED' -and -not $result.TransferExecutionImplemented)
 Add-CheckResult 'Oeffentliches Ergebnis bleibt pfad-, secret- und rohheaderfrei' ((($result|ConvertTo-Json -Depth 20) -notmatch '(?i)password|credential|secret|path|header.*(database|position|backup)') -and (($result|ConvertTo-Json -Depth 20)|Test-Json -SchemaFile (Join-Path $repoRoot 'Schemas/portable-container-transfer-preflight-result.schema.json')))
 Add-CheckResult 'Nur explizite Transfers, SqlCredential und parametrisierte SQL-Medienpruefung sind vorhanden' ((Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('DatabaseTransfers') -and -not (Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('AllEligible') -and $private -match 'System\.Data\.SqlClient\.SqlCredential' -and $private -match "RESTORE HEADERONLY FROM DISK = @backupPath;" -and $private -match 'RESTORE VERIFYONLY FROM DISK = @backupPath WITH CHECKSUM, STOP_ON_ERROR;' -and $private -notmatch 'Invoke-SqlQuery|sqlcmd\s+-P')
 Add-CheckResult 'Mount-Fallbacks und Transferfreigabe sind ausgeschlossen' ($private -notmatch "ArgumentList\s+@\('(?:cp|exec|mkdir|mount)" -and $private -notmatch "\b(?:docker|podman)\s+(?:cp|exec|mkdir|mount|recreate)\b" -and $private -match 'SQL_VISIBLE_STAGING_BINDING_UNAVAILABLE' -and $private -match "TransferExecutorStatus='BLOCKED'")
} finally {Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;if($root){Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
$failed=@($results|Where-Object{-not $_.Success});if($failed){throw "PORTABLE CONTAINER TRANSFER PREFLIGHT CHECKS FAILED: $($failed.Name -join '; ')"};Write-Host "PORTABLE CONTAINER TRANSFER PREFLIGHT CHECKS: PASS ($($results.Count))"
