#Requires -Version 7.2
[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$results=[Collections.Generic.List[object]]::new();function Add-CheckResult{param([string]$Name,[bool]$Success)$results.Add([pscustomobject]@{Name=$Name;Success=$Success});Write-Host "$(if($Success){'PASS'}else{'FAIL'}): $Name"}
$root=Join-Path ([IO.Path]::GetTempPath()) "sql-server-lab-transfer-executor-$([guid]::NewGuid().ToString('N'))";New-Item -ItemType Directory -Path $root -Force|Out-Null;$sourceRun='11111111-1111-1111-1111-111111111111';$targetRun='22222222-2222-2222-2222-222222222222';$backupId='33333333-3333-3333-3333-333333333333'
Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;$module=Import-Module (Join-Path $repoRoot 'SqlServerLab.psd1') -Force -PassThru
try{$batch=Get-SqlServerLabPortableContainerTransferExecutorPlan -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='SourceDb';TargetDatabaseName='TargetDb';BackupSetId=$backupId}) -DataRoot $root -StateRoot $root;$plan=$batch.Transfers[0].Plan;$journal=& $module {param($p) New-LabPortableContainerTransferExecutorJournal -Plan $p} $plan;$result=[pscustomobject]@{Batch=$batch;Plan=$plan;Journal=$journal}
 Add-CheckResult 'Mehrdatenbank-Executorplan bleibt ohne Inhaltsvergleich und SQL-Revalidierung strikt blockiert' ($result.Batch.SelectionMode -eq 'EXPLICIT' -and $result.Batch.Status -eq 'BLOCKED' -and -not $result.Batch.ExecutionImplemented -and 'CONTENT_COMPARISON_PROFILE_UNAVAILABLE' -in $result.Plan.Blockers -and 'BACKUP_HEADERONLY_AND_LIVE_CHECKSUM_VERIFYONLY_NOT_EXECUTED' -in $result.Plan.Blockers)
 Add-CheckResult 'Plan bindet beide angeforderten Runs und Instanzen ohne Secrets' ($result.Plan.Source.RunId -eq $sourceRun -and $result.Plan.Target.RunId -eq $targetRun -and $result.Plan.Source.InstanceId -eq 'source' -and $result.Plan.Target.InstanceId -eq 'target' -and (($result.Plan|ConvertTo-Json -Depth 30) -notmatch '(?i)password|credential|secret'))
 Add-CheckResult 'Journal behauptet keine Mutation und erfuellt den Schema-Vertrag' ($result.Journal.Status -eq 'BLOCKED' -and $result.Journal.Recovery -eq 'NO_MUTATION_PERFORMED' -and (($result.Journal|ConvertTo-Json -Depth 40)|Test-Json -SchemaFile (Join-Path $repoRoot 'Schemas/portable-container-transfer-executor-journal.schema.json')))
 $allEligible=Get-SqlServerLabPortableContainerTransferExecutorPlan -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -AllEligible -DataRoot $root -StateRoot $root
 Add-CheckResult 'AllEligible bleibt ohne sichere Quellinventur explizit blockiert' ($allEligible.SelectionMode -eq 'ALL_ELIGIBLE' -and $allEligible.Transfers.Count -eq 0 -and 'ALL_ELIGIBLE_INVENTORY_CREDENTIAL_REQUIRED' -in $allEligible.Blockers)
}finally{Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}
$failed=@($results|Where-Object{-not $_.Success});if($failed){throw "PORTABLE CONTAINER TRANSFER EXECUTOR CHECKS FAILED: $($failed.Name -join '; ')"};Write-Host "PORTABLE CONTAINER TRANSFER EXECUTOR CHECKS: PASS ($($results.Count))"
