#Requires -Version 7.2
[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$results=[Collections.Generic.List[object]]::new();function Add-CheckResult{param([string]$Name,[bool]$Success)$results.Add([pscustomobject]@{Name=$Name;Success=$Success});Write-Host "$(if($Success){'PASS'}else{'FAIL'}): $Name"}
$private=Get-Content -LiteralPath (Join-Path $repoRoot 'Private/PortableContainerTransferPreflight.ps1') -Raw -Encoding utf8;$public=Get-Content -LiteralPath (Join-Path $repoRoot 'Public/Invoke-SqlServerLabPortableContainerTransferPreflight.ps1') -Raw -Encoding utf8
$schemas=@('portable-container-transfer-preflight-request.schema.json','portable-container-transfer-preflight-result.schema.json','portable-container-transfer-preflight-journal.schema.json');foreach($schema in $schemas){Add-CheckResult "Schema ist valide: $schema" ((Get-Content -LiteralPath (Join-Path $repoRoot "Schemas/$schema") -Raw -Encoding utf8|Test-Json))}
Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;$module=Import-Module (Join-Path $repoRoot 'SqlServerLab.psd1') -Force -PassThru
try{
 $sourceRun='11111111-1111-1111-1111-111111111111';$targetRun='22222222-2222-2222-2222-222222222222';$backupId='33333333-3333-3333-3333-333333333333';$root=Join-Path ([IO.Path]::GetTempPath()) "sql-server-lab-transfer-preflight-$([guid]::NewGuid().ToString('N'))";New-Item -ItemType Directory -Path $root -Force|Out-Null
 $selection=@([pscustomobject]@{SourceDatabaseName='SourceDb';TargetDatabaseName='TargetDb';BackupSetId=$backupId})
 $result=Invoke-SqlServerLabPortableContainerTransferPreflight -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers $selection -DataRoot $root -StateRoot $root
 Add-CheckResult 'Fehlende lokale Backup-Evidence blockiert vor jeder Staging-Mutation' ($result.Status -eq 'BLOCKED' -and $result.CleanupStatus -eq 'NO_MUTATION_PERFORMED' -and 'BACKUP_LOCAL_OWNERSHIP_OR_INTEGRITY_UNVERIFIABLE' -in $result.Blockers -and $result.TransferExecutorStatus -eq 'BLOCKED' -and -not $result.TransferExecutionImplemented)
 $json=$result|ConvertTo-Json -Depth 20;Add-CheckResult 'Oeffentliches Ergebnis bleibt ohne Pfad, Secret, Rohheader, Container-ID und Endpoint' (($json -notmatch '(?i)""(?:password|credential|secret|path|containerid|hostname|port)""\s*:|""Header(?:Database|Position|Backup)""\s*:') -and ($json|Test-Json -SchemaFile (Join-Path $repoRoot 'Schemas/portable-container-transfer-preflight-result.schema.json')))
 $duplicateRejected=& $module {param($sourceRun,$targetRun,$backupId)try{New-LabPortableContainerTransferPreflightRequest -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='a';TargetDatabaseName='t1';BackupSetId=$backupId},[pscustomobject]@{SourceDatabaseName='a';TargetDatabaseName='t2';BackupSetId='44444444-4444-4444-4444-444444444444'})|Out-Null;$false}catch{$_.Exception.Message -eq 'PORTABLE_CONTAINER_TRANSFER_PREFLIGHT_SOURCE_DATABASE_DUPLICATE'}} $sourceRun $targetRun $backupId
 Add-CheckResult 'Doppelte Quelle und BackupSetId werden vor jeder Mutation abgewiesen' $duplicateRejected
 $backupDuplicateRejected=& $module {param($sourceRun,$targetRun,$backupId)try{New-LabPortableContainerTransferPreflightRequest -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers @([pscustomobject]@{SourceDatabaseName='a';TargetDatabaseName='t1';BackupSetId=$backupId},[pscustomobject]@{SourceDatabaseName='b';TargetDatabaseName='t2';BackupSetId=$backupId})|Out-Null;$false}catch{$_.Exception.Message -eq 'PORTABLE_CONTAINER_TRANSFER_PREFLIGHT_BACKUPSET_DUPLICATE'}} $sourceRun $targetRun $backupId
 Add-CheckResult 'Doppelte BackupSetId wird vor jeder Mutation abgewiesen' $backupDuplicateRejected
 $beforeWhatIf=@(Get-ChildItem -LiteralPath $root -Force).Count;$whatIfResult=@(Invoke-SqlServerLabPortableContainerTransferPreflight -SourceRunId $sourceRun -SourceInstanceId source -TargetRunId $targetRun -TargetInstanceId target -DatabaseTransfers $selection -DataRoot $root -StateRoot $root -WhatIf)[-1];$afterWhatIf=@(Get-ChildItem -LiteralPath $root -Force).Count
 Add-CheckResult 'WhatIf erzeugt weder Journal noch Stagingverzeichnis oder SQL-Verbindung' ($whatIfResult.CleanupStatus -eq 'NO_MUTATION_PERFORMED' -and $beforeWhatIf -eq $afterWhatIf)
 $headerValid=& $module { $header=[pscustomobject]@{Position=1;BackupType=1;SoftwareVersionMajor=17;DatabaseName='SourceDb';DatabaseGuid=[guid]'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';FamilyGUID=[guid]'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';HasBackupChecksums=$true;IsDamaged=$false;IsSnapshot=$false;EncryptorType='NO_Encryption'};Test-LabPortableContainerTransferPreflightHeaderObservation -Header $header -ExpectedDatabaseName SourceDb }
 Add-CheckResult 'HEADERONLY akzeptiert nur den vollstaendigen sicheren Einzelsatz' ($headerValid -eq $true)
 $headerUnsafe=& $module { try{$header=[pscustomobject]@{Position=1;BackupType=1;SoftwareVersionMajor=17;DatabaseName='SourceDb';DatabaseGuid=[guid]'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';FamilyGUID=[guid]'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';HasBackupChecksums=$true;IsDamaged=$false;IsSnapshot=$false;EncryptorType='UNKNOWN'};Test-LabPortableContainerTransferPreflightHeaderObservation -Header $header -ExpectedDatabaseName SourceDb|Out-Null;$false}catch{$_.Exception.Message -eq 'SQL_MEDIA_HEADERONLY_ENCRYPTION_UNKNOWN_OR_UNSUPPORTED'} }
 Add-CheckResult 'HEADERONLY blockiert unbekannte Verschluesselung' $headerUnsafe
 $operation=Join-Path $root 'operation';$journal=Join-Path $root 'operation.journal.json';New-Item -ItemType Directory -Path $operation|Out-Null;$stage=Join-Path $operation '33333333-3333-3333-3333-333333333333.bak';Set-Content -LiteralPath $stage -Value x;Set-Content -LiteralPath $journal -Value x;$cleanup=& $module {param($root,$journal,$operation,$stage)Invoke-LabPortableContainerTransferPreflightCleanup -HostRoot $root -JournalPath $journal -OperationDirectory $operation -StageFiles @($stage)} $root $journal $operation $stage
 Add-CheckResult 'Cleanup entfernt nur exakt journalisierte eigene Dateien ohne Rekursion' ($cleanup -eq 'CLEANED' -and -not(Test-Path -LiteralPath $operation) -and -not(Test-Path -LiteralPath $journal))
 Add-CheckResult 'WhatIf, sichere Verbindung, Journal und Drift-Pruefung sind vertraglich vorhanden' ((Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('WhatIf') -and $public -match 'SupportsShouldProcess' -and $public -match '\$PSCmdlet.ShouldProcess' -and $private -match 'SqlConnectionStringBuilder' -and $private -match 'Pooling=\$false' -and $private -match 'PersistSecurityInfo=\$false' -and $private -match 'INTENT_PERSISTED' -and $private -match 'SQL_MEDIA_PREFLIGHT_TARGET_BINDING_DRIFT' -and $private -notmatch 'Remove-Item\s+-LiteralPath\s+\$operationDirectory\s+-Recurse')
 Add-CheckResult 'Nur explizite Transfers, SqlCredential und parametrisierte SQL-Medienpruefung sind vorhanden' ((Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('DatabaseTransfers') -and -not(Get-Command Invoke-SqlServerLabPortableContainerTransferPreflight).Parameters.ContainsKey('AllEligible') -and $private -match 'System\.Data\.SqlClient\.SqlCredential' -and $private -match 'RESTORE HEADERONLY FROM DISK = @backupPath;' -and $private -match 'RESTORE VERIFYONLY FROM DISK = @backupPath WITH CHECKSUM, STOP_ON_ERROR;' -and $private -notmatch 'Invoke-SqlQuery|sqlcmd\s+-P')
 Add-CheckResult 'Mount-Fallbacks und Transferfreigabe sind ausgeschlossen' ($private -notmatch "ArgumentList\s+@\('(?:cp|exec|mkdir|mount)" -and $private -notmatch "\b(?:docker|podman)\s+(?:cp|exec|mkdir|mount|recreate)\b" -and $private -match 'SQL_VISIBLE_STAGING_BINDING_UNAVAILABLE' -and $private -match "TransferExecutorStatus='BLOCKED'")
}finally{Remove-Module SqlServerLab -Force -ErrorAction SilentlyContinue;if($root){Remove-Item $root -Recurse -Force -ErrorAction SilentlyContinue}}
$failed=@($results|Where-Object{-not $_.Success});if($failed){throw "PORTABLE CONTAINER TRANSFER PREFLIGHT CHECKS FAILED: $($failed.Name -join '; ')"};Write-Host "PORTABLE CONTAINER TRANSFER PREFLIGHT CHECKS: PASS ($($results.Count))"
