#Requires -Version 7.2
[CmdletBinding()]param()
$ErrorActionPreference='Stop';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path
. (Join-Path $PSScriptRoot '../Common/CheckResult.ps1')
$failures=[Collections.Generic.List[string]]::new();$passed=0;$module=$null;$upstreamJob=$null;$session=$null
$testRoot=[IO.Path]::GetFullPath((Join-Path ([IO.Path]::GetTempPath()) ('sql-lab-shared-gateway-session-test-'+[guid]::NewGuid().ToString('N'))));$null=[IO.Directory]::CreateDirectory($testRoot);$disposable=[Collections.Generic.List[IDisposable]]::new()
function New-TestCa {$rsa=[Security.Cryptography.RSA]::Create(2048);$script:disposable.Add($rsa);$r=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=Session Test CA',$rsa,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$r.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($true,$false,0,$true));$r.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509KeyUsageExtension]::new([Security.Cryptography.X509Certificates.X509KeyUsageFlags]::KeyCertSign,$true));$c=$r.CreateSelfSigned([datetimeoffset]::UtcNow.AddDays(-1),[datetimeoffset]::UtcNow.AddDays(2));$script:disposable.Add($c);$c}
function New-TestLeaf($Ca){$rsa=[Security.Cryptography.RSA]::Create(2048);$script:disposable.Add($rsa);$r=[Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=host.docker.internal',$rsa,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1);$r.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($false,$false,0,$true));$r.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509KeyUsageExtension]::new([Security.Cryptography.X509Certificates.X509KeyUsageFlags]::DigitalSignature,[bool]$true));$eku=[Security.Cryptography.OidCollection]::new();$null=$eku.Add([Security.Cryptography.Oid]::new('1.3.6.1.5.5.7.3.1'));$r.CertificateExtensions.Add([Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension]::new($eku,$true));$san=[Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new();$san.AddDnsName('host.docker.internal');$r.CertificateExtensions.Add($san.Build());$serial=[byte[]]::new(16);[Security.Cryptography.RandomNumberGenerator]::Fill($serial);$public=$r.Create($Ca,[datetimeoffset]::UtcNow.AddHours(-1),[datetimeoffset]::UtcNow.AddDays(1),$serial);$script:disposable.Add($public);$c=[Security.Cryptography.X509Certificates.RSACertificateExtensions]::CopyWithPrivateKey($public,$rsa);$script:disposable.Add($c);[pscustomobject]@{Certificate=$c;PrivateKey=$rsa}}
function Get-FreePort {$l=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,0);$l.Start();try{([Net.IPEndPoint]$l.LocalEndpoint).Port}finally{$l.Stop()}}
function New-TestSecureString([string]$Value){$secure=[SecureString]::new();foreach($character in $Value.ToCharArray()){$secure.AppendChar($character)};$secure.MakeReadOnly();$secure}
function Reject([scriptblock]$Action,[string]$Code){try{& $Action|Out-Null;$false}catch{$_.Exception.Message -ceq $Code}}
try {
    $runtime=Join-Path $testRoot 'runtime.bin';$model=Join-Path $testRoot 'model.gguf';$cert=Join-Path $testRoot 'cert.pem';$key=Join-Path $testRoot 'key.pem';$caPath=Join-Path $testRoot 'ca.pem';[IO.File]::WriteAllText($runtime,'synthetic runtime');[IO.File]::WriteAllText($model,'synthetic model')
    $ca=New-TestCa;$leaf=New-TestLeaf $ca;[IO.File]::WriteAllText($cert,$leaf.Certificate.ExportCertificatePem());[IO.File]::WriteAllText($key,$leaf.PrivateKey.ExportPkcs8PrivateKeyPem());[IO.File]::WriteAllText($caPath,$ca.ExportCertificatePem())
    $upstreamPort=Get-FreePort;$gatewayPort=Get-FreePort;while($gatewayPort -eq $upstreamPort){$gatewayPort=Get-FreePort};$ready=Join-Path $testRoot 'upstream.ready';$stop=Join-Path $testRoot 'upstream.stop'
    $server={param($port,$ready,$stop,$model)
        $listener=[Net.Sockets.TcpListener]::new([Net.IPAddress]::Loopback,$port);$listener.Start(8);[IO.File]::WriteAllText($ready,'ready')
        try{while(-not(Test-Path -LiteralPath $stop)){if(-not $listener.Pending()){Start-Sleep -Milliseconds 20;continue};$client=$listener.AcceptTcpClient();$stream=$client.GetStream();try{$bytes=[Collections.Generic.List[byte]]::new();$match=0;while($bytes.Count -lt 16384 -and $match -lt 4){$v=$stream.ReadByte();if($v -lt 0){break};$bytes.Add([byte]$v);$want=@(13,10,13,10)[$match];if($v -eq $want){$match++}elseif($v -eq 13){$match=1}else{$match=0}};$header=[Text.Encoding]::ASCII.GetString($bytes.ToArray());$length=0;if($header -match '(?im)^Content-Length:\s*([0-9]+)\s*$'){$length=[int]$Matches[1]};$body=[byte[]]::new($length);$offset=0;while($offset -lt $length){$read=$stream.Read($body,$offset,$length-$offset);if($read -le 0){break};$offset+=$read};$response=@{object='list';model=$model;data=@(@{object='embedding';index=0;embedding=@(0.1,0.2,0.3)})}|ConvertTo-Json -Depth 8 -Compress;$payload=[Text.Encoding]::UTF8.GetBytes($response);$head=[Text.Encoding]::ASCII.GetBytes("HTTP/1.1 200 OK`r`nContent-Type: application/json`r`nContent-Length: $($payload.Length)`r`nConnection: close`r`n`r`n");$stream.Write($head);$stream.Write($payload);$stream.Flush()}finally{$stream.Dispose();$client.Dispose()}}}finally{$listener.Stop()}}
    $upstreamJob=Start-Job -ScriptBlock $server -ArgumentList $upstreamPort,$ready,$stop,'bound-model';$deadline=[datetime]::UtcNow.AddSeconds(15);while(-not(Test-Path $ready)){if($upstreamJob.State -ne 'Running' -or [datetime]::UtcNow -gt $deadline){throw 'synthetic upstream failed'};Start-Sleep -Milliseconds 50}
    $module=Import-Module (Join-Path $repoRoot 'SqlServerLab.psd1') -Force -PassThru;$stateRoot=Join-Path $testRoot 'state'
    $consumers=@([pscustomobject]@{RunId='11111111-1111-4111-8111-111111111111';InstanceId='a';DatabaseId='22222222-2222-4222-8222-222222222222';ExternalModelName='SharedA';ApiKeyReference='SQL_SERVER_LAB_SECRET_SHARED_AI_A'},[pscustomobject]@{RunId='33333333-3333-4333-8333-333333333333';InstanceId='b';DatabaseId='44444444-4444-4444-8444-444444444444';ExternalModelName='SharedB';ApiKeyReference='SQL_SERVER_LAB_SECRET_SHARED_AI_B'})
    $plan=Get-SqlServerLabAiSharedGatewayPlan -GatewayId shared-session -Location "https://host.docker.internal:$gatewayPort/v1/embeddings" -UpstreamBackend LlamaCppCuda -UpstreamLocation "http://127.0.0.1:$upstreamPort/v1/embeddings" -RuntimeModel bound-model -Dimension 3 -InputProfile raw -ModelSha256 (Get-FileHash $model -Algorithm SHA256).Hash.ToLowerInvariant() -RuntimeSha256 (Get-FileHash $runtime -Algorithm SHA256).Hash.ToLowerInvariant() -ServerCertificateSha256 $leaf.Certificate.GetCertHashString([Security.Cryptography.HashAlgorithmName]::SHA256).ToLowerInvariant() -CertificateAuthoritySha256 $ca.GetCertHashString([Security.Cryptography.HashAlgorithmName]::SHA256).ToLowerInvariant() -Consumer $consumers
    $null=$plan|Register-SqlServerLabAiSharedGatewayStorage -RuntimePath $runtime -ModelPath $model -CertificatePath $cert -PrivateKeyPath $key -CertificateAuthorityPath $caPath -StateRoot $stateRoot -Confirm:$false
    $keyA=New-TestSecureString 'AAAAAAAAAAAAAAAAAAAAAAAA';$keyB=New-TestSecureString 'BBBBBBBBBBBBBBBBBBBBBBBB';$keys=@{SQL_SERVER_LAB_SECRET_SHARED_AI_A=$keyA;SQL_SERVER_LAB_SECRET_SHARED_AI_B=$keyB}
    Add-CheckResult 'WhatIf startet keine Session' ($null -eq ($plan|Start-SqlServerLabAiSharedGatewaySession -ApiKeyByReference $keys -StateRoot $stateRoot -WhatIf))
    $session=$plan|Start-SqlServerLabAiSharedGatewaySession -ApiKeyByReference $keys -StateRoot $stateRoot -StartTimeoutSeconds 20 -LeaseSeconds 60 -Confirm:$false
    Add-CheckResult 'Start liefert schema-validiertes ownergebundenes Receipt' ($session.Status -ceq 'SESSION_ENDPOINT_VERIFIED' -and ($session|ConvertTo-Json -Depth 20|Test-Json -SchemaFile (Join-Path $repoRoot 'Schemas/ai-shared-gateway-session-receipt.schema.json')))
    $operationRoot=& $module {param($id)$script:AiSharedGatewaySessions[$id].OperationRoot} $session.OperationId
    $processBinding=& $module {param($id)$owned=$script:AiSharedGatewaySessions[$id];$receipt=Get-Content -LiteralPath $owned.ReceiptPath -Raw|ConvertFrom-Json;[bool]($receipt.OperationId -ceq $id -and [int]$receipt.ProcessId -eq $owned.Worker.Id -and $receipt.OwnerNonce -ceq $owned.OwnerNonce -and $receipt.OwnerNonce -cmatch '^[a-f0-9]{64}$')} $session.OperationId
    Add-CheckResult 'Workerreceipt bindet Operation, PID und plattformneutralen Owner-Nonce' $processBinding
    Add-CheckResult 'Worker löscht beide temporären Schlüsseldateien nach dem Einlesen' (-not(Test-Path (Join-Path $operationRoot 'consumer-keys.json')) -and -not(Test-Path (Join-Path $operationRoot 'upstream-key.txt')))
    & $module {param($p,$k)Invoke-LabAiSharedGatewaySessionProbe -Plan $p -ApiKey $k -TimeoutSeconds 5} $plan $keyB
    Add-CheckResult 'Zweiter geplanter Consumer authentifiziert sich am selben Endpoint' $true
    $auth=& $module {Test-LabAiSharedGatewaySessionBearer -Authorization 'Bearer BBBBBBBBBBBBBBBBBBBBBBBB' -Secrets @('AAAAAAAAAAAAAAAAAAAAAAAA','BBBBBBBBBBBBBBBBBBBBBBBB')}
    $badAuth=& $module {Test-LabAiSharedGatewaySessionBearer -Authorization 'Bearer CCCCCCCCCCCCCCCCCCCCCCCC' -Secrets @('AAAAAAAAAAAAAAAAAAAAAAAA','BBBBBBBBBBBBBBBBBBBBBBBB')}
    Add-CheckResult 'Mehrfachauthentifizierung akzeptiert nur einen gebundenen Schlüssel' ($auth -and -not $badAuth)
    $json=$session|ConvertTo-Json -Depth 20
    Add-CheckResult 'Receipt enthält weder Secret noch lokalen Pfad' ($json -notmatch 'AAAAAAAA|BBBBBBBB' -and $json -notmatch [regex]::Escape($testRoot))
    Add-CheckResult 'Unvollständige Schlüsselzuordnung scheitert geschlossen' (Reject {& $module {param($p,$m)Resolve-LabAiSharedGatewaySessionKeys $p $m} $plan @{SQL_SERVER_LAB_SECRET_SHARED_AI_A=$keyA}} 'AI_SHARED_GATEWAY_SESSION_API_KEY_SET_MISMATCH')
    Add-CheckResult 'Doppelte Consumer-Schlüssel werden abgewiesen' (Reject {& $module {param($p,$m)Resolve-LabAiSharedGatewaySessionKeys $p $m} $plan @{SQL_SERVER_LAB_SECRET_SHARED_AI_A=$keyA;SQL_SERVER_LAB_SECRET_SHARED_AI_B=$keyA}} 'AI_SHARED_GATEWAY_SESSION_API_KEY_DUPLICATE')
    $cleanup=Stop-SqlServerLabAiSharedGatewaySession -OperationId $session.OperationId -Confirm:$false;$session=$null
    Add-CheckResult 'Stop bestätigt Prozess-/Listenercleanup und entfernt Operationszustand' ($cleanup.Status -ceq 'CLEANUP_SUCCEEDED' -and -not(Test-Path $operationRoot))
    Add-CheckResult 'Fremde OperationId wird nicht angefasst' (Reject {Stop-SqlServerLabAiSharedGatewaySession -OperationId ([guid]::NewGuid().ToString('D')) -Confirm:$false} 'AI_SHARED_GATEWAY_SESSION_OWNERSHIP_NOT_FOUND')
    $workerSource=Get-Content (Join-Path $repoRoot 'Tools/Invoke-AiSharedGatewaySessionWorker.ps1') -Raw
    Add-CheckResult 'Worker bindet Loopback und begrenzt den direkten Upstreamtransport' ($workerSource -match 'IPAddress\]::Loopback' -and $workerSource -match '\.UseProxy=\$false' -and $workerSource -match '\.AllowAutoRedirect=\$false' -and $workerSource -match 'ResponseHeadersRead' -and $workerSource -match 'upstreamOutput\.Length\+\$upstreamRead -gt 1MB')
    $ownerSource=Get-Content (Join-Path $repoRoot 'Private/LlamaCppOwnedRuntime.ps1') -Raw
    Add-CheckResult 'Modulentladung schließt auch Shared-Gateway-Ownerkanäle' ($ownerSource -match '\$script:AiSharedGatewaySessions' -and $ownerSource -match 'StandardInput\.Close\(\)')
    Add-CheckResult 'Öffentliche Befehle sind manifestexportiert' ((Get-Command Start-SqlServerLabAiSharedGatewaySession).ModuleName -ceq 'SqlServerLab' -and (Get-Command Stop-SqlServerLabAiSharedGatewaySession).ModuleName -ceq 'SqlServerLab')
}
finally {
    if($session -and $module){try{Stop-SqlServerLabAiSharedGatewaySession -OperationId $session.OperationId -Confirm:$false|Out-Null}catch{}}
    [IO.File]::WriteAllText((Join-Path $testRoot 'upstream.stop'),'stop');if($upstreamJob){$null=$upstreamJob|Wait-Job -Timeout 10;$upstreamJob|Remove-Job -Force}
    if($module){Remove-Module $module -Force -ErrorAction SilentlyContinue};foreach($item in @($disposable)){try{$item.Dispose()}catch{}};if(Test-Path $testRoot){Remove-Item $testRoot -Recurse -Force}
}
if($failures.Count){throw ($failures -join '; ')}
Write-Host "AI SHARED GATEWAY SESSION: PASS ($passed)"
